namespace AquaModelLibrary.Data.PSO2.Constants
{
    public class EnemyData
    {
        public static string rebootEnemy = "enemy/en_";
        public static string[] rebootRegions = new string[]
        {
            "r00",
            "r01",
            "r02",
            "r03",
            "r04",
            "s01",
            "s02",
            "s03",
            "s04",
            "",
        };
        public static string[] rebootFaction = new string[]
        {
            "gd",
            "nat",
            "unk",
            "alt",
            "ani",
            "non",
            "dbg",
            "",
        };
        public static string[] rebootEnNames = new string[]
        {
            "1ng",
            "2ng",
            "10av",
            "11av",
            "9av",
            "abn",
            "akm",
            "armma",
            "bat",
            "bea",
            "bir",
            "bis",
            "bkt",
            "boa",
            "box",
            "bra",
            "brs",
            "cam",
            "can",
            "cas",
            "chk",
            "cli",
            "crb",
            "der",
            "dks",
            "dra",
            "dro",
            "dwf",
            "dvs",
            "dvs",
            "emp",
            "fan",
            "figman",
            "fih",
            "flg",
            "flo",
            "for",
            "gdn",
            "gia",
            "gma",
            "god",
            "god0",
            "god1",
            "god2",
            "god3",
            "god4",
            "gor",
            "gos",
            "hal",
            "hip",
            "hmc",
            "hog",
            "hpo",
            "hrp",
            "hum",
            "ins",
            "kic",
            "kit",
            "kpy",
            "ksg",
            "ktn",
            "leg",
            "lzd",
            "mag",
            "mam",
            "mog",
            "mon",
            "monki",
            "month",
            "moo",
            "moveonly",
            "moveupdown",
            "mrt",
            "mtl",
            "nod",
            "nyb",
            "pan",
            "phe",
            "pun",
            "pyc",
            "rap",
            "rbt",
            "rei",
            "rkt",
            "rob",
            "rpt",
            "shotl",
            "shots",
            "shp",
            "sin",
            "sip",
            "sli",
            "slm",
            "sna",
            "snk",
            "sol",
            "tan",
            "tao",
            "tat",
            "tig",
            "tis",
            "tkm",
            "trf",
            "tur",
            "tyu",
            "ufo",
            "ush",
            "verificationenemy",
            "vdr",
            "wic",
            "wlf",
            "wol",
            "zmr",
            "zrf",
            "",
        };

        public static string[] rebootEnemyEnd = new string[]
        {
            "1ng",
            "2ng",
            "10av",
            "10avbi",
            "11av",
            "11avbi",
            "9av",
            "0",
            "00",
            "1",
            "1ng",
            "01",
            "2",
            "02",
            "3",
            "03",
            "4",
            "04",
            "a",
            "atm",
            "atmbi",
            "ax",
            "axld",
            "b",
            "ba",
            "ba2",
            "babi",
            "bald",
            "bi",
            "bo",
            "c",
            "ch",
            "cl",
            "cm",
            "cm",
            "d",
            "de",
            "e",
            "ea",
            "el",
            "ex",
            "f",
            "fl",
            "gr",
            "gu",
            "ha",
            "hm",
            "ice",
            "icem",
            "icef",
            "kn",
            "gs",
            "lu",
            "luld",
            "m",
            "mi",
            "mo",
            "mobi",
            "mon",
            "old",
            "rai",
            "ri",
            "ribo",
            "ribold",
            "rild",
            "robi",
            "rs",
            "s",
            "sm",
            "sm2",
            "sn",
            "sw",
            "swbo",
            "swbold",
            "swld",
            "tmsp",
            "th",
            "thum",
            "thuf",
            "ud1",
            "ud2",
            "w",
            "wi",
            "yz",
            "",
        };

        public static string[] rebootEndOther = new string[]
        {
            "common",
            "eff",
        };

        public static string[] rebootEnemyMisc = new string[]
        {
            "en_common_boost_eff.ice",
            "enemy/en_common_boost1.ice",
            "enemy/en_common_boost2.ice",
            "enemy/en_common_boost3.ice",
            "enemy/en_common_boost4.ice",
            "enemy/en_common_boost5.ice",
            "enemy/en_common_boost1_rgn.ice",
            "enemy/en_common_boost2_rgn.ice",
            "enemy/en_common_boost3_rgn.ice",
            "enemy/en_common_boost4_rgn.ice",
            "enemy/en_common_boost5_rgn.ice",
            "enemy/en_common_se.ice",
            "enemy/en_effect_dead.ice",
            "enemy/en_effect_common_v70100.ice"
        };


        public static List<string> classicPetNames = new List<string>()
        {
            "Synchro Animations,シンクロウ モショーン,en_pe_anubis_g.ice",
            "Synchro aqn,シンクロウ aqn,en_pe_anubis_g01.ice",
            "Synchro Model,シンクロウ モデル,en_pe_anubis_g01_mesh.ice",
            "Synchro aqn 2,シンクロウ aqn 2,en_pe_anubis_g02.ice",
            "Synchro Model 2,シンクロウ モデル 2,en_pe_anubis_g02_mesh.ice",
            "Synchro Effects,シンクロウ エフェクト,en_pe_anubis_g_eff.ice",
            "Trim Animations,トリム モショーン,en_pe_bird_b.ice",
            "Trim aqn,トリム aqn,en_pe_bird_b01.ice",
            "Trim Model,トリム モデル,en_pe_bird_b01_mesh.ice",
            "Trim aqn 2,トリム aqn 2,en_pe_bird_b02.ice",
            "Trim Model 2,トリム モデル 2,en_pe_bird_b02_mesh.ice",
            "Trim Effects,トリム エフェクト,en_pe_bird_b_eff.ice",
            "Aero Animations,エアロ モショーン,en_pe_bird_n.ice",
            "Aero aqn,エアロ aqn,en_pe_bird_n01.ice",
            "Aero Model,エアロ モデル,en_pe_bird_n01_mesh.ice",
            "Aero aqn 2,エアロ aqn 2,en_pe_bird_n02.ice",
            "Aero Model 2,エアロ モデル 2,en_pe_bird_n02_mesh.ice",
            "Aero Effects,エアロ エフェクト,en_pe_bird_n_eff.ice",
            "Wanda Animations,ワンダ モショーン,en_pe_dog_a.ice",
            "Wanda aqn,ワンダ aqn,en_pe_dog_a01.ice",
            "Wanda Model,ワンダ モデル,en_pe_dog_a01_mesh.ice",
            "Wanda aqn 2,ワンダ aqn 2,en_pe_dog_a02.ice",
            "Wanda Model 2,ワンダ モデル 2,en_pe_dog_a02_mesh.ice",
            "Wanda Effects,ワンダ エフェクト,en_pe_dog_a_eff.ice",
            "Jinga Animations,ジンガ モショーン,en_pe_dog_m.ice",
            "Jinga aqn,ジンガ aqn,en_pe_dog_m01.ice",
            "Jinga Model,ジンガ モデル,en_pe_dog_m01_mesh.ice",
            "Jinga aqn 2,ジンガ aqn 2,en_pe_dog_m02.ice",
            "Jinga Model 2,ジンガ モデル 2,en_pe_dog_m02_mesh.ice",
            "Jinga Effects,ジンガ エフェクト,en_pe_dog_m_eff.ice",
            "Redran Animations,レドラン モショーン,en_pe_dragon_h.ice",
            "Redran aqn,レドラン aqn,en_pe_dragon_h01.ice",
            "Redran Model,レドラン モデル,en_pe_dragon_h01_mesh.ice",
            "Redran aqn 2,レドラン aqn 2,en_pe_dragon_h02.ice",
            "Redran Model 2,レドラン モデル 2,en_pe_dragon_h02_mesh.ice",
            "Redran Effects,レドラン エフェクト,en_pe_dragon_h_eff.ice",
            "Vulcan Animations,バルカン モショーン,en_pe_drkhero_l.ice",
            "Vulcan aqn,バルカン aqn,en_pe_drkhero_l01.ice",
            "Vulcan Model,バルカン モデル,en_pe_drkhero_l01_mesh.ice",
            "Vulcan Effects,バルカン エフェクト,en_pe_drkhero_l_eff.ice",
            "Herbie Animations,グラス モショーン,en_pe_glass_k.ice",
            "Herbie aqn,グラス aqn,en_pe_glass_k01.ice",
            "Herbie Model,グラス モデル,en_pe_glass_k01_mesh.ice",
            "Herbie Effects,グラス エフェクト,en_pe_glass_k_eff.ice",
            "Marron aqn,マロン aqn,en_pe_longear_d01.ice",
            "Marron Model,マロン モデル,en_pe_longear_d01_mesh.ice",
            "Melon aqn,メロン aqn,en_pe_longear_d02.ice",
            "Melon Model,メロン モデル,en_pe_longear_d02_mesh.ice",
            "Marron aqn 2,マロン aqn 2,en_pe_longear_d03.ice",
            "Marron Model 2,マロン モデル 2,en_pe_longear_d03_mesh.ice",
            "Melon aqn 2,メロン aqn 2,en_pe_longear_d04.ice",
            "Melon Model 2,メロン モデル 2,en_pe_longear_d04_mesh.ice",
            "Marron Animations,マロン モショーン,en_pe_longear_d_common.ice",
            "Marron Effects,マロン エフェクト,en_pe_longear_d_eff.ice",
            "Marron rgn,マロン rgn,en_pe_longear_d_rgn.ice",
            "Rappy Animations,ラッピー モショーン,en_pe_rappy_f.ice",
            "Rappy Effects,ラッピー エフェクト,en_pe_rappy_f_eff.ice",
            "Rappy Model,ラッピー モデル,en_pe_rappy_f_mesh.ice",
            "Viola Animations,ヴィオラ モショーン,en_pe_sheep_e.ice",
            "Viola aqn,ヴィオラ aqn,en_pe_sheep_e01.ice",
            "Viola Model,ヴィオラ モデル,en_pe_sheep_e01_mesh.ice",
            "Viola aqn 2,ヴィオラ aqn 2,en_pe_sheep_e02.ice",
            "Viola Model 2,ヴィオラ モデル 2,en_pe_sheep_e02_mesh.ice",
            "Viola Effects,ヴィオラ エフェクト,en_pe_sheep_e_eff.ice",
            "Sally Animations,サリィ モショーン,en_pe_wiz_c.ice",
            "Sally aqn,サリィ aqn,en_pe_wiz_c01.ice",
            "Sally Model,サリィ モデル,en_pe_wiz_c01_mesh.ice",
            "Sally aqn 2,サリィ aqn 2,en_pe_wiz_c02.ice",
            "Sally Model 2,サリィ モデル 2,en_pe_wiz_c02_mesh.ice",
            "Sally Effects,サリィ エフェクト,en_pe_wiz_c_eff.ice",
            "Popple Animations,ポップル モショーン,en_pe_wiz_o.ice",
            "Popple aqn,ポップル aqn,en_pe_wiz_o01.ice",
            "Popple Model,ポップル モデル,en_pe_wiz_o01_mesh.ice",
            "Popple aqn 2,ポップル aqn 2,en_pe_wiz_o02.ice",
            "Popple Model 2,ポップル モデル 2,en_pe_wiz_o02_mesh.ice",
            "Popple Effects,ポップル エフェクト,en_pe_wiz_o_eff.ice",
        };

        public static List<string> classicBaseStats = new List<string>()
        {

            "Base Stats Enemies,レベル　ベース,en_level_base.ice",
            "Base Stats Masquerader (1-999),レベル　ベース マスカレーダ,en_level_base_masquerade.ice",
            "Base Stats Sodam (1-200),レベル　ベース ソダム,en_level_base_bodelfoots.ice.",
        };

        public static List<string> classicEnemyNames = new List<string>(){
            "Dephanasaur Shield Effect,デファンザウル　エフェクト,eff_en_ult_wdra_barrier.ice",
            "Debug Enemy Move Model (Gunkaiser),Debug ガンカイザー モデル,en_aaadebugenemymoveonly_a.ice",
            "Debug Enemy Move Animations (Gunkaiser),Debug ガンカイザー モーション,en_aaadebugenemymoveonly_common.ice",
            "Debug Enemy Move Up Down Model (Bareel),Debug バリール　モデル,en_aaadebugenemymoveupdown.ice",
            "Debug Enemy Move Up Down Animations (Bareel),Debug バリール　モーション,en_aaadebugenemymoveupdown_common.ice",
            "Debug Enemy Shoot Animations (Zombie),Debug ゾンビ モーション,en_aaadebugenemyshot_common.ice",
            "Debug Enemy Shoot Model (Gilnas),Debug ギルナス モデル,en_aaadebugenemyshot_l.ice",
            "Debug Enemy Shoot Animations (Gilnas),Debug ギルナス モーション,en_aaadebugenemyshot_l_common.ice",
            "Debug Enemy Shoot Model (Zombie),Debug ゾンビ モデル,en_aaadebugenemyshot_s.ice",
            "Dio Hyunal Model,ディーオ・ヒューナル モデル,en_abs_dp_human.ice",
            "Dio Hyunal Animations,ディーオ・ヒューナル モーション,en_abs_dp_human_common.ice",
            "Dio Hyunal Effect,ディーオ・ヒューナル エフェクト,en_abs_dp_human_eff.ice",
            "Veil Hyunal Model,ヴィエル・ヒューナル モデル,en_abs_dp_human_uniq.ice",
            "Falcabone,ファルカボネ,en_abyss_crab.ice",
            "Masquerader Model,エルガ・マスカレーダ モデル,en_akk.ice",
            "Masquerader Animations,マスカレーダ モーション,en_akk_common.ice",
            "Masquerader Effect,マスカレーダ エフェクト,en_akk_eff.ice",
            "Omega Masquerader Model 999,オメガ・マスカレーダ モデル 999,en_akk_l.ice",
            "Omega Masquerader Model,オメガ・マスカレーダ モデル,en_akk_m.ice",
            "Omega Masquerader Shadow Clone Model,オメガ・マスカレーダ 影 モデル,en_akk_msh.ice",
            "Masquerader Shadow Clone Model,マスカレーダ 影　モデル,en_akk_sh.ice",
            "Elga Masquerader Model,エルガ・マスカレーダ モデル,en_akk_u.ice",
            "Elga Masquerader Shadow Clone Model,エルガ・マスカレーダ 影　モデル,en_akk_ush.ice",
            "Zeshraider Model,ゼッシュレイダ モデル,en_alligator_snapper_a.ice",
            "Zeshraider Animations,ゼッシュレイダ モーション,en_alligator_snapper_common.ice",
            "Rigshraider Model,リグシュレイダ モデル,en_alligator_snapper_rare.ice",
            "Dagan Egg,ダガンエッグ,en_antegg.ice",
            "El Arda,エル・アーダ,en_ant_reaper.ice",
            "Buster Ram,バスターラム,en_arks_battering_ram.ice",
            "Garongo,ガロンゴ,en_armadillo_a.ice",
            "Castrum Demonica: Gasul Dhol Model,魔神城・ギャスルドール モデル,en_b1cats_a.ice",
            "Castrum Demonica: Lanzer Vales Model,魔神城・ランザーバレス モデル,en_b1cats_b.ice",
            "Castrum Demonica: Lanzer Vales Model 2,魔神城・ランザーバレス モデル 2,en_b1cats_bu.ice",
            "Castrum Demonica: Misil Gassdo Model,魔神城・ミシルガスード モデル,en_b1cats_c.ice",
            "Castrum Demonica Animations,魔神城 モーション,en_b1cats_common.ice",
            "Castrum Demonica: Misil Gassdo Model 2,魔神城・ミシルガスード モデル 2,en_b1cats_csp.ice",
            "Castrum Demonica: Misil Gassdo Effect,魔神城・ミシルガスード エフェクト,en_b1cats_c_eff.ice",
            "Castrum Demonica Effect,魔神城 エフェクト,en_b1cats_eff.ice",
            "Bomber Golem Model,ボンバゴーレム　モデル,en_b1gol_b.ice",
            "Golem Animations,ゴーレム モーション,en_b1gol_common.ice",
            "Golem Effect,ゴーレム エフェクト,en_b1gol_eff.ice",
            "Resta Golem Model,レスタゴーレム　モデル,en_b1gol_h.ice",
            "Rock Golem Model,ロックゴーレム　モデル,en_b1gol_n.ice",
            "Goblin Bomber Model,ゴブリンボンバ モデル,en_b1go_bo.ice",
            "Goblin Animations,ゴブリン モーション,en_b1go_common.ice",
            "Omega Goblin Model,オメガゴブリン モデル,en_b1go_sw.ice",
            "Minotaurgz Model,ミノタオルグス モデル,en_b1min.ice",
            "Minotaurgz Animations,ミノタオルグス モーション,en_b1min_common.ice",
            "Orc Bomber Model,オークボンバ モデル,en_b1or_bo.ice",
            "Orc Animations,オーク モーション,en_b1or_common.ice",
            "Omega Orc Model,オメガオーク モデル,en_b1or_n.ice",
            "Skull Archer Model,スカルアーチャー モデル,en_b1skar.ice",
            "Skull Soldier Model,スカルソルジャー モデル,en_b1sksw.ice",
            "Skull Animations,スカル モーション,en_b1sk_common.ice",
            "Omega Salamander Model,オメガサラマンダ モデル,en_b1slm.ice",
            "Omega Salamander Animations,オメガサラマンダ モショーン,en_b1slm_common.ice",
            "Omega Salamander Effects,オメガサラマンダ エフェクト,en_b1slm_eff.ice",
            "Wolf Animations,ウルフ モショーン,en_b1wo_common.ice",
            "Wolffoie Model,ウルフフォイエ モデル,en_b1wo_f.ice",
            "Omega Wolf Model,オメガウルフ モデル,en_b1wo_n.ice",
            "Sorceror (Omega) Animations,ソーサラー  (オメガ) モショーン,en_b1wra_common.ice",
            "Megid Sorcerer Model,メギドソーサラー モデル,en_b1wra_d.ice",
            "Sorceror (Omega) Effects,ソーサラー (オメガ) エフェクト,en_b1wra_eff.ice",
            "Foi Sorcerer Model,フォイソーサラー モデル,en_b1wra_f.ice",
            "Grants Sorcerer Model,グランソーサラー モデル,en_b1wra_l.ice",
            "Orc Cavalier Model,オークキャバリエ モデル,en_b1wrg.ice",
            "Orc Cavalier Animations,オークキャバリエ モショーン,en_b1wrg_common.ice",
            "Flame Diamos Model,フレイムディアモス モデル,en_b3blg.ice",
            "Flame Diamos Animations,フレイムディアモス モショーン,en_b3blg_common.ice",
            "Flame Diamos Effects,フレイムディアモス エフェクト,en_b3blg_eff.ice",
            "Castrum Demonica: Buster Vales Model,魔神城・バスターバレス モデル,en_b3cats_d.ice",
            "Castrum Demonica: Buster Vales Effects,魔神城・バスターバレス エフェクト,en_b3cats_d_eff.ice",
            "Velmuritta Model,ヴェルムリッター モデル,en_b3drl.ice",
            "Velmuritta Animations,ヴェルムリッター モショーン,en_b3drl_common.ice",
            "Omega Gryphon,オメガグリフォン,en_b3glf.ice",
            "Omega Cockatrice Model,オメガコカトリス モデル,en_b5coc.ice",
            "Omega Cockatrice Animations,オメガコカトリス モショーン,en_b5coc_common.ice",
            "Omega Cockatrice Effects,オメガコカトリス エフェクト,en_b5coc_eff.ice",
            "Omega Cockatrice Rock Effects,オメガコカトリス ロック　エフェクト,en_b5coc_peff.ice",
            "Omega Falz Luther Model,オメガファルス・ルーサー　モデル,en_bd1dp.ice",
            "Omega Falz Luther Animations,オメガファルス・ルーサー　モショーン,en_bd1dp_common.ice",
            "Omega Falz Luther Effects,オメガファルス・ルーサー　エフェクト,en_bd1dp_eff.ice",
            "Omega Falz Luther Rare Model (Same as normal),オメガファルス・ルーサー レア　モデル,en_bd1dp_rare.ice",
            "Bomber Valehda Model,ボンバヴァレーダ モデル,en_bd2bbb.ice",
            "Bomber Valehda Animations,ボンバヴァレーダ モショーン,en_bd2bbb_common.ice",
            "Omega Angel Model,オメガ・アンゲル モデル,en_bd2bhu.ice",
            "Omega Angel Motion 2,オメガ・アンゲル モショーン,en_bd2bhu_common.ice",
            "Omega Angel Effect,オメガ・アンゲル エフェクト,en_bd2bhu_eff.ice",
            "Omega Angel Model 2,オメガ・アンゲル モデル 2,en_bd2bhu_u.ice",
            "Tyraluda (Omega) Model,ティラルーダ (オメガ) モデル,en_bd2crw.ice",
            "Tyraluda (Omega) Animations,ティラルーダ (オメガ) モショーン,en_bd2crw_common.ice",
            "Bryu Ringahda (Omega) Model,ブリュー・リンガーダ (オメガ) モデル,en_bd2ctl.ice",
            "Bryu Ringahda (Omega) Animations,ブリュー・リンガーダ (オメガ) モショーン,en_bd2ctl_common.ice",
            "Dekor Maryuda (Omega) Model,デコル・マリューダ (オメガ) モデル,en_bd2drm.ice",
            "Dekor Maryuda (Omega) Animations,デコル・マリューダ (オメガ) モショーン,en_bd2drm_common.ice",
            "Lafaga Ringahda Model,ラファガ・リンガーダ モデル,en_bd3ctl.ice",
            "Lafaga Ringahda Animations,ラファガ・リンガーダ モショーン,en_bd3ctl_common.ice",
            "Udan,ウダン,en_beast_a.ice",
            "Za Udan,ザウーダン,en_beast_b.ice",
            "Za Udan Rock,ザウーダン ロック,en_beast_rock.ice",
            "Fal Vibras Model,ダーク・ビブラス モデル,en_beetle_a.ice",
            "Fal Vibras Yuga Model,ダーク・ビブラス・ユガ モデル,en_beetle_b.ice",
            "Fal Rinzes Yuga Model,ダーク・リンゼス・ユガ モデル,en_beetle_brare.ice",
            "Fal Vibras Animations,ダーク・ビブラス モショーン,en_beetle_common.ice",
            "Fal Rinzes Model,ダーク・リンゼス モデル,en_beetle_rare.ice",
            "Rockbear Animations,ロックベア モショーン,en_big_beast.ice",
            "Rockbear Model,ロックベア モデル,en_big_beast_a.ice",
            "Rogbelt Model,ログベルト モデル,en_big_beast_rare.ice",
            "Dingale Model,ディンゲール モデル,en_big_robot_a.ice",
            "Dingapolce Model,ディンガポルス モデル,en_big_robot_a_rare.ice",
            "Jagd Dingale Model,ヤクトディンゲール モデル,en_big_robot_b.ice",
            "Dinganoche Model,ディンガノーチェ モデル,en_big_robot_b_rare.ice",
            "Dingale Animations,ディンゲール モショーン,en_big_robot_common.ice",
            "Valehda Animations,ヴァレーダ モショーン,en_bird_bat.ice",
            "Lanz Valehda Model,ランズ・ヴァレーダ モデル,en_bird_bat_a.ice",
            "Vada Ransune Model,ヴァダ・ランズーネ モデル,en_bird_bat_ar.ice",
            "Shutrahda Animations,シュトゥラーダ エフェクト,en_bird_birdcrow.ice",
            "Shutrahda Model,シュトゥラーダ モデル,en_bird_birdcrow_a.ice",
            "Bal Shutrahda Model,バル・シュトゥラーダ モデル,en_bird_birdcrow_ar.ice",
            "Tyraluda Model,ティラルーダ モデル,en_bird_birdcrow_b.ice",
            "Ringahda Animations,リンガーダ モショーン,en_bird_centaur.ice",
            "Bryu Ringahda Model,ブリュー・リンガーダ モデル,en_bird_centaur_a.ice",
            "Nove Ringahdarl Model,ノーヴ・リンガダール モデル,en_bird_centaur_rare.ice",
            "Davrune Model,ダブリューネ モデル,en_bird_chicken_a.ice",
            "Bal Davrune Model,バル・ダブリューネ モデル,en_bird_chicken_ar.ice",
            "Davrunda Model,ダブリュンダ モデル,en_bird_chicken_b.ice",
            "Davrune Animations,ダブリューネ モショーン,en_bird_chicken_common.ice",
            "Druahda Model,ドリュアーダ モデル,en_bird_crest_a.ice",
            "Druahda Animations,ドリュアーダ モショーン,en_bird_crest_common.ice",
            "Dekor Maryuda Model,デコル・マリューダ モデル,en_bird_dharma_a.ice",
            "Dekor Maryuda Animations,デコル・マリューダ モショーン,en_bird_dharma_common.ice",
            "Nove Marydahl Model,ノーヴ・マリダール モデル,en_bird_dharma_rare.ice",
            "Luda Sorceror Model,リューダソーサラー モデル,en_bird_double_head.ice",
            "Luda Sorceror Animations,リューダソーサラー モショーン,en_bird_double_head_common.ice",
            "Falz Angel Model,ファルス・アンゲル モデル,en_bird_dp_human.ice",
            "Falz Angel Animations,ファルス・アンゲル モショーン,en_bird_dp_human_common.ice",
            "Falz Angel Model 2,ファルス・アンゲル モデル 2,en_bird_dp_human_uniq.ice",
            "Apos Dorios Model,アポス・ドリオス モデル,en_bird_owl_a.ice",
            "Apostol Torissha Model,アポストル・トリッツァー モデル,en_bird_owl_ar.ice",
            "Apos Dorios Animations,アポス・ドリオス モショーン,en_bird_owl_common.ice",
            "Apos Dorios Effects,アポス・ドリオス エフェクト,en_bird_owl_eff.ice",
            "Solda Capita Model,ソルダ・カピタ モデル,en_bird_soldier_a.ice",
            "Guru Solda Model,グル・ソルダ モデル,en_bird_soldier_b.ice",
            "Dwe Solda Model,ドゥエ・ソルダ モデル,en_bird_soldier_c.ice",
            "Solda Animations,ソルダ モショーン,en_bird_soldier_common.ice",
            "Gunnekazuchi Model,グンネカヅチ　モデル,en_bkb.ice",
            "Gunnekazuchi Animations,グンネカヅチ　モショーン,en_bkb_common.ice",
            "Gunnekazuchi Effects,グンネカヅチ　エフェクト,en_bkb_eff.ice",
            "Gommorus Primordial Darkness Model,【原初の闇】ゴモルス モデル,en_bodelbeast.ice",
            "Gommorus Primordial Darkness Animations,【原初の闇】ゴモルス モショーン,en_bodelbeast_common.ice",
            "Gommorus Primordial Darkness Animations 2,【原初の闇】ゴモルス モショーン 2,en_bodelbeast_depth2.ice",
            "Gommorus Primordial Darkness Effects,【原初の闇】ゴモルス エフェクト,en_bodelbeast_eff.ice",
            "Gommorus Primordial Darkness Model 2,【原初の闇】ゴモルス モデル 2,en_bodelbeast_u.ice",
            "Sodam Primordial Darkness Model,【原初の闇】ソダム モデル,en_bodelfoot.ice",
            "Sodam Primordial Darkness Animations,【原初の闇】ソダム モショーン,en_bodelfoot_common.ice",
            "Gommorus Primordial Darkness Animations 3,【原初の闇】ゴモルス モショーン 3,en_bodelfoot_common_god.ice",
            "Sodam Primordial Darkness Effects,【原初の闇】ソダム エフェクト,en_bodelfoot_eff.ice",
            "Sodam Primordial Darkness Model 2,【原初の闇】ソダム モデル 2,en_bodelfoot_u.ice",
            "Sodam Primordial Darkness Model (4 man),【原初の闇】ソダム モデル (4人),en_bodelfoot_s.ice",
            "Magatsu Choopga Model,マガツ・レタルガ モデル,en_bohvn.ice",
            "Magatsu Choopga Animations,マガツ・レタルガ モショーン,en_bohvn_common.ice",
            "Magatsu Choopga Effect,マガツ・レタルガ エフェクト,en_bohvn_eff.ice",
            "Big Varder Model,ビッグヴァーダー モデル,en_boss_mecha_a.ice",
            "Big Varder Animations,ビッグヴァーダー モショーン,en_boss_mecha_common.ice",
            "Kindid Model,キンディッド モデル,en_boss_mecha_mine.ice",
            "Kindid Animations,キンディッド　モデル,en_boss_mecha_mine_common.ice",
            "Wynvid Model,ウィンヴィッド モデル,en_boss_mecha_mine_rare.ice",
            "King Varder Model,キングヴァーダー モデル,en_boss_mecha_rare.ice",
            "Gilnach Core,ギルナッチ・コア,en_boss_mecha_repair.ice",
            "Damoth Model,ダモス モデル,en_bug_legion.ice",
            "Damoth Motion,ダモス モショーン,en_bug_legion_common.ice",
            "Tagamikazuchi Model,タガミカヅチ モデル,en_byakko_a.ice",
            "Tagamikazuchi Animations,タガミカヅチ モショーン,en_byakko_common.ice",
            "Izanekazuchi Model,イザネカヅチ モデル,en_byakko_g.ice",
            "Izanekazuchi Animations,イザネカヅチ モショーン,en_byakko_g_common.ice",
            "Izanekazuchi Effects,イザネカヅチ エフェクト,en_byakko_g_eff.ice",
            "Mother cml,マザー cml,en_c0_mt.ice",
            "Mother Animations,マザー モショーン,en_c0_mt_common.ice",
            "Mother Effects,マザー　エフェクト,en_c0_mt_eff.ice",
            "Apostle of Water Ophiel cml,水の使徒 オフィエル cml,en_c1_of.ice",
            "Apostle of Water Ophiel Animations,水の使徒 オフィエル モショーン,en_c1_of_common.ice",
            "Sir Adam Sacrid cml,サー・アーデム・S cml,en_c2_ar.ice",
            "Sir Adam Sacrid Animations,サー・アーデム・S モショーン,en_c2_ar_common.ice",
            "Sir Adam Sacrid Effects,サー・アーデム・S エフェクト,en_c2_ar_eff.ice",
            "Sir Adam Sacrid Weapon,サー・アーデム・S エフェクト 武器,en_c2_ar_wpn.ice",
            "Phaleg 2 cml,ファレグ cml,en_c3_f.ice",
            "Phaleg 2 Animations,ファレグ モショーン,en_c3_f_common.ice",
            "Phaleg 2 Effects,ファレグ エフェクト,en_c3_f_eff.ice",
            "SORO cml,SORO cml,en_c4_s.ice",
            "Elmir cml,エルミル cml,en_c5_p.ice",
            "Elmir Animations,エルミル モショーン,en_c5_p_common.ice",
            "Varuna (Ep6) cml,ヴァルナ (ep6) cml,en_c6_v.ice",
            "Varuna (Ep6) Animations,ヴァルナ (ep6) モショーン,en_c6_v_common.ice",
            "Shiva (Mitra) cml,シバ（ミトラ） cml,en_c7_sh.ice",
            "Shiva (Mitra) Animations,シバ（ミトラ） モショーン,en_c7_sh_common.ice",
            "Shiva (Mitra) Effects,シバ（ミトラ） エフェクト,en_c7_sh_eff.ice",
            "Shiva Goddess of Demise Animations,【終の女神】シバ モショーン,en_c9_common.ice",
            "Shiva Goddess of Demise cml,【終の女神】シバ cml,en_c9_sv.ice",
            "Shiva Goddess of Demise Effects,【終の女神】シバ エフェクト,en_c9_sv_eff.ice",
            "Guardine Model,ガーディン モデル,en_canadin_a.ice",
            "Guardinan Model,ガーディナン モデル,en_canadin_b.ice",
            "Guardine Animations,ガーディン モショーン,en_canadin_common.ice",
            "Guardinan Custom Model,カストガーディナン モデル,en_canadin_ctm_a.ice",
            "Guardinan Custom Animations,カストガーディナン モショーン,en_canadin_ctm_common.ice",
            "Signogun,シグノガン,en_cannon_robot_a.ice",
            "Persona the Masked (Sword) cml,【仮面】 (ソード) cml,en_char01_maskman.ice",
            "Persona the Masked Animations,【仮面】 モショーン,en_char01_maskman_common.ice",
            "Persona the Masked (Double Saber) cml,【仮面】 (ダブルセイバー) cml,en_char01_maskman_ds.ice",
            "Persona the Masked (Double Saber) cml　2,【仮面】 (ダブルセイバー) cml 2,en_char01_maskman_dsex.ice",
            "Persona the Masked (Sword) cml 2,【仮面】 (ソード) cml 2,en_char01_maskman_ex.ice",
            "Oza,オーザ,en_char06_o.ice",
            "Marlu,マールー,en_char07_m.ice",
            "Risa,リサ,en_char08_r.ice",
            "Fourie,フーリエ,en_char09_f.ice",
            "Casra (Gunslash),カスラ (ガンスラッシュ),en_char10_k_gs.ice",
            "Casra (Talis),カスラ (タリス),en_char10_k_th.ice",
            "Arks Abyss FM,アークス・アビス (FM),en_char12_zfo1.ice",
            "Arks Abyss FF,アークス・アビス (FF),en_char12_zfo2.ice",
            "Arks Abyss F Animations,アークス・アビス (F) モショーン,en_char12_zfo_common.ice",
            "Arks Abyss HM,アークス・アビス (HM),en_char12_zhu1.ice",
            "Arks Abyss HF,アークス・アビス (HF),en_char12_zhu2.ice",
            "Arks Abyss H Animations,アークス・アビス (H) モショーン,en_char12_zhu_common.ice",
            "Arks Abyss RM,アークス・アビス (RM),en_char12_zra1.ice",
            "Arks Abyss RF,アークス・アビス (RF),en_char12_zra2.ice",
            "Theodore (Ep2) cml,テオドール (Ep2) cml,en_char14_t.ice",
            "Theodore (Ep2) Effect,テオドール (Ep2) エフェクト,en_char14_t_eff.ice",
            "Theodore (Ep2) Sword,テオドール (Ep2) ソード,en_char14_t_wpn1.ice",
            "Theodore (Ep2) Partizan,テオドール (Ep2) パルチザン,en_char14_t_wpn2.ice",
            "Theodore (Ep2) Wand,テオドール (Ep2) ウォンド,en_char14_t_wpn3.ice",
            "Matoi Viel,マトイ・ヴィエル,en_char17_ma_a.ice",
            "Matoi Viel Animations cml,マトイ・ヴィエル モショーン cml,en_char17_ma_common.ice",
            "Matoi Viel Effects,マトイ・ヴィエル エフェクト,en_char17_ma_eff.ice",
            "Matoi Viel 2,マトイ・ヴィエル 2,en_char17_ma_uniq.ice",
            "Matoi Viel Rod,マトイ・ヴィエル ロッド,en_char17_ma_wpn_rod.ice",
            "Matoi Viel Wand,マトイ・ヴィエル　ウォンド,en_char17_ma_wpn_wand.ice",
            "Hagito Femt cml,ハギト・フェムト cml,en_char18_hg.ice",
            "Hagito Femt Animations,ハギト・フェムト モショーン,en_char18_hg_common.ice",
            "Hagito Femt Effects,ハギト・フェムト エフェクト,en_char18_hg_eff.ice",
            "Bethor cml,ベトール cml,en_char19_bt_a.ice",
            "Bethor camera,ベトール カメラ,en_char19_bt_camera.ice",
            "Bethor Animations,ベトール モショーン,en_char19_bt_common.ice",
            "Bethor Effects,ベトール エフェクト,en_char19_bt_eff.ice",
            "Bethor Fan,ベトール ファン,en_char19_bt_fan.ice",
            "Bethor Clapboard,ベトール Clapboard,en_char19_bt_wpn.ice",
            "Bethor Megaphone,ベトール メガホン,en_char19_bt_wpn2.ice",
            "Phaleg cml,ファレグ cml,en_char20_flg.ice",
            "Phaleg Animations,ファレグ モショーン,en_char20_flg_common.ice",
            "Phaleg Effects,ファレグ エフェクト,en_char20_flg_eff.ice",
            "Och cml,日の使徒 オークゥ cml,en_char21_oc.ice",
            "Och Animations,日の使徒 オークゥ モショーン,en_char21_oc_common.ice",
            "Och Effects,日の使徒 オークゥ エフェクト,en_char21_oc_eff.ice",
            "Och Weapon,日の使徒 オークゥ 武器,en_char21_oc_wpn.ice",
            "Phul Animations,月の使徒 フル モショーン,en_char22_common.ice",
            "Phul cml,月の使徒 フル cml,en_char22_fl.ice",
            "Phul Effects,月の使徒 フル エフェクト,en_char22_fl_eff.ice",
            "Phul Effects,月の使徒 フル 武器,en_char22_fl_wpn.ice",
            "Kohri Washinomiya cml,鷲宮コオリ cml,en_char23_kr.ice",
            "Kohri Washinomiya Animations,鷲宮コオリ モショーン,en_char23_kr_common.ice",
            "Kohri Washinomiya Effects,鷲宮コオリ エフェクト,en_char23_kr_eff.ice",
            "Gettemhult,ゲッテムハルト,en_chr02_gettem.ice",
            "Gettemhult 2,ゲッテムハルト 2,en_chr02_gettem_ex.ice",
            "Huey,ヒューイ,en_chr03_huey.ice",
            "Claris Krays,クラリスクレイス,en_chr04_kk.ice",
            "Claris Krays 2,クラリスクレイス 2,en_chr04_kk2.ice",
            "Claris Krays 3,クラリスクレイス 3,en_chr04_kkcl.ice",
            "Claris Krays Animations,クラリスクレイス モショーン,en_chr04_kk_common.ice",
            "Regius,レギアス,en_chr12_regias.ice",
            "Luther,ルーサー,en_chr13_looser.ice",
            "Apprentice (Margareta),【若人】 (マルガレータ),en_chr15_aold.ice",
            "Apprentice (Margareta) 2,【若人】 (マルガレータ) 2,en_chr15_aoldex.ice",
            "Apprentice (Margareta) Animations,【若人】 (マルガレータ) モショーン,en_chr15_aold_common.ice",
            "Luther,ルーサー,en_chr16_lc.ice",
            "Luther Animations,ルーサー モショーン,en_chr16_lc_common.ice",
            "Cougar NX Model,クーガーNX モデル,en_clb01_bb_cougar_a.ice",
            "Cougar NX ACE Model,クーガーNX・ACE モデル,en_clb01_bb_cougar_a_rare.ice",
            "Cougar NX Animations,クーガーNX モショーン,en_clb01_bb_cougar_common.ice",
            "Krabahda,クラバーダ,en_crab.ice",
            "Barbarillipan Model,バルバリリーパ モデル,en_crazyriripa_a.ice",
            "Barbarillipan Animations,バルバリリーパ モショーン,en_crazyriripa_common.ice",
            "Nemesangele Model,ネメスアンジュール　モデル,en_cy1ace.ice",
            "Nemesangele Animations,ネメスアンジュール　モショーン,en_cy1ace_common.ice",
            "Nemesangele Effects,ネメスアンジュール　エフェクト,en_cy1ace_eff.ice",
            "Avaalnemesis Model,アヴァールネメシス　モデル,en_cy1ace_r.ice",
            "Avaalnemesis Effects,アヴァールネメシス　エフェクト,en_cy1ace_r_eff.ice",
            "Dimolduminus　Model,ディモールドゥミヌス モデル,en_cy1bos.ice",
            "Dimolduminus Animations,ディモールドゥミヌス モショーン,en_cy1bos_common.ice",
            "Dimolduminus Effects,ディモールドゥミヌス エフェクト,en_cy1bos_eff.ice",
            "Dizolsaber Model,ディゾルセイバー モデル,en_cy1cap.ice",
            "Dizolsaber Animations,ディゾルセイバー モショーン,en_cy1cap_common.ice",
            "Dizolsaber Effects,ディゾルセイバー エフェクト,en_cy1cap_eff.ice",
            "Saberdigul Model,セイバーディグル モデル,en_cy1cap_r.ice",
            "Bareel Model,バリール モデル,en_cy1dro.ice",
            "Bareel Animations,バリール モショーン,en_cy1dro_common.ice",
            "Bareel Effects,バリール エフェクト,en_cy1dro_eff.ice",
            "Orcahba Model,オルカーバ モデル,en_cy1gun.ice",
            "Orcahba Animations,オルカーバ モショーン,en_cy1gun_common.ice",
            "Orcahba Effects,オルカーバ エフェクト,en_cy1gun_eff.ice",
            "Radilugo Model,ラディルーゴ モデル,en_cy1knu.ice",
            "Radilugo Animations,ラディルーゴ モショーン,en_cy1knu_common.ice",
            "Radilugo Effects,ラディルーゴ エフェクト,en_cy1knu_eff.ice",
            "Habalsa Model,ハバルッサ モデル,en_cy1shi.ice",
            "Habalsa Animations,ハバルッサ モショーン,en_cy1shi_common.ice",
            "Habalsa Effects,ハバルッサ エフェクト,en_cy1shi_eff.ice",
            "Zorula Model,ゾルーラ モデル,en_cy1sol.ice",
            "Zorula Animations,ゾルーラ モショーン,en_cy1sol_common.ice",
            "Zorula Effects,ゾルーラ エフェクト,en_cy1sol_eff.ice",
            "Dralberouge Model,ドラルベルージュ モデル,en_cy1tan.ice",
            "Dralberouge Animations,ドラルベルージュ モショーン,en_cy1tan_common.ice",
            "Dralberouge Effects,ドラルベルージュ エフェクト,en_cy1tan_eff.ice",
            "Dralberouge Effects 2,ドラルベルージュ エフェクト 2,en_cy1tan_n_eff.ice",
            "Dralberoudi Model,ドラルグルーディ モデル,en_cy1tan_r.ice",
            "Dralberoudi Effects,ドラルグルーディ エフェクト,en_cy1tan_r_eff.ice",
            "Veldfodrus Model,ベールドフォードルス モデル,en_cy2jam.ice",
            "Veldfodrus Animations,ベールドフォードルス モショーン,en_cy2jam_common.ice",
            "Veldfodrus Effects,ベールドフォードルス エフェクト,en_cy2jam_eff.ice",
            "Hyudo Azure Model,ヒュードアズール モデル,en_cy2orc.ice",
            "Hyudo Azure Animations,ヒュードアズール モショーン,en_cy2orc_common.ice",
            "Hyudo Azure Effects,ヒュードアズール エフェクト,en_cy2orc_eff.ice",
            "El Scudo Model,エルスクード モデル,en_cy2wiz.ice",
            "El Scudo Animations,エルスクード モショーン,en_cy2wiz_common.ice",
            "El Scudo Effects,エルスクード エフェクト,en_cy2wiz_eff.ice",
            "Grave Exegul Model,グラーブエクゼクル モデル,en_cy3des.ice",
            "Grave Exegul Animations,グラーブエクゼクル モショーン,en_cy3des_common.ice",
            "Grave Exegul Effects,グラーブエクゼクル エフェクト,en_cy3des_eff_a.ice",
            "Grave Exegul Effects 2,グラーブエクゼクル エフェクト 2,en_cy3des_eff_common.ice",
            "Gildina Exegul Effects,ギルディナエクゼクル エフェクト,en_cy3des_eff_r.ice",
            "Gildina Exegul Model,ギルディナエクゼクル モデル,en_cy3des_g.ice",
            "Luminmech Effects,閃機種 エフェクト,en_cy_common_eff.ice",
            "Apostle Dragon Model,アポストロ・ドラゴン モデル,en_d1bds.ice",
            "Descant Drahl Model,デサント・ドラール モデル,en_d1bdsr.ice",
            "Apostle Dragon Animations,アポストロ・ドラゴン モショーン,en_d1bds_common.ice",
            "Apostle Dragon Effects,アポストロ・ドラゴン エフェクト,en_d1bds_eff.ice",
            "Evilion Dragon Model,エボリオン・ドラゴン モデル,en_d2dmag.ice",
            "Evilion Dragon Animations,エボリオン・ドラゴン モショーン,en_d2dmag_common.ice",
            "Evilion Dragon Effects,エボリオン・ドラゴン エフェクト,en_d2dmag_eff.ice",
            "Ignisimo Dragon Model,ドラゴン・イグニシモ モデル,en_d2gla.ice",
            "Ignisimo Dragon Animations,ドラゴン・イグニシモ モショーン,en_d2gla_common.ice",
            "Deus Esca Zefirot Model,デウスエスカ・ゼフィロス モデル,en_de.ice",
            "Deus Hyunas Model,デウス・ヒューナス モデル,en_dehm1.ice",
            "Deus Hyunas Model,デウス・ヒューナス モデル 2,en_dehm1u.ice",
            "Deus Anges Model,デウス・アンジェス モデル,en_dehm2.ice",
            "Deus Hyunas Animations,デウス・ヒューナス モショーン,en_dehm_common.ice",
            "Deus Hyunas Effects,デウス・ヒューナス エフェクト,en_dehm_eff.ice",
            "Deus Esca Zefirot Animations,デウスエスカ・ゼフィロス モショーン,en_de_common.ice",
            "Deus Esca Zefirot Effects,デウスエスカ・ゼフィロス エフェクト,en_de_eff.ice",
            "Deus Esca Gracia Model,デウスエスカ・グラーシア　モデル,en_de_rare.ice",
            "Odin Model,オーディン モデル,en_dk.ice",
            "Odin Animations,オーディン モショーン,en_dk_common.ice",
            "Odin Effects,オーディン エフェクト,en_dk_eff.ice",
            "Odin cml,オーディン cml,en_dk_f.ice",
            "Odin Effects 2,オーディン エフェクト 2,en_dk_peff.ice",
            "Gwanada Model,グワナーダ モデル,en_doodlebug.ice",
            "Gwanada Animations,グワナーダ モショーン,en_doodlebug_common.ice",
            "Gwanada Bit Model,グワナーダ・ビット モデル,en_doodlebug_needle.ice",
            "Gwanada Bit Animations,グワナーダ・ビット モショーン,en_doodlebug_needle_common.ice",
            "Gwanada Bit Nero Model,グワナーダ・ビット・ネロ モデル,en_doodlebug_needle_rare.ice",
            "Gwanada Nero Model,グワナーダ・ネロ モデル,en_doodlebug_rare.ice",
            "Esca Falz Mother Model,エスカファルス・マザー モデル,en_dpp1.ice",
            "Esca Falz Mother Animations,エスカファルス・マザー モショーン,en_dpp1_common.ice",
            "Esca Falz Mother Effects,エスカファルス・マザー エフェクト,en_dpp1_eff.ice",
            "Esca Falz Mother Model 2,エスカファルス・マザー モデル 2,en_dpp2.ice",
            "Esca Falz Mother Animations 2,エスカファルス・マザー モショーン 2,en_dpp2_common.ice",
            "Esca Falz Mother Effects 2,エスカファルス・マザー エフェクト 2,en_dpp2_eff.ice",
            "Esca Falz Mother Model 3,エスカファルス・マザー モデル 3,en_dpp2_u.ice",
            "Profound Darkness Model,【深遠なる闇】 モデル,en_dp_abyss.ice",
            "Profound Darkness Persona Core cml,【深遠なる闇】 【仮面】 コア cml,en_dp_abyss_c.ice",
            "Profound Darkness Persona cml,【深遠なる闇】 【仮面】 cml,en_dp_abyss_char.ice",
            "Profound Darkness Persona Cast Female Animations,【深遠なる闇】 【仮面】 キャストF モショーン,en_dp_abyss_char_caf.ice",
            "Profound Darkness Persona Cast Male Animations,【深遠なる闇】 【仮面】 キャストM モショーン,en_dp_abyss_char_cam.ice",
            "Profound Darkness Persona cml 2,【深遠なる闇】 【仮面】 cml 2,en_dp_abyss_char_ex.ice",
            "Profound Darkness Persona Human Animations,【深遠なる闇】 【仮面】 ヒューマン モショーン,en_dp_abyss_char_std.ice",
            "Profound Darkness Persona cml 3,【深遠なる闇】 【仮面】 cml 3,en_dp_abyss_char_u.ice",
            "Profound Darkness Persona Effects,【深遠なる闇】 【仮面】 エフェクト,en_dp_abyss_char_uniq.ice",
            "Profound Darkness Animations,【深遠なる闇】 モショーン,en_dp_abyss_common.ice",
            "Profound Darkness Effects,【深遠なる闇】 エフェクト,en_dp_abyss_eff.ice",
            "Profound Darkness Model 2,【深遠なる闇】 モデル 2,en_dp_abyss_ex.ice",
            "Profound Darkness Animations 2,【深遠なる闇】 モショーン 2,en_dp_abyss_ex_common.ice",
            "Profound Darkness Effects 2,【深遠なる闇】 エフェクト 2,en_dp_abyss_ex_eff.ice",
            "Profound Darkness Model 3,【深遠なる闇】 モデル 3,en_dp_abyss_u.ice",
            "Dark Falz Luther Model,ダークファルス・ルーサー モデル,en_dp_bird.ice",
            "Dark Falz Luther Animations,ダークファルス・ルーサー モショーン,en_dp_bird_common.ice",
            "Dark Falz Luther Effects,ダークファルス・ルーサー エフェクト,en_dp_bird_eff.ice",
            "Dark Falz Luther Model 2,ダークファルス・ルーサー モデル 2,en_dp_bird_ex.ice",
            "Dark Falz Luther Animations 2,ダークファルス・ルーサー モショーン 2,en_dp_bird_ex_common.ice",
            "Dark Falz Luther Effects 2,ダークファルス・ルーサー エフェクト 2,en_dp_bird_ex_eff.ice",
            "Dark Falz Luther EQ Gauge Fail Model,ダークファルス・ルーサー EQゲージの失敗 モデル ,en_dp_bird_fake.ice",
            "Dark Falz Elder Model,ダークファルス・エルダー モデル,en_dp_elder_a.ice",
            "Dark Falz Elder Model 2,ダークファルス・エルダー モデル 2,en_dp_elder_a_ex.ice",
            "Dark Falz Elder Animations,ダークファルス・エルダー モショーン,en_dp_elder_common.ice",
            "Dark Falz Elder Animations 2,ダークファルス・エルダー モショーン 2,en_dp_elder_common_ex.ice",
            "Dark Falz Elder Arm BG Model,ダークファルス・エルダー アーム BG モデル,en_dp_elder_far.ice",
            "Dark Falz Elder Arm BG Model 2,ダークファルス・エルダー アーム BG モデル 2,en_dp_elder_far_ex.ice",
            "Falz Arm Parameters,ファルス・アーム パラメータ,en_dp_hand.ice",
            "Falz Arm x1 Model,ファルス・アーム x1 モデル,en_dp_hand_a.ice",
            "Falz Arm x1 Model 2,ファルス・アーム x1 モデル 2,en_dp_hand_a_ex.ice",
            "Falz Arm x8 Model,ファルス・アーム x8 モデル,en_dp_hand_eight.ice",
            "Falz Arm x8 Model 2,ファルス・アーム x8 モデル 2,en_dp_hand_eight_ex.ice",
            "Falz Arm Parameters 2,ファルス・アーム パラメータ 2,en_dp_hand_ex.ice",
            "Falz Arm x4 Model,ファルス・アーム x4 モデル,en_dp_hand_four.ice",
            "Falz Arm x4 Model 2,ファルス・アーム x4 モデル 2,en_dp_hand_four_ex.ice",
            "Falz Arm x1 Model 3,ファルス・アーム x1 モデル 3,en_dp_hand_free.ice",
            "Falz Arm x8 Model 3,ファルス・アーム x8 モデル 3,en_dp_hand_hanabi.ice",
            "Falz Arm x8 Model 4,ファルス・アーム x8 モデル 4,en_dp_hand_hanabi_ex.ice",
            "Falz Arm x2 Model,ファルス・アーム x2 モデル,en_dp_hand_two.ice",
            "Falz Arm x2 Model 2,ファルス・アーム x2 モデル 2,en_dp_hand_two_ex.ice",
            "Falz Hyunal Model,ファルス・ヒューナル モデル,en_dp_human.ice",
            "Omega Hyunal Model,オメガ・ヒューナル モデル,en_dp_human_neo.ice",
            "Omega Hyunal Effects,オメガ・ヒューナル エフェクト,en_dp_human_neo_eff.ice",
            "Dark Falz Apprentice Zia Model,DFアプレンティス・ジア モデル,en_dp_insect.ice",
            "Dark Falz Apprentice Zia Animations,DFアプレンティス・ジア モショーン,en_dp_insect_common.ice",
            "Dark Falz Apprentice Zia Effects,DFアプレンティス・ジア エフェクト,en_dp_insect_eff.ice",
            "Dark Falz Gemini Model,ダークファルス・ダブル モデル,en_dp_toy.ice",
            "Dark Falz Gemini Animations,ダークファルス・ダブル モショーン,en_dp_toy_common.ice",
            "Dark Falz Gemini Effects,ダークファルス・ダブル エフェクト,en_dp_toy_eff.ice",
            "Dark Falz Gemini Model 2,ダークファルス・ダブル モデル 2,en_dp_toy_ex.ice",
            "Dark Falz Gemini Animations 2,ダークファルス・ダブル モショーン 2,en_dp_toy_ex_common.ice",
            "Dark Falz Gemini Effects 2,ダークファルス・ダブル エフェクト 2,en_dp_toy_ex_eff.ice",
            "Baridran,バリドラン,en_dragon_beast.ice",
            "Chrome Dragon Model,クローム・ドラゴン モデル,en_dragon_berserk_a.ice",
            "Haze Drahl Model,ヘイズ・ドラール モデル,en_dragon_berserk_a_rare.ice",
            "Chrome Dragon Animations,クローム・ドラゴン モショーン,en_dragon_berserk_common.ice",
            "Quartz Dragon Animations,クォーツ・ドラゴン モショーン,en_dragon_blizzard.ice",
            "Quartz Dragon Model,クォーツ・ドラゴン モデル,en_dragon_blizzard_a.ice",
            "Crys Drahl Model,クリス・ドラール モデル,en_dragon_blizzard_rare.ice",
            "Dirandahl Model,ディランダール モデル,en_dragon_chariot_a.ice",
            "Sol Dirandahl Model,ソル・ディランダール モデル,en_dragon_chariot_b.ice",
            "Dirandahl Animations,ディランダール モショーン,en_dragon_chariot_common.ice",
            "Deegahla Animations,ディガーラ モショーン,en_dragon_flyraptor.ice",
            "Deegahla Model,ディガーラ モデル,en_dragon_flyraptor_a.ice",
            "Sol Deegahla Model,ソル・ディガーラ モデル,en_dragon_flyraptor_b.ice",
            "Dragon X Animations,ドラゴン・エクス モショーン,en_dragon_gladiator.ice",
            "Dragon X Model,ドラゴン・エクス モデル,en_dragon_gladiator_a.ice",
            "Noire Drahl Model,ノワル・ドラール モデル,en_dragon_gladiator_ar.ice",
            "Dragon X Effects,ドラゴン・エクス エフェクト,en_dragon_gladiator_eff_common.ice",
            "Pendran Animations,ペンドラン モショーン,en_dragon_hammer.ice",
            "Pendran Model,ペンドラン モデル,en_dragon_hammer_a.ice",
            "Vol Dragon Model,ヴォル・ドラゴン モデル,en_dragon_magma.ice",
            "Vol Dragon Animations,ヴォル・ドラゴン モショーン,en_dragon_magma_common.ice",
            "Vol Dragon Effects,ヴォル・ドラゴン エフェクト,en_dragon_magma_eff_common.ice",
            "Burn Drahl Model,バーン・ドラール モデル,en_dragon_magma_rare.ice",
            "Deeg Model,ディッグ モデル,en_dragon_raptor.ice",
            "Deeg Animations,ディッグ モショーン,en_dragon_raptor_common.ice",
            "Deegnacht Model,ディグナッツ モデル,en_dragon_raptor_rare.ice",
            "Deenian Animations,ディーニアン モショーン,en_dragon_rizardman.ice",
            "Sil Deenian Model,シル・ディーニアン モデル,en_dragon_rizardman_a.ice",
            "Sol Deenian Model,ソル・ディニアン モデル,en_dragon_rizardman_b.ice",
            "Deenian Model,ディーニアン モデル,en_dragon_rizardman_c.ice",
            "Sil Sadeenian Model,シル・サディーニアン モデル,en_dragon_rizardman_sa.ice",
            "Sol Sadeenian Model,ソル・サディニアン モデル,en_dragon_rizardman_sb.ice",
            "Sadeenian Model,サディーニアン モデル,en_dragon_rizardman_sc.ice",
            "Ceto Sadeenian Model,セト・サディニアン モデル,en_dragon_rizardman_sd.ice",
            "Goron Zran Model,ゴロンゾラン モデル,en_dragon_summoner.ice",
            "Goron Zran Animations,ゴロンゾラン モショーン,en_dragon_summoner_common.ice",
            "Goron Zran Vol Dragon Model,ゴロンゾラン ヴォル・ドラゴン モデル,en_dragon_summoner_illusion.ice",
            "Goron Zran Vol Dragon Animations,ゴロンゾラン ヴォル・ドラゴン モショーン,en_dragon_summoner_illusion_common.ice",
            "Zoron Goraal Burn Drahl Model,ゾロン・ゴラール バーン・ドラール モデル,en_dragon_summoner_illusion_rare.ice",
            "Zoron Goraal Model,ゾロン・ゴラール モデル,en_dragon_summoner_rare.ice",
            "Ran/Ransa Animations,ラン/ランサ モショーン,en_dragon_wolf.ice",
            "Fodran Model,フォードラン モデル,en_dragon_wolf_a.ice",
            "Nordeeran Model,ノーディラン モデル,en_dragon_wolf_b.ice",
            "Fodransa Model,フォードランサ モデル,en_dragon_wolf_sa.ice",
            "Nordeeransa Model,ノーディランサ モデル,en_dragon_wolf_sb.ice",
            "Catredran Model,キャタドラン モデル,en_dragon_worm.ice",
            "Catredransa Model,キャタドランサ モデル,en_dragon_worm_b.ice",
            "Catredran Animations,キャタドラン モショーン,en_dragon_worm_common.ice",
            "Catre Drahl Model,カタドラール モデル,en_dragon_worm_rare.ice",
            "Wyndila Model,ウィンディラ モデル,en_dragon_wyvern.ice",
            "Enemy Status,エネミのステータス,en_enemy_status.ice",
            "Enemy Title,エネミのタイトル,en_enemy_title.ice",
            "Omega Hyunal Model 2,オメガ・ヒューナル モデル 2,en_fd1dhu.ice",
            "Omega Hyunal Animations 2,オメガ・ヒューナル モショーン 2,en_fd1dhu_common.ice",
            "Omega Hyunal Effects 2,オメガ・ヒューナル エフェクト 2,en_fd1dhu_eff.ice",
            "Wolguarda Model,ウォルガーダ モデル,en_fd1fbb.ice",
            "Wolguarda Animations,ウォルガーダ モショーン,en_fd1fbb_common.ice",
            "Bomber Dhargash Model,ボンバダガッシュ　モデル,en_fd1fsh.ice",
            "Bomber Dhargash Animations,ボンバダガッシュ　モショーン,en_fd1fsh_common.ice",
            "Gawonda Model,ガウォンダ モデル,en_fd1fs_a.ice",
            "Gawonda Animations,ガウォンダ モショーン,en_fd1fs_a_common.ice",
            "Guwonda Model,グウォンダ モデル,en_fd1fs_b.ice",
            "Guwonda Animations,グウォンダ モショーン,en_fd1fs_b_common.ice",
            "Cuchronahda Model,キュクロナーダ モデル,en_fd1me_a.ice",
            "Cychronahda Model,サイクロネーダ モデル,en_fd1me_b.ice",
            "Cuchronada/Cychronahda Animations,キュクナーダ/サイクロネーダ モショーン,en_fd1me_common.ice",
            "Gorshraider Model,ゴルシュレイダ モデル,en_fd2all.ice",
            "Gorshraider Animations,ゴルシュレイダ モショーン,en_fd2all_common.ice",
            "Gawonda,ガウォンダ,en_fishrock_a.ice",
            "Guwonda,グウォンダ,en_fishrock_b.ice",
            "Wolguarda Animations 2,ウォルガーダ モショーン 2,en_fish_big_beast.ice",
            "Wolguarda Model 2,ウォルガーダ モデル 2,en_fish_big_beast_a.ice",
            "Alonaguarda Model,アロナガーダ モデル,en_fish_big_beast_b.ice",
            "Dhargacha Model,ダガッチャ モデル,en_floatagefish_a.ice",
            "Dhargash Model,ダーガッシュ モデル,en_floatagefish_b.ice",
            "Dharga Animations,ダガッ モショーン,en_floatagefish_common.ice",
            "Dhargash Nero Model,ダーガッシュ・ネロ モデル,en_floatagefish_rare.ice",
            "Gal Gryphon Model,ガル・グリフォン モデル,en_galgriffon_a.ice",
            "Gal Gryphon Animations,ガル・グリフォン モショーン,en_galgriffon_common.ice",
            "Gal Gryphon Effects,ガル・グリフォン エフェクト,en_galgriffon_eff.ice",
            "Gryphon Gehls Model,グリフォン・ゲルス モデル,en_galgriffon_rare.ice",
            "Spardun A Model,スパルダンＡ モデル,en_gorma_a.ice",
            "Spargun Model,スパルガン　モデル,en_gorma_b.ice",
            "Sparzile Model,スパルザイル モデル,en_gorma_c.ice",
            "Spar Animations,スパル モショーン,en_gorma_common.ice",
            "Signo Beat Model,シグノビート モデル,en_hologram_robot_a.ice",
            "Signo Animations,シグノ モショーン,en_hologram_robot_common.ice",
            "Signo Blue Model,シグノブルー モデル,en_hologram_robot_rare.ice",
            "Broondarl Model,ブリュンダール モデル,en_hummingbird.ice",
            "Broondarl Animations,ブリュンダール モショーン,en_hummingbird_common.ice",
            "Bal Broondarl Model,バル・ブリュンダール モデル,en_hummingbird_rare.ice",
            "Omega Appregina Model,オメガ・アプレジナ モデル,en_id1ahu.ice",
            "Omega Appregina Animations,オメガ・アプレジナ モショーン,en_id1ahu_common.ice",
            "Omega Appregina Effects,オメガ・アプレジナ エフェクト,en_id1ahu_eff.ice",
            "Omega Appregina Model 2,オメガ・アプレジナ モデル 2,en_id1ahu_u.ice",
            "Briarda Model,ブリアーダ モデル,en_id1ant.ice",
            "Briarda Animations,ブリアーダ モショーン,en_id1ant_common.ice",
            "Omega Falz Apprentice Model,OF・アプレンティス モデル,en_id1apple.ice",
            "Omega Falz Apprentice Animations,OF・アプレンティス モショーン,en_id1apple_common.ice",
            "Omega Falz Apprentice Effects,OF・アプレンティス エフェクト,en_id1apple_eff.ice",
            "Omega Falz Apprentice Model 2,OF・アプレンティス モデル 2,en_id1apple_r.ice",
            "Damoth Model,ダモス モデル,en_id1bleg.ice",
            "Damoth Animations,ダモス モショーン,en_id1bleg_common.ice",
            "Goldrahda Model,ゴルドラーダ モデル,en_id1coc.ice",
            "Goldrahda Animations,ゴルドラーダ モショーン,en_id1coc_common.ice",
            "Predicahdr Model,プレディカーダ モデル,en_id1man.ice",
            "Predicahdr Animations,プレディカーダ モショーン,en_id1man_common.ice",
            "Dark Ragne Model,ダーク・ラグネ モデル,en_id1spa.ice",
            "Dark Ragne Animations,ダーク・ラグネ モショーン,en_id1spa_common.ice",
            "Dark Ragne Effects,ダーク・ラグネ エフェクト,en_id1spa_eff.ice",
            "Grana Gwanahda Bit Model,グラナグワナーダ・ビット モデル,en_id2don.ice",
            "Grana Gwanahda Bit Animations,グラナグワナーダ・ビット モショーン,en_id2don_common.ice",
            "Grana Gwanahda Model,グラナグワナーダ モデル,en_id2doo.ice",
            "Grana Gwanahda Animations,グラナグワナーダ モショーン,en_id2doo_common.ice",
            "Lilipan,リリーパ族,en_kobito_a.ice",
            "Elder Lilipan,リリーパ族 (長),en_kobito_b.ice",
            "Vardersoma Model,ヴァーダーソーマ モデル,en_little_mecha_a.ice",
            "Vardersoma Animations,ヴァーダーソーマ モショーン,en_little_mecha_common.ice",
            "Embryo Varder Model,エンブリオヴァーダー モデル,en_little_mecha_rare.ice",
            "Krahda,クラーダ,en_locust.ice",
            "Shutolmizer Model,シュトルムマイザー モデル,en_m1tra.ice",
            "Shutolmizer Animations,シュトルムマイザー モショーン,en_m1tra_common.ice",
            "Batragun Model,バトラガン モデル,en_machine_kick_a.ice",
            "Starkgun Model,シュタークガン モデル,en_machine_kick_b.ice",
            "Gun Animations, ガン Animations,en_machine_kick_common.ice",
            "Marmoth Animations,マルモス モショーン,en_mammoth.ice",
            "De Marmoth Model,デ・マルモス モデル,en_mammoth_a.ice",
            "Marmoth Model,マルモス モデル,en_mammoth_b.ice",
            "Dal Malri Model,ダル・マルリ モデル,en_mammoth_rare.ice",
            "Dicahdr Animations,ディカーダ モショーン,en_mantis_warrior.ice",
            "Predicahdr Model,プレディカーダ モデル,en_mantis_warrior_a.ice",
            "Dicahdr Model,ディカーダ モデル,en_mantis_warrior_b.ice",
            "Predicahdr Nero Model,プレディカーダ・ネロ モデル,en_mantis_warrior_rare.ice",
            "Balger Animations,バルガ モショーン,en_mecha_wolf.ice",
            "Vint Balger Model,ヴィントバルガー モデル,en_mecha_wolf_a.ice",
            "Ganon Balger Model,ガノンバルガー モデル,en_mecha_wolf_b.ice",
            "Jagd Balger Model,ヤクトバルガー モデル,en_mecha_wolf_c.ice",
            "Dark Falz Persona Animations,ダークファルス・ペルソナ モショーン,en_med_common.ice",
            "Dark Falz Persona Animations UH,ダークファルス・ペルソナ モショーン UH,en_med_common_uh.ice",
            "Dark Falz Persona Effects,ダークファルス・ペルソナ エフェクト,en_med_eff.ice",
            "Dark Falz Persona Effects 2,ダークファルス・ペルソナ エフェクト 2,en_med_eff_ex.ice",
            "Dark Falz Persona Effects 3,ダークファルス・ペルソナ エフェクト 3,en_med_eff_u.ice",
            "Dark Falz Persona Model,ダークファルス・ペルソナ モデル,en_med_n.ice",
            "Dark Falz Persona Model 2,ダークファルス・ペルソナ モデル 2,en_med_r.ice",
            "Dark Falz Persona Model 3,ダークファルス・ペルソナ モデル 3,en_med_u.ice",
            "Mikda Animations,ミクダ モショーン,en_mimic.ice",
            "Mikda Model,ミクダ モデル,en_mimic_a.ice",
            "Ahl Mikda Model,オル・ミクダ モデル,en_mimic_b.ice",
            "Mikda Model,ミクダ モデル,en_mimic_c.ice",
            "Kindidd Custom,カストキンディッド,en_mine_cstm.ice",
            "Cuchronahda Model 2,キュクロナーダ モデル 2,en_monoeye_a.ice",
            "Cychronahda Model 2,サイクロネーダ モデル 2,en_monoeye_b.ice",
            "Cuchronada/Cychronahda Animations 2,キュクナーダ/サイクロネーダ モショーン 2,en_monoeye_common.ice",
            "Pajigwan Model,パジゴワン モデル,en_mono_bigarm_a.ice",
            "Pajigwan Animations,パジゴワン モショーン,en_mono_bigarm_common.ice",
            "Pajigeeri Model,パジギッリ モデル,en_mono_eyefoot_a.ice",
            "Pajigeeri Animations,パジギッリ モショーン,en_mono_eyefoot_common.ice",
            "Maga Pajigeeri Model,マガ・パジギッリ モデル,en_mono_eyefoot_ge.ice",
            "Maga Pajigeeri Animations,マガ・パジギッリ モショーン,en_mono_eyefoot_ge_common.ice",
            "Magatsu Shigan Model,マガツ・シガン モデル,en_mono_greatevilex_1.ice",
            "Magatsu Higan Model,マガツ・ヒガン モデル,en_mono_greatevilex_2.ice",
            "Magatsu Sai Model,マガツ・サイ モデル,en_mono_greatevilex_3.ice",
            "Magatsu Animations,マガツ モショーン,en_mono_greatevilex_common.ice",
            "Magatsu Effects,マガツ エフェクト,en_mono_greatevilex_eff.ice",
            "Magatsu Model,マガツ モデル,en_mono_greatevil_a.ice",
            "Magatsu Animations 2,マガツ モショーン 2,en_mono_greatevil_common.ice",
            "Magatsu Effects 2,マガツ エフェクト 2,en_mono_greatevil_eff.ice",
            "Gwahl Jigmolde Model,グアル・ジグモルデ モデル,en_mono_keeper_a.ice",
            "Gwahl Jigmolde Animations,グアル・ジグモルデ モショーン,en_mono_keeper_common.ice",
            "Gwahl Jigmolde Effects,グアル・ジグモルデ エフェクト,en_mono_keeper_eff.ice",
            "Gwahl Jigmolde Effects 2,グアル・ジグモルデ エフェクト 2,en_mono_keeper_eff_common.ice",
            "Gwahl Jigmolde Player Effects,グアル・ジグモルデ プレイヤ エフェクト,en_mono_keeper_player_eff.ice",
            "Agata Jigmolinde Model,アガタ・ジグモリンデ モデル,en_mono_keeper_rare.ice",
            "Kodoniagari Model,コドニアガリ モデル,en_mono_lantern_a.ice",
            "Kodoniagari Animations,コドニアガリ モショーン,en_mono_lantern_common.ice",
            "Orogrel Model,オロオガル モデル,en_mono_oni_ax.ice",
            "Izaogal Model,イザオガル モデル,en_mono_oni_club.ice",
            "Gal Animations,ガル モショーン,en_mono_oni_common.ice",
            "Maga Izaogal Model,マガ・イザオガル モデル,en_mono_oni_ge_club.ice",
            "Maga Izaogal Animations,マガ・イザオガル モショーン,en_mono_oni_ge_common.ice",
            "Adaogal Model,アドオガル モデル,en_mono_oni_gun.ice",
            "Daybreaker Model,白の民 モデル,en_mono_oni_white.ice",
            "Daybreaker Model 2,白の民 モデル 2,en_mono_oni_white_b.ice",
            "Kotoshiro Model,コトシロ モデル,en_mono_oni_white_unique.ice",
            "Gam Animations,ガム モショーン,en_mono_ork_common.ice",
            "Gannagam Model,ガンナガム モデル,en_mono_ork_thunder.ice",
            "Gimungamuy Model,ギムナガムリ モデル,en_mono_ork_thunderrare.ice",
            "Rerangam Model,レランガム モデル,en_mono_ork_wind.ice",
            "Olnagamuy Model,オルナガムリ モデル,en_mono_ork_windrare.ice",
            "Anshizagri Model,アヌシザグリ モデル,en_mono_plate_a.ice",
            "Yomnazagri Model,ヨムナザグリ モデル,en_mono_plate_ar.ice",
            "Zagri Animations,ザグリ モショーン,en_mono_plate_common.ice",
            "Maga Anshizagri Model,マガ・アヌシザグリ モデル,en_mono_plate_ge.ice",
            "Maga Anshizagri Animations,マガ・アヌシザグリ,en_mono_plate_ge_common.ice",
            "Anjadeurili Model,アンジャドゥリリ モデル,en_mono_roller_a.ice",
            "Yogjadeurili Model,ヨグジャドゥリリ モデル,en_mono_roller_ar.ice",
            "Anjadeurili Animations,アンジャドゥリリ モショーン,en_mono_roller_common.ice",
            "Pajadeurin Model,パジャドゥリン モデル,en_mono_roller_ii.ice",
            "Itagizakri Model,イタギザクリ モデル,en_mono_sickle_a.ice",
            "Itagizakri Animations,イタギザクリ モショーン,en_mono_sickle_common.ice",
            "Gol Ogabar Model,ゴル・オガバーレ モデル,en_mono_skull_allrare.ice",
            "Ogakibar Animations,オガキバル モショーン,en_mono_skull_common.ice",
            "Ban Ogakibar Model,バン・オガキバル モデル,en_mono_skull_hummer.ice",
            "Bor Ogakibar Model,ボル・オガキバル モデル,en_mono_skull_pole.ice",
            "Gau Ogakibar Model,ガウ・オガキバル モデル,en_mono_skull_rifle.ice",
            "Gigur Gunnegam Model,ギグル・グンネガム モデル,en_mono_yoroi_a.ice",
            "Gigur Gunnegam Animations,ギグル・グンネガム モショーン,en_mono_yoroi_common.ice",
            "Gigur Gunnegam Effects,ギグル・グンネガム エフェクト,en_mono_yoroi_common_eff.ice",
            "Gigur Gunnegam Effects 2,ギグル・グンネガム エフェクト 2,en_mono_yoroi_eff_common.ice",
            "Gunne Ginnegam Model,グンネ・ギンナガム モデル,en_mono_yoroi_rare.ice",
            "Thunder Rockbear Model,サンダーロックベア モデル,en_n1d_be.ice",
            "Mint Rockbear Model,ミントロックベア モデル,en_n2abe.ice",
            "Vangabear Model,バンガーベア モデル,en_n3bbe.ice",
            "Vangabear Animations,バンガーベア モショーン,en_n3bbe_common.ice",
            "Blizzard Banser Model,ブリザードバンサー モデル,en_n3pan_a.ice",
            "Blizzard Banshee Model,ブリザードバンシー モデル,en_n3pan_b.ice",
            "Banser Animations,バンサー モショーン,en_n3pan_common.ice",
            "Rockbear Model 2,ロックベア モデル 2,en_n4bbe.ice",
            "Udan 2,ウダン 2,en_native_beast_t.ice",
            "Gratsi Meduna Model,グラツィ・メデューナ モデル,en_o1afl_a.ice",
            "Gratsi Meduna Animations,グラツィ・メデューナ モショーン,en_o1afl_common.ice",
            "Gratsi Meduna Effects,グラツィ・メデューナ エフェクト,en_o1afl_eff.ice",
            "Brigantbran Model,ブリガンテブラン モデル,en_o1orc.ice",
            "Brigantbran Animations,ブリガンテブラン モショーン,en_o1orc_common.ice",
            "Gazar Casadohra Model,ガザル・キャサドーラ モデル,en_o1sle.ice",
            "Gazar Casadohra Animations,ガザル・キャサドーラ モショーン,en_o1sle_common.ice",
            "Anfeduraad Model,アンフェドゥラード モデル,en_o1wan.ice",
            "Anfeduraad Animations,アンフェドゥラード モショーン,en_o1wan_common.ice",
            "Imperial Fiend Animations,撃魔人兵 モショーン,en_osol_common.ice",
            "Imperial Fiendmage cml,皇国魔人法兵 cml,en_osol_ro.ice",
            "Imperial Fiendmage Animations,皇国魔人法兵 モショーン,en_osol_ro_common.ice",
            "Imperial Fiendmage weapon,皇国魔人法兵 武器,en_osol_ro_wpn.ice",
            "Imperial Fiendlancer cml,皇国突撃魔人兵 cml,en_osol_sw.ice",
            "Imperial Fiendlancer weapon,皇国突撃魔人兵 武器,en_osol_wpn_sw.ice",
            "Thunder Bear Model,サンダーベア モデル,en_p1d_be.ice",
            "Mint Polar Bear Model,ミントポーラベア モデル,en_p2abe.ice",
            "The Sixth Angel Model,第6使徒 モデル,en_p3psm.ice",
            "The Sixth Angel Animations,第6使徒 モショーン,en_p3psm_common.ice",
            "The Sixth Angel Effects,第6使徒 エフェクト,en_p3psm_eff.ice",
            "Rixes Gidor Model,リーゼス・ギドール モデル,en_p4tra.ice",
            "Rixes Gidor Animations,リーゼス・ギドール モショーン,en_p4tra_common.ice",
            "Rixes Gidor Effects,リーゼス・ギドール エフェクト,en_p4tra_eff.ice",
            "Es Opsis Model,エス・オプシス モデル,en_pafly.ice",
            "Es Opsis Animations,エス・オプシス モショーン,en_pafly_common.ice",
            "Es Anges Model,エス・アンジェス モデル,en_paman.ice",
            "Es Anges Animations,エス・アンジェス モショーン,en_paman_common.ice",
            "Fang Banser Model,ファングバンサー　モデル,en_panther_a.ice",
            "Banser Ong Model,バンサ・オング　モデル,en_panther_a_rare.ice",
            "Fang Banshee Model,ファングバンシー モデル,en_panther_b.ice",
            "Banser Donna Model,バンサ・ドンナ モデル,en_panther_b_rare.ice",
            "Bansers Animations,バンサー モショーン,en_panther_common.ice",
            "Snow Banser Model,スノウバンサー　モデル,en_panther_snow_a.ice",
            "Banser Oran Model,バンサ・オラン　モデル,en_panther_snow_a_rare.ice",
            "Snow Banshee Model,スノウバンシー モデル,en_panther_snow_b.ice",
            "Banser Elna Model,バンサ・エレナ モデル,en_panther_snow_b_rare.ice",
            "Es Santrus Model,エス・サントルス モデル,en_pawpn.ice",
            "Es Santrus Animations,エス・サントルス モショーン,en_pawpn_common.ice",
            "Es Santrus Effects,エス・サントルス エフェクト,en_pawpn_eff.ice",
            "Phantasm Battleship Yamato Model,幻創戦艦・大和 モデル,en_phantomship_a.ice",
            "Phantasm Battleship Yamato Animations,幻創戦艦・大和 モショーン,en_phantomship_common.ice",
            "Phantasm Battleship Yamato Effects,幻創戦艦・大和 エフェクト,en_phantomship_eff.ice",
            "Phantasm Battleship Yamato Model 2,幻創戦艦・大和 モデル 2,en_phantomship_ex.ice",
            "Phantasm Battleship Yamato Animations 2,幻創戦艦・大和 モショーン 2,en_phantomship_ex_common.ice",
            "Phantasm Battleship Yamato Effects 2,幻創戦艦・大和 エフェクト 2,en_phantomship_ex_eff.ice",
            "T15 Tank Model,１５式戦車 モデル,en_phantomtank_a.ice",
            "T15 Tank Animations,１５式戦車 モショーン,en_phantomtank_common.ice",
            "Armored T15 Tank Model,アーマード１５式 モデル,en_phantomtank_rare.ice",
            "Brown Bear Model,ブラウンベア モデル,en_phantom_bear_a.ice",
            "Polar Bear Model,ポーラベア モデル,en_phantom_bear_b.ice",
            "Bear Animations,ベア モショーン,en_phantom_bear_common.ice",
            "Snakeheli Model,スネークヘリ モデル,en_phantom_heli.ice",
            "Snakeheli Animations,スネークヘリ モショーン,en_phantom_heli_common.ice",
            "Black Snake Model,ブラックスネーク モデル,en_phantom_heli_rare.ice",
            "Sword Zombie Model,ドスゾンビ モデル,en_phantom_man_assault.ice",
            "Zombie Model,ゾンビ モデル,en_phantom_man_common.ice",
            "Heat-Packing Zombie Model,チャカゾンビ モデル,en_phantom_man_gun.ice",
            "Hoodlum Zombie Model,グレンゾンビ モデル,en_phantom_man_sp.ice",
            "Vidrola,ヴィドルーダ,en_pillbug.ice",
            "Solza Brahda,ソルザ・ブラーダ,en_priest.ice",
            "Agnis,アギニス,en_pterosaur_a.ice",
            "Disciple of Saturn Aratron Model,アラトロン・フェムト モデル,en_ptm_alt.ice",
            "Disciple of Saturn Aratron Animations,アラトロン・フェムト モショーン,en_ptm_alt_common.ice",
            "Disciple of Saturn Aratron Model 2,アラトロン・フェムト モデル 2,en_ptm_alt_uniq.ice",
            "Lanka Valehs Model,ランカ・ヴァレース モデル,en_ptm_bird_bat.ice",
            "Lanka Valehs Animations,ランカ・ヴァレース モショーン,en_ptm_bird_bat_common.ice",
            "Valehs Lankaas Model,ヴァレス・ランカース モデル,en_ptm_bird_bat_rare.ice",
            "Dekor Maryuz Model,デコル・マリューズ モデル,en_ptm_bird_dharma.ice",
            "Dekor Maryuz Animations,デコル・マリューズ モショーン,en_ptm_bird_dharma_common.ice",
            "Skull Buffalo Model,スカルバファロー モデル,en_ptm_buffalo.ice",
            "Skull Buffalo Animations,スカルバファロー モショーン,en_ptm_buffalo_common.ice",
            "Buffalo Head Model,バファローヘッド モデル,en_ptm_buffalo_rare.ice",
            "Circus Carriage Model,サーカスキャリッジ モデル,en_ptm_caravan.ice",
            "Circus Carriage Animations,サーカスキャリッジ モショーン,en_ptm_caravan_common.ice",
            "Crow Phant Model,クロウファムト モデル,en_ptm_crow_a.ice",
            "Crow Phant Animations,クロウファムト モショーン,en_ptm_crow_common.ice",
            "Crow Phant Effects,クロウファムト エフェクト,en_ptm_crow_eff.ice",
            "Boxer Phant Model,ボクサーファムト モデル,en_ptm_dog.ice",
            "Boxer Phant Animations,ボクサーファムト モショーン,en_ptm_dog_common.ice",
            "Boxer Phant Effects,ボクサーファムト エフェクト,en_ptm_dog_eff.ice",
            "Gachas,ガッチャス,en_ptm_fish_float_b.ice",
            "Vegas Illusia Model,ベガス・イリュージア モデル,en_ptm_goddess_a.ice",
            "Vegas Illusia Animations,ベガス・イリュージア モショーン,en_ptm_goddess_common.ice",
            "Vegas Illusia Effects,ベガス・イリュージア エフェクト,en_ptm_goddess_eff.ice",
            "Nightmare Vegas Model,ナイトメア・ベガス モデル,en_ptm_goddess_rare.ice",
            "Vidrols,ヴィドルース,en_ptm_ins_armaj.ice",
            "Esmoth Model,エスモス モデル,en_ptm_ins_legion.ice",
            "Esmoth Animations,エスモス モショーン,en_ptm_ins_legion_common.ice",
            "Platidrahs Model,プラチドーラス モデル,en_ptm_ins_roach_a.ice",
            "Platidrahs Animations,プラチドーラス モショーン,en_ptm_ins_roach_common.ice",
            "Granidrahs Model,グラニドーラス モデル,en_ptm_ins_roach_rare.ice",
            "Dekor Maryuz Model,エスカ・ラグナス モデル,en_ptm_ins_spider.ice",
            "Dekor Maryuz Animations,エスカ・ラグナス モショーン,en_ptm_ins_spider_common.ice",
            "Dekor Maryuz Effects,エスカ・ラグナス エフェクト,en_ptm_ins_spider_eff.ice",
            "Laplace Model,ラプラスの悪魔 モデル,en_ptm_laplace_a.ice",
            "Laplace Animations,ラプラスの悪魔 モショーン,en_ptm_laplace_common.ice",
            "Maxwell Model,マクスウェルの悪魔 モデル,en_ptm_maxwell_a.ice",
            "Maxwell Animations,マクスウェルの悪魔 モショーン,en_ptm_maxwell_common.ice",
            "Juggler Clown,ジャグラーピエロ モデル,en_ptm_pierrot_a.ice",
            "Chainsaw Clown,チェーンソーピエロ モデル,en_ptm_pierrot_b.ice",
            "Clown Animations,ピエロ モショーン,en_ptm_pierrot_common.ice",
            "Rat Phant Model,ラットファムト モデル,en_ptm_rat_a.ice",
            "Rat Phant Animations,ラットファムト モショーン,en_ptm_rat_common.ice",
            "Rat Phant Effects,ラットファムト エフェクト,en_ptm_rat_eff.ice",
            "Mouse Phant Model,マウスファムト モデル,en_ptm_rat_rare.ice",
            "T-Rex Model,Ｔ・レックス モデル,en_ptm_rex_a.ice",
            "T-Rex Animations,Ｔ・レックス モショーン,en_ptm_rex_common.ice",
            "T-Rex Effects,Ｔ・レックス エフェクト,en_ptm_rex_eff.ice",
            "Rex Noire Model,レックスノワール モデル,en_ptm_rex_rare.ice",
            "Dullahan Biker Model,デュラハンライダー モデル,en_ptm_rider.ice",
            "Dullahan Biker Model,デュラハンライダー モデル,en_ptm_rider_common.ice",
            "Red Dullahan Biker Model,レッドデュライダー モデル,en_ptm_rider_rare.ice",
            "Road Roller Model,ロードローラー モデル,en_ptm_roller_a.ice",
            "Road Roller Animations,ロードローラー モショーン,en_ptm_roller_common.ice",
            "Red Roller Model,レッドローラー モデル,en_ptm_roller_rare.ice",
            "Sniper Neon Model,スナイパーネオン モデル,en_ptm_sniper_a.ice",
            "Launcher Neon Model,ランチャーネオン モデル,en_ptm_sniper_b.ice",
            "Neon Effects,ネオン エフェクト,en_ptm_sniper_common.ice",
            "Neon Animations,ネオン モショーン,en_ptm_sniper_eff.ice",
            "Bonta Beattas Model,ボンタ・ベアタス モデル,en_ptm_toy_bear_a.ice",
            "Bonta Beattas Animations,ボンタ・ベアタス モショーン,en_ptm_toy_bear_common.ice",
            "Pras Picohs Animations,パラス・ピコス モショーン,en_ptm_toy_box_common.ice",
            "Pras Picohs Model,パラス・ピコス モデル,en_ptm_toy_box_missile.ice",
            "Devil Truck Model,デビルズトレーラー モデル,en_ptm_track_a.ice",
            "Truck Animations,トレーラー モショーン,en_ptm_track_common.ice",
            "Murder Truck Model,マーダートレーラー モデル,en_ptm_track_rare.ice",
            "Train Gidran Model,トレイン・ギドラン モデル,en_ptm_train_a.ice",
            "Train Gidran Animations,トレイン・ギドラン モショーン,en_ptm_train_common.ice",
            "Train Gidran Effects,トレイン・ギドラン エフェクト,en_ptm_train_eff.ice",
            "Train Gidran Effects 2,トレイン・ギドラン エフェクト 2,en_ptm_train_eff_common.ice",
            "Doktor Gidoras Model,ドクトル・ギドラス モデル,en_ptm_train_rare.ice",
            "UFO Model,U.F.O モデル,en_ptm_ufo_a.ice",
            "UFO Animations,U.F.O モショーン,en_ptm_ufo_common.ice",
            "UFO Effects,U.F.O エフェクト,en_ptm_ufo_eff.ice",
            "Vulture Phant Model,バルチャファムト モデル,en_ptm_vulture.ice",
            "Vulture Phant Animations,バルチャファムト モショーン,en_ptm_vulture_common.ice",
            "Briarda,ブリアーダ,en_queenant.ice",
            "Nav Rappy Animations,ナヴ・ラッピー  モショーン,en_rag_rappy.ice",
            "Nav Rappy Model,ナヴ・ラッピー  モデル,en_rag_rappy_a.ice",
            "Rappy Model,ラッピー  モデル,en_rappy.ice",
            "Rappy Animations,ラッピー  モショーン,en_rappy_common.ice",
            "Drago Rappy,ドラグ・ラッピー モデル,en_rappy_dragon.ice",
            "Egg Rappy Model,エグ・ラッピー モデル,en_rappy_easter.ice",
            "Eleph Rappy,エレフ・ラッピー モデル,en_rappy_elephant.ice",
            "Emperappy Model,エンペ・ラッピー モデル,en_rappy_emp.ice",
            "Emperappy Effects,エンペ・ラッピー エフェクト,en_rappy_emp_eff.ice",
            "Lantern Rappy Model,ラタン・ラッピー モデル,en_rappy_helloween.ice",
            "Frog Rappy Model,フログ・ラッピー モデル,en_rappy_rainy.ice",
            "Santa Rappy Model,セント・ラッピー モデル,en_rappy_santa.ice",
            "Summer Rappy Model,サマー・ラッピー モデル,en_rappy_summer.ice",
            "Love Rappy Model,ラブ・ラッピー モデル,en_rappy_valentine.ice",
            "Lovey Rappy Model,ラヴィ・ラッピー モデル,en_rappy_whiteday.ice",
            "Elytron Dragon Model,エリュトロン・ドラゴン モデル,en_rd_a.ice",
            "Atolm Dragon Model,ドラゴン・アートルム モデル,en_rd_ar.ice",
            "Elytron Dragon Animations,エリュトロン・ドラゴン モショーン,en_rd_common.ice",
            "Elytron Dragon Effects,エリュトロン・ドラゴン エフェクト,en_rd_eff.ice",
            "Dark Emperappy Model,ダーク・エンペラッピー モデル,en_rebl.ice",
            "Dark Emperappy Effects,ダーク・エンペラッピー エフェクト,en_rebl_eff.ice",
            "Lantern Emperappy Model,ラタン・エンペラッピー モデル,en_rehw.ice",
            "Lantern Emperappy Effects,ラタン・エンペラッピー エフェクト,en_rehw_eff.ice",
            "Love Emperappy Model,ラブ・エンペラッピー モデル,en_revd.ice",
            "Love Emperappy Effects,ラブ・エンペラッピー エフェクト,en_revd_eff.ice",
            "Lovey Emperappy Model,ラヴィ・エンペラッピー モデル,en_rewd.ice",
            "Lovey Emperappy Effects,ラヴィ・エンペラッピー エフェクト,en_rewd_eff.ice",
            "Goldrahda Model,ゴルドラーダ モデル,en_roach_a.ice",
            "Goldrahda Animations,ゴルドラーダ モショーン,en_roach_common.ice",
            "Rinze Drahda Model,リンゼ・ドラーダ モデル,en_roach_rare.ice",
            "Arks Rappy Model,アクス・ラッピー モデル,en_rp2.ice",
            "Arks Rappy Animations,アクス・ラッピー モショーン,en_rp2_common.ice",
            "Turkey Rappy Model,タッキ・ラッピー モデル,en_rth.ice",
            "Gilnas,ギルナス,en_separation_mecha_a.ice",
            "Gilnas Core Model,ギルナス・コア　モデル,en_separation_mecha_a_core.ice",
            "Gilnas Core Animations,ギルナス・コア　モショーン,en_separation_mecha_a_core_common.ice",
            "Gilnas Legs,ギルナス レッグ,en_separation_mecha_a_lower.ice",
            "Gilnas Arms,ギルナス アーム,en_separation_mecha_a_upper.ice",
            "Gilnach,ギルナッチ,en_separation_mecha_b.ice",
            "Knight Gear Model,ナイトギア モデル,en_sfc_knightgear_a.ice",
            "Knight Gear Animations,ナイトギア モショーン,en_sfc_knightgear_common.ice",
            "Magi Knight Gear Model,魔導騎士ナイトギア モデル,en_sfc_knightgear_rare.ice",
            "Carthago,カルターゴ,en_snail.ice",
            "Dagan Animations,ダガン モショーン,en_soldierant.ice",
            "Dagan Model,ダガン モデル,en_soldierant_a.ice",
            "El Dagan Model,エル・ダガン モデル,en_soldierant_b.ice",
            "Dagan Nero Model,ダガン・ネロ モデル,en_soldierant_rare.ice",
            "Dark Ragne Model,ダーク・ラグネ モデル,en_spider.ice",
            "Dark Ragne Animations,ダーク・ラグネ モショーン,en_spider_common.ice",
            "Dark Agrahni Model,ダーク・アグラニ モデル,en_spider_rare.ice",
            "Viliga Zignind Model,ビリガ・ジグニンデ モデル,en_t1xcu.ice",
            "Viliga Zignind Animations,ビリガ・ジグニンデ モショーン,en_t1xcu_common.ice",
            "Viliga Zignind Effects,ビリガ・ジグニンデ エフェクト,en_t1xcu_eff.ice",
            "Broll Brengam Model,ブロル・ブレンガム モデル,en_t1yor.ice",
            "Broll Brengam Animations,ブロル・ブレンガム モショーン,en_t1yor_common.ice",
            "Broll Brengam Effects,ブロル・ブレンガム エフェクト,en_t1yor_eff.ice",
            "Kodotta Idihta Model,コドッタ・イーデッタ モデル,en_td1blo.ice",
            "Kodotta Idihta Animations,コドッタ・イーデッタ モショーン,en_td1blo_common.ice",
            "Kodotta Idihta Effects,コドッタ・イーデッタ エフェクト,en_td1blo_eff.ice",
            "Bonta Beadda Model,ボンタ・ベアッダ モデル,en_td1crr.ice",
            "Bonta Beadda Animations,ボンタ・ベアッダ モショーン,en_td1crr_common.ice",
            "Orota Bikehta Model,オロタ・ビケッタ モデル,en_td1hou.ice",
            "Orota Bikehta Animations,オロタ・ビケッタ モショーン,en_td1hou_common.ice",
            "Murder Toykatta Model,マーダ・トカッタ モデル,en_td1pip.ice",
            "Murder Toykatta Animations,マーダ・トカッタ モショーン,en_td1pip_common.ice",
            "Omega Dranble Animations,オメガ・ダランブル モショーン,en_td1thu_common.ice",
            "Omega Dranble Effects,オメガ・ダランブル エフェクト,en_td1thu_eff.ice",
            "Omega Dranble Model,オメガ・ダランブル モデル,en_td1thu_fu.ice",
            "Omega Dranble Model 2,オメガ・ダランブル モデル 2,en_td1thu_w.ice",
            "Dranble Krone Model,ダランブル・クローネ モデル,en_td1thu_wc.ice",
            "Omega Dranble Model 3,オメガ・ダランブル モデル 3,en_td1thu_wu.ice",
            "Oduna Zordata Model,オドゥナ・ゾルダッタ モデル,en_td2blo.ice",
            "Oduna Zordata Animations,オドゥナ・ゾルダッタ モショーン,en_td2blo_common.ice",
            "Oduna Zordata Effects,オドゥナ・ゾルダッタ エフェクト,en_td2blo_eff.ice",
            "Kodotta Idihta Model 2,コドッタ・イーデッタ モデル 2,en_toy_block_a.ice",
            "Baretta Idihta Model,バレッタ・イーデッタ モデル,en_toy_block_a_rare.ice",
            "Kodotta Idihta Animations 2,コドッタ・イーデッタ モショーン 2,en_toy_block_common.ice",
            "Kodotta Idihta Effects 2,コドッタ・イーデッタ エフェクト 2,en_toy_block_eff.ice",
            "Kodotta Idihta Effects 3,コドッタ・イーデッタ エフェクト 3,en_toy_block_eff_common.ice",
            "Pitta Wadda Model,ピッタ・ワッダ モデル,en_toy_box_bite.ice",
            "Pitta Wadda Animations,ピッタ・ワッダ モショーン,en_toy_box_common.ice",
            "Prata Picohda Model,パラタ・ピコーダ モデル,en_toy_box_missile.ice",
            "Bomta Bakuta Model,ボンタ・バクタ モデル,en_toy_box_nitro.ice",
            "Bonta Beadda Model 2,ボンタ・ベアッダ モデル 2,en_toy_crazybear_a.ice",
            "Bichda Rabitta Model,ビクダ・ラビッタ モデル,en_toy_crazybear_b.ice",
            "Bonta Beadda Animations 2,ボンタ・ベアッダ モショーン 2,en_toy_crazybear_common.ice",
            "Orota Bikehta Model,オロタ・ビケッタ モデル,en_toy_dollhouse_a.ice",
            "Rota Birokehta Model,ロタ・ビロケッタ モデル,en_toy_dollhouse_ar.ice",
            "Orota Bikehta Animations 2,オロタ・ビケッタ モショーン 2,en_toy_dollhouse_common.ice",
            "Falz Dranble Animations,ファルス・ダランブル モショーン,en_toy_dp_human_common.ice",
            "Falz Dranble Effects,ファルス・ダランブル エフェクト,en_toy_dp_human_eff.ice",
            "Falz Daril Model,ファルス・ダリル モデル,en_toy_dp_human_f.ice",
            "Falz Daril Model 2,ファルス・ダリル モデル 2,en_toy_dp_human_funiq.ice",
            "Falz Dranble Model,ファルス・ダラン モデル,en_toy_dp_human_m.ice",
            "Falz Dranble Model 2,ファルス・ダラン モデル 2,en_toy_dp_human_muniq.ice",
            "Murder Toykatta Model 2,マーダ・トカッタ モデル 2,en_toy_pipe_a.ice",
            "Murder Toykatta Animations 2,マーダ・トカッタ モショーン 2,en_toy_pipe_common.ice",
            "Tranmizer Animations,トランマイザー モショーン,en_transform_mecha.ice",
            "Tranmizer Model,トランマイザー モデル,en_transform_mecha_a.ice",
            "Tranmizer Effects,トランマイザー エフェクト,en_transform_mecha_eff_common.ice",
            "Tranzexia Model,トランゼクシア モデル,en_transform_mecha_rare.ice",
            "Deos Gryphon Model,デオス・グリフォン モデル,en_u1gg.ice",
            "Deos Gryphon Animations,デオス・グリフォン モショーン,en_u1gg_common.ice",
            "Deos Gryphon Effects,デオス・グリフォン エフェクト,en_u1gg_eff.ice",
            "Grandilga Model,グランディルガ モデル,en_ult_armadillo_a.ice",
            "Grandilga Animations,グランディルガ モショーン,en_ult_armadillo_common.ice",
            "Bearabos Model,ベーアリブルス モデル,en_ult_big_beast_a.ice",
            "Bearabos Animations,ベーアリブルス モショーン,en_ult_big_beast_common.ice",
            "Bergaribosa Model,ベルガリブルーサ モデル,en_ult_big_beast_rare.ice",
            "Bladingale Model,ブレードディンゲール モデル,en_ult_big_robot_a.ice",
            "Dingabruise Model,Dingabruise モデル,en_ult_big_robot_ar.ice",
            "Bladingale Animations,ブレードディンゲール モショーン,en_ult_big_robot_common.ice",
            "Yggda Sorcerer Model,ユグダソーサラー モデル,en_ult_bird_double_head.ice",
            "Yggda Sorcerer Animations,ユグダソーサラー モショーン,en_ult_bird_double_head_common.ice",
            "Gunkaiser Model,ガンカイザー モデル,en_ult_cannon_robot_a.ice",
            "Gunkaiser Animations,ガンカイザー モショーン,en_ult_cannon_robot_common.ice",
            "Gryzorus Drago Model,グリュゾラス・ドラゴ モデル,en_ult_dragon_blizzard_a.ice",
            "Gryzorus Drago Animations,グリュゾラス・ドラゴ モショーン,en_ult_dragon_blizzard_common.ice",
            "Nilbareez Drago Model,ニルバリーズ・ドラゴ モデル,en_ult_dragon_blizzard_rare.ice",
            "Z Schwarzus Animations,ゾ・シュバルザス モショーン,en_ult_dragon_chariot_common.ice",
            "Z Schwarzus Model,ゾ・シュバルザス モデル,en_ult_dragon_chariot_rearguard.ice",
            "Valgahla Model,ヴァルガーラ モデル,en_ult_dragon_flyraptor_a.ice",
            "Grobgahla Model,グロブガーラ モデル,en_ult_dragon_flyraptor_ar.ice",
            "Valgahla Animations,ヴァルガーラ モショーン,en_ult_dragon_flyraptor_common.ice",
            "Drago Deadlion Model,ドラゴ・デッドリオン モデル,en_ult_dragon_gladiator_a.ice",
            "Valeon Drahl Model,ヴァレオン・ドラール モデル,en_ult_dragon_gladiator_ar.ice",
            "Drago Deadlion Animations,ドラゴ・デッドリオン モショーン,en_ult_dragon_gladiator_common.ice",
            "Grudran Model,グルドラン モデル,en_ult_dragon_hammer_a.ice",
            "Grudran Animations,グルドラン モショーン,en_ult_dragon_hammer_common.ice",
            "Grudran Effects,グルドラン エフェクト,en_ult_dragon_hammer_eff.ice",
            "Diaboigryphis Model,ディアボイグリシス モデル,en_ult_dragon_magma_a.ice",
            "Diaboigryphis Animations,ディアボイグリシス モショーン,en_ult_dragon_magma_common.ice",
            "Vomosbrodyphis Model,ヴォモスブロドシス モデル,en_ult_dragon_magma_rare.ice",
            "G Chevalizan Model,ジ・シュバリザン モデル,en_ult_dragon_rizardman_a.ice",
            "Z Chevalizan Model,ゾ・シュバリザン モデル,en_ult_dragon_rizardman_b.ice",
            "Chevalizan Model,シュバリザン モデル,en_ult_dragon_rizardman_c.ice",
            "Chevalizan Animations,シュバリザン モショーン,en_ult_dragon_rizardman_common.ice",
            "Ventasaur Model,ヴェンタザウル モデル,en_ult_dragon_wolf_a.ice",
            "Dephansaur Model,デファンザウル モデル,en_ult_dragon_wolf_b.ice",
            "Saur Animations,ザウル モショーン,en_ult_dragon_wolf_common.ice",
            "Boks Deubarz Model,ボクス・ドゥバルス モデル,en_ult_dra_tran_a.ice",
            "Bugihl Deubarz Model,ブギル・ドゥバルス モデル,en_ult_dra_tran_ar.ice",
            "Boks Deubarz Animations,ボクス・ドゥバルス モショーン,en_ult_dra_tran_common.ice",
            "Boks Deubarz Effects,ボクス・ドゥバルス エフェクト,en_ult_dra_tran_eff.ice",
            "Wonda Yuga Animations,ウォンダ・ユガ モショーン,en_ult_fish_shield_common.ice",
            "Guwonda Yuga Model,グウォンダ・ユガ モデル,en_ult_fish_shield_l.ice",
            "Guwonda Yuga Animations,グウォンダ・ユガ モショーン,en_ult_fish_shield_l_common.ice",
            "Gawonda Yuga Model,ガウォンダ・ユガ モデル,en_ult_fish_shield_r.ice",
            "Gawonda Yuga Animations,ガウォンダ・ユガ モショーン,en_ult_fish_shield_r_common.ice",
            "Jagdspardan Model,ヤクトスパルダン モデル,en_ult_gorma_a.ice",
            "Jagdspardan Animations,ヤクトスパルダン モショーン,en_ult_gorma_common.ice",
            "Sinow Rapidus Model,シノワラピドゥス モデル,en_ult_hologram_robot_a.ice",
            "Sinow Rosso Model,シノワロッゾ モデル,en_ult_hologram_robot_ar.ice",
            "Sinow Rapidus Animations,シノワラピドゥス モショーン,en_ult_hologram_robot_common.ice",
            "Plosiogrs Model,プロジオーグルス モデル,en_ult_mammoth_a.ice",
            "Ignisiogrs Model,イグニジオグルス モデル,en_ult_mammoth_a_rare.ice",
            "Jahmagrs Model,ジャーマグルス モデル,en_ult_mammoth_b.ice",
            "Grs Animations,グルス モショーン,en_ult_mammoth_common.ice",
            "Yugadicahdr Model,ユーガディカーダ モデル,en_ult_mantis_warrior_a.ice",
            "Nelgadicahdr Model,ネルガディカーダ モデル,en_ult_mantis_warrior_ar.ice",
            "Dicahdr Animations,ディカーダ モショーン,en_ult_mantis_warrior_common.ice",
            "Zeta Granz Model,ゼータ・グランゾ モデル,en_ult_mecha_noarm_a.ice",
            "Epsilon Granz Model,イプシロン・グランゾ モデル,en_ult_mecha_noarm_ar.ice",
            "Zeta Granz Animations,ゼータ・グランゾ モショーン,en_ult_mecha_noarm_common.ice",
            "Zeta Granz Effects,ゼータ・グランゾ エフェクト,en_ult_mecha_noarm_eff.ice",
            "Falke Leone Model,ファルケ・レオーネ モデル,en_ult_mecha_panth_blade.ice",
            "Leone Farozzo Model,レオーネ・ファロッゾ モデル,en_ult_mecha_panth_bladerare.ice",
            "Varima Leopod Model,ヴリマ・レオパード モデル,en_ult_mecha_panth_buster.ice",
            "Leone Vrozzo Model,レオパード・ヴロッゾ モデル,en_ult_mecha_panth_busterrare.ice",
            "Leone Animations,レオーネ モショーン,en_ult_mecha_panth_common.ice",
            "Leone Effects,レオーネ エフェクト,en_ult_mecha_panth_common_eff.ice",
            "Kaizer Balger Model,カイザーバルガー モデル,en_ult_mecha_wolf_a.ice",
            "Kaizer Balger Animations,カイザーバルガー モショーン,en_ult_mecha_wolf_common.ice",
            "Cuchronahda Yuga Model,キュクロナーダ・ユガ モデル,en_ult_monoeye_a.ice",
            "Cyclonehda Yuga Model,サイクロネーダ・ユガ モデル,en_ult_monoeye_b.ice",
            "Cuchronahda Yuga Animations,キュクロナーダ・ユガ モショーン,en_ult_monoeye_common.ice",
            "Geragodan Model,ジェラゴダン モデル,en_ult_nativebeast.ice",
            "Gibludan Model,ギブルーダン モデル,en_ult_nativebeastthrower.ice",
            "Gibludan Animations,ギブルーダン モショーン,en_ult_nativebeastthrower_common.ice",
            "Geragodan Animations,ジェラゴダン モショーン,en_ult_nativebeast_common.ice",
            "Folgnis Model,フォルギニス モデル,en_ult_pterosaur_a.ice",
            "Folgnis Animations,フォルギニス モショーン,en_ult_pterosaur_common.ice",
            "Yuguldrahda Model,ユグルドラーダ モデル,en_ult_roach_a.ice",
            "Yurisgadrahda Model,ユリスガドラーダ モデル,en_ult_roach_ar.ice",
            "Yuguldrahda Animations,ユグルドラーダ モショーン,en_ult_roach_common.ice",
            "Rapid Gillnas Model,ラピドギルナス モデル,en_ult_separation_mecha_a.ice",
            "Rapid Gillnas Animations,ラピドギルナス モショーン,en_ult_separation_mecha_common.ice",
            "Rapid Gillnas Effects,ラピドギルナス エフェクト,en_ult_separation_mecha_eff.ice",
            "Dagan Yuga Model,ダガン・ユガ モデル,en_ult_soldierant_a.ice",
            "Yugarl Dagan Model,ユガール・ダガン モデル,en_ult_soldierant_ar.ice",
            "Dagan Yuga Animations,ダガン・ユガ モショーン,en_ult_soldierant_common.ice",
            "Anga Phandaj (Dog) Model,アンガ・ファンダージ (犬) モデル,en_ult_waker_beast.ice",
            "Anga Phandaj (Dog) Animations,アンガ・ファンダージ (犬) モショーン,en_ult_waker_beast_common.ice",
            "Anga Phandaj (Dog) Effects,アンガ・ファンダージ (犬)　エフェクト,en_ult_waker_beast_eff.ice",
            "Anga Phandaj Core Model,アンガ・ファンダージ コア モデル,en_ult_waker_core.ice",
            "Anga Phandaj Model,アンガ・ファンダージ モデル,en_ult_waker_symbol_a.ice",
            "Anga Phandaj Model 2,アンガ・ファンダージ モデル 2,en_ult_waker_symbol_b.ice",
            "Anga Phandaj Animations,アンガ・ファンダージ モショーン,en_ult_waker_symbol_common.ice",
            "Anga Phandaj Effects,アンガ・ファンダージ　エフェクト,en_ult_waker_symbol_eff.ice",
            "Balgraf Model,バルグラフ モデル,en_ult_wolf_a.ice",
            "Balgraf Gu Model,バルグラフ・グー モデル,en_ult_wolf_arare.ice",
            "Zgraf Model,ズグラフ モデル,en_ult_wolf_b.ice",
            "Zgraf Gu Model,ズグラフ・グー モデル,en_ult_wolf_brare.ice",
            "graf Animations,グラフ モショーン,en_ult_wolf_common.ice",
            "Kaisfoehgo Model,カイズフォエーゴ　モデル,en_ult_yeti_a.ice",
            "Foehgo Model,フォエーゴ　モデル,en_ult_yeti_b.ice",
            "Foehgo Animations,フォエーゴ　モショーン,en_ult_yeti_common.ice",
            "Mr. Umbra Model,Mr.アンブラ モデル,en_umblla.ice",
            "Mr. Umbra Animations,Mr.アンブラ モショーン,en_umblla_common.ice",
            "Santa Umbra Model,セント・アンブラ モデル,en_umblla_santa.ice",
            "Kabrakan,カブラカン,en_umincyu_a.ice",
            "Nakanishi,ナカニシ,en_umincyu_nakanishi.ice",
            "Nasu,ナス,en_umincyu_nasu.ice",
            "Mr. Bwomf Model,Mr.ボワン モデル,en_unk_lucky_a.ice",
            "Mr. Bwomf Animations,Mr.ボワン モショーン,en_unk_lucky_common.ice",
            "Mesetan,メセタン,en_unk_mstn.ice",
            "Nyau Animations,ニャウ モショーン,en_unk_myau.ice",
            "Nyau Model,ニャウ モデル,en_unk_myau_a.ice",
            "Ceremo-Nyau Model,セレモ・ニャウ モデル,en_unk_myau_arcs.ice",
            "Luna Nyau Model,ルーナ・ニャウ モデル,en_unk_myau_autumn.ice",
            "Happy Nyau Year Model,ノイヤ・ニャウ モデル,en_unk_myau_jan1.ice",
            "Sonic Nyau Model,ソニック・ニャウ モデル,en_unk_myau_sh.ice",
            "Sakura Nyau Model,サクラ・ニャウ モデル,en_unk_myau_spring.ice",
            "Summer Nyau Model,サマー・ニャウ モデル,en_unk_myau_summer.ice",
            "Toro Kuro Nyau Model,トロクロ・ニャウ モデル,en_unk_myau_tk.ice",
            "AIS Exoda Animations,A.I.Sエクソーダ モショーン,en_vehicle_common.ice",
            "AIS Exoda Model,A.I.Sエクソーダ モデル,en_vehicle_enemy.ice",
            "AIS Exoda Rifle Effects,A.I.Sエクソーダ ライフル　エフェクト,en_vehicle_enemy_weapon_a.ice",
            "AIS Exoda Sword Effects,A.I.Sエクソーダ ソード　エフェクト,en_vehicle_enemy_weapon_b.ice",
            "AIS Exoda Launcher Effects,A.I.Sエクソーダ ランチャー　エフェクト,en_vehicle_enemy_weapon_c.ice",
            "Elzelion Model,エルゼリオン モデル,en_volcano_a.ice",
            "Elzelion Animations,エルゼリオン モショーン,en_volcano_common.ice",
            "Elzelion Effects,エルゼリオン エフェクト,en_volcano_eff.ice",
            "Grulf Animations,ガルフ モショーン,en_wolf.ice",
            "Phongrulf Model,フォンガルフ モデル,en_wolf_a.ice",
            "Grulf Model,ガルフ モデル,en_wolf_b.ice",
            "Phongrulfer Model,フォンガルフル モデル,en_wolf_snow_a.ice",
            "Grulfer Model,ガルフル モデル,en_wolf_snow_b.ice",
            "Segrezun Model,セグレズン モデル,en_wtr_ball_a.ice",
            "Segrezun Animations,セグレズン モショーン,en_wtr_ball_common.ice",
            "Degrezun Model,デギレズン モデル,en_wtr_ball_rare.ice",
            "Biol Meduna Model,ビオル・メデューナ モデル,en_wtr_bornt_a.ice",
            "Magisa Meduna Model,マギサ・メデューナ モデル,en_wtr_bornt_ar.ice",
            "Biol Meduna Animations,ビオル・メデューナ モショーン,en_wtr_bornt_common.ice",
            "Biol Meduna Effects,ビオル・メデューナ エフェクト,en_wtr_bornt_eff_common.ice",
            "Falgurbon Model,ファルガルボン モデル,en_wtr_chimpan_a.ice",
            "Gabonarog Model,ガボナロッグ モデル,en_wtr_chimpan_ar.ice",
            "Falgurbon Animations,ファルガルボン モショーン,en_wtr_chimpan_common.ice",
            "Vid Giros,ヴィド・ギロス,en_wtr_cnang.ice",
            "Leomaduraad Animations,レオマドゥラード モショーン,en_wtr_crocodile.ice",
            "Leomaduraad Model,レオマドゥラード モデル,en_wtr_crocodile_a.ice",
            "Malduzareed Model,マルドゥザリード モデル,en_wtr_crocodile_ar.ice",
            "Dalbolupus Model,タルボルプス モデル,en_wtr_dog.ice",
            "Dalbolupus Animations,タルボルプス モショーン,en_wtr_dog_common.ice",
            "Bloomegara Model,ブルメガーラ モデル,en_wtr_flower_a.ice",
            "Fiorgara Model,フィオルガーラ モデル,en_wtr_flower_a_rare.ice",
            "Bloometta Model,ブルメッタ モデル,en_wtr_flower_b.ice",
            "Bloome Animations,ブルメ モショーン,en_wtr_flower_common.ice",
            "Orgbran Model,オルグブラン モデル,en_wtr_gorilla_a.ice",
            "Orgbran Animations,オルグブラン モショーン,en_wtr_gorilla_common.ice",
            "Orgbran Effects,オルグブラン エフェクト,en_wtr_gorilla_eff_common.ice",
            "Orgceratos Model,オルグケラトス モデル,en_wtr_gorilla_rare.ice",
            "Nept Casadohra Animations,ネプト・キャサドーラ モショーン,en_wtr_hookcap.ice",
            "Nept Casadohra Model,ネプト・キャサドーラ モデル,en_wtr_hookcap_a.ice",
            "Casado Badoohl Model,キャサド・バドゥール　モデル,en_wtr_hookcap_ar.ice",
            "Nept Casadohra Effects,ネプト・キャサドーラ エフェクト,en_wtr_hookcap_eff_common.ice",
            "Silt Grimian Model,シルト・グリミアン モデル,en_wtr_massive_a.ice",
            "Silt Grimian Animations,シルト・グリミアン モショーン,en_wtr_massive_common.ice",
            "Sevanian Model,セヴァニアン モデル,en_wtr_mermaid_a.ice",
            "Tag Sevanian Model,タグ・セヴァニアン モデル,en_wtr_mermaid_b.ice",
            "Sevanian Animations,セヴァニアン モショーン,en_wtr_mermaid_common.ice",
            "Tarobekko Model,タロベッコ モデル,en_wtr_penguin.ice",
            "Tarobekko Animations,タロベッコ モショーン,en_wtr_penguin_common.ice",
            "Jigrubekko Model,ジグルベッコ モデル,en_wtr_penguin_rare.ice",
            "Aqualupus Animations,アクルプス モショーン,en_wtr_shark.ice",
            "Aqualupus Model,アクルプス モデル,en_wtr_shark_a.ice",
            "Tag Aqualupus Model,タグ・アクルプス モデル,en_wtr_shark_b.ice",
            "Banoridian Model,バノリディアン モデル,en_wtr_shield_a.ice",
            "Banoridian Animations,バノリディアン モショーン,en_wtr_shield_common.ice",
            "Valadinan Model,ヴァラディナン モデル,en_wtr_soldier_a.ice",
            "Valadinan Effects,ヴァラディナン エフェクト,en_wtr_soldier_a_eff.ice",
            "O Valadinan Model,オ・ヴァラディナン モデル,en_wtr_soldier_b.ice",
            "O Valadinan Effects,オ・ヴァラディナン エフェクト,en_wtr_soldier_b_eff.ice",
            "Su Valadinan Model,ス・ヴァラディナン モデル,en_wtr_soldier_c.ice",
            "Valadinan Animations,ヴァラディナン モショーン,en_wtr_soldier_common.ice",
            "Su Valadinan Effects,ス・ヴァラディナン エフェクト,en_wtr_soldier_c_eff.ice",
            "Branadian Model,ブラナディアン モデル,en_wtr_soldier_d.ice",
            "Bar Lodos Model,バル・ロドス モデル,en_wtr_spnt_a.ice",
            "Bar Dominus Model,バル・ドミヌス モデル,en_wtr_spnt_a_rare.ice",
            "Bar Lodos Model 2,バル・ロドス モデル 2,en_wtr_spnt_b.ice",
            "Bar Lodos Animations 2,バル・ロドス モショーン 2,en_wtr_spnt_b_common.ice",
            "Bar Dominus Model 2,バル・ドミヌス モデル 2,en_wtr_spnt_b_rare.ice",
            "Bar Lodos Animations,バル・ロドス モショーン,en_wtr_spnt_common.ice",
            "Turbon Model,トルボン モデル,en_wtr_tpot_a.ice",
            "Bluturbon Model,ブルトルボン モデル,en_wtr_tpot_b.ice",
            "Turbon Animations,トルボン モショーン,en_wtr_tpot_common.ice",
            "King Yedi Model,キングイエーデ モデル,en_yeti_a.ice",
            "King Yedi Model 2,キングイエーデ モデル 2,en_yeti_a_t.ice",
            "King Yedi Animations,キングイエーデ モショーン,en_yeti_a_t_common.ice",
            "Yedi Model,イエーデ モデル,en_yeti_b.ice",
            "Yedi Animations,イエーデ モショーン,en_yeti_common.ice",
        };

    }
}
