namespace AquaModelLibrary.Data.PSO2.Constants
{
    public class MagNames
    {
        public static Dictionary<int, string> magNames = new Dictionary<int, string>()
        {
            { 1, "???,Alternate Mag?" },
            { 2, "マグ,Mag" },
            { 3, "ライラ,Lyra" },
            { 4, "フォルナクス,Fornax" },
            { 5, "レプス,Lepus"},
            { 6, "アントリア,Antlia"},
            { 7, "ライブラ,Libra"},
            { 8, "ドルフィヌス,Delphinus"},
            { 9, "キグナス,Cygnus"},
            { 10, "カエルム,Caelum"},
            { 11, "ケフェウス,Cepheus"},
            { 12, "ツカナ,Tsukana"},
            { 13, "カリーナ,Carina"},
            { 14, "モノケロス,Monoceros"},
            { 15, "オリオン,Orion"},
            { 16, "アプス,Apus"},
            { 17, "コルブス,Corvus"},
            { 18, "レオ,Leo"},
            { 19, "クルックス,Crux"},
            { 20, "リンクス,Lynx"},
            { 21, "ドラコ,Draco"},
            { 22, "シャト,Sato"},
            { 23, "ラッピー,Rappy"},
            { 24, "ジャック,Jack"},
            { 25, "ピート,Pete"},
            { 26, "キャンサー,Cancer"},
            { 27, "アクベンス,Acubens"},
            { 28, "アセルス,Asers"},
            { 29, "アルタルフ,Altarf"},
            { 30, "キトゥン,Kitten"},
            { 31, "カッツェ,Katze"},
            { 32, "ミーツェ,Miishe"},
            { 33, "クラーリタ,Clarita"},
            { 34, "ナナハナ,nanahana"},
            { 35, "アークマ,Arkuma"},
            { 36, "アークマミ,Arkumami"},
            { 37, "アンブラ,Umbra"},
            { 38, "トロ,Toro"},
            { 39, "クロ,Kuro"},
            { 40, "ハンプティ,Humpty"},
            { 41, "チャムライ,Chamurai"},
            { 42, "チャーク,Chark"},
            { 43, "リリーパ,Lillipan"},
            { 44, "ゴストン,Ghoston"},
            { 45, "ソニチ,Sonichi"},
            { 46, "プーシャン,Pushan"},
            { 47, "ミクダヨー,Mikudayo-"},
            { 48, "緑ぷよ,Green Puyo"},
            { 49, "カーバンクル,Carbuncle"},
            { 50, "キュゥべえ,Kyubey"},
            { 51, "ポリタン,Polytan"},
            { 52, "カガミミ,Kagamimi"},
            { 53, "ラブラッピー,Love Rappy"},
            { 54, "ラヴィラッピー,Lovey Rappy"},
            { 55, "キャリブー,Caribou" },
            { 56, ",Unidentified Black Bear"},
            { 57, "イーツター,Eatster (Intended spelling)"},
            { 58, "ミャリッジ,Wedding Bell"},
            { 59, "ベレイ,Berei"},
            { 60, "ベレイMk2,Berei Mk2"},
            { 61, "エトワル,étoile"},
            { 62, "月見ラッピー,Moon-Viewing Rappy"},
            { 63, "ソニック人形, Sonic Doll"},
            { 64, "モロ星人,Moro Alien"},
            { 65, "モロ星人B,Moro Alien B"},
            { 66, "ナイトギア,Nightgear"},
            { 67, "ニャウ,Nyau"},
            { 68, "ジャクラン,Jack Lan"},
            { 69, "テルクゥ,Teruku"},
            { 70, "キリゾー,Girizoo"},
            { 71, "SFC妖精,SFC Fairy"},
            { 72, "赤ぷよ,Red Puyo"},
            { 73, "ダンボー,Danboard"},
            { 74, "カラッピー,Karappy"},
            { 75, "タマヒメ,Tamahime"},
            { 76, "お団子ヘア,Dumpling Hair"},
            { 77, "ラブリーパ,LoveLipa"},
            { 78, "ラヴィリー,LoveLi"},
            { 79, "ドリキャス,Dreamcast"},
            { 80, "セガサターン,Sega Saturn"},
            { 81, "メガドラ,Mega Drive"},
            { 82, "アナライザー,Analyzer"},
            { 83, "ホヌホヌ,Honuhonu" },
            { 84, "小梅,Xiaomei"},
            { 85, "ニャンドリオン（ニャンD）,Nyandorion (NyanD)"},
            { 86, "A.I.S,A.I.S"},

            { 88, "ジーツター,Jiitsuter"},
            { 89, "レイニャン,Rainyan"},
            { 90, "ルクミン,Rukmin"},
            { 91, "ネッキー,Necky"},
            { 92, "リンクスR,Lynx R"},
            { 93, "キトゥンR,Kitten R"},
            { 96, "キャンサーR,Cancer R"},
            { 97, "アクベンスR,Acubens R"},
            { 100, "波乗ニャウ,Wave Riding Nyau"},
            { 101, "リリダイコ,Lilidaigo"},
            { 102, "RRリコ,RR Rico"},
            { 103, "ニドラー,Nidra"},
            { 104, "ピトリ,Pitri"},
            { 105, "プチアンガ,Petit Anga"},
            { 106, "ウサノヤ,Usanoya"},
            { 107, "モチュゴヤ,Mochugoya"},
            { 108, "オパオパ,Opa-Opa"},
            { 109, "紫ぷよ,Purple Puyo"},
            { 110, "テムジン,Temjin"},
            { 111, "青ぷよ,Blue Puyo"},
            { 112, "ルーシャー,Luther"},
            { 113, "バットリー,Batreat"},
            { 114, "シャノルン,Chanolun"},
            { 115, "ハッピー,Happy"},
            { 116, "ナガミミ,Nagamimi"},
            { 117, "ノルルン,Nolulun"},
            { 118, "クツッピー,Kutsuppy"},
            { 119, "ラブクマミ,Lovekumami"},
            { 120, "ラヴィクマ,LoveyKuma"},
            { 121, "チェリシュ,Cherish"},
            { 122, "オーディン,Odin"},
            { 123, "モーグリ,Moogle"},
            { 124, "プリニー,Prinny"},
            { 125, "東京タワーラッピー,Tokyo Tower Rappy"},
            { 126, "金シャチラッピー,Golden Whale Rappy"},
            { 127, "屋台ラッピー,Food Cart Rappy"},
            { 128, "ジンギスカンラッピー,Jingisukan Rappy"},
            { 129, "通天閣(R)ラッピー,Tsutenkaku (R) Rappy"},
            { 130, "ステルス化,Stealth"},
            { 131, "ケツカッチン,Ketsukacchin"},
            { 132, "エスカくん,Eska-kun"},
            { 133, "プリュミー,Plumii"},
            { 134, "光武二式（大神機）,Koubu MK II (OM)"},
            { 135, "光武二式（さくら機）,Koubu MK II (SM)"},
            { 136, "パティエンティア,Patty & Tiea"},
            { 137, "ワンダラー,Wanderer"},
            { 138, "ミニゴジラ,Mini Godzilla"},
            { 139, "ピートR,Pete R"},
            { 140, "ブラナート,Brownart"},

            { 143, "ポーラー,Polar"},
            { 144, "ポッド０４２,Pod 042"},
            { 145, "ポッド１５３,Pod 153"},
            { 146, "桜ニャウ,Sakura Nyau"},
            { 147, "フログラッピー,Frog Rappy"},
            { 148, "モア,Moa"},
            { 149, "スティレットＧ,Stylet G"},
            { 150, "エンペ・ラッピー,Empe Rappy"},
            { 151, "ヤミガラス,Yamigarasu"},
            { 152, "プラフタ,Plachta"},
            { 153, "ラタン・エンペ,Rotten Empe"},
            { 154, "アクス・ラッピー,ARKS Rappy"},
            { 155, "フェザーキャロル,Feather Carole"},
            { 156, "フェリチェマクス,Felice Max"},
            { 158, "ホワイトラプラス,White Laplace"},
            { 159, "エグ・ラッピー,Egg Rappy"},
            { 160, "ラヴィ・エンペ,Lovey Empe"},
            { 162, "パック,Puck"},
            { 164, "ラブ・エンペ,Love Empe"},
            { 166, "ダークラッピー,Dark Rappy"},
            { 167, "テルテルラッピー,Tell Tell Rappy"},
            { 168, "モルガナ,Morgana"},
            { 169, "バーゼラルドＧ,Baselard G"},
            { 170, "轟雷Ｇ,Gourai G"},
            { 171, "パートニャー,Partnya"},
            { 172, "プーギー,Poogie"},
            { 173, "レイチュ,Reichu"},
            { 174, "セント・ラッピー,Saint Rappy"},
            { 176, "ジャックフロスト,Jack Frost"},

            { 177, ",Ornate Japanese looking black pig"},
            { 178, "ちびレラ,Sabirera (Quartz Dragon/クォーツドラゴン)"},
            { 179, "サクリャ,Sakurya"},
            { 180, "リトルメデューナ,Little Meduna"},
            { 181, "キツネアメ,Kitsune Ame"},
            { 182, "カグヤ,Kaguya"},
            { 183, "ペルチョナ,Perchona"},
            { 184, "タマヒメ2,Tamahime 2"},
            { 185, "ペギー,Pegi"},
            { 186, "ペギータ,Pegita"},
            { 188, "Vハンター,V Hunter"},
            { 190, "パイ,Pai"},
            { 191, ",Ornate Japanese looking black mouse"},
            { 192, "チョトリ,Chotrea"},
            { 193, "ミルトリ,Miltrea"},
            { 194, "フェズ,Feath"},
            { 195, "カエルン,Kaerun"},
            { 196, "オッチャ,Ocha"},

            { 999, "Debug" }
        };
    }
}
