namespace AquaModelLibrary.Data.PSO2.Constants
{
    public static class MusicFilenames
    {
        public static string adaptivePath = "sound/music/adaptive/";
        public static string streamPath = "sound/music/stream/";

        public static Dictionary<string, string> ngsAdaptiveNames = new Dictionary<string, string>()
        {
            { "mu_11_bgm_ct.ice", ""},
            { "mu_11_bgm_gl.ice", ""},
            { "mu_11_bgm02_anv09.ice", ""},
            { "mu_11_bgm02_boss_b01.ice", ""},
            { "mu_11_bgm02_boss_e01.ice", ""},
            { "mu_11_bgm02_boss_e01sb.ice", ""},
            { "mu_11_bgm02_boss_f01.ice", ""},
            { "mu_11_bgm02_boss_m01.ice", ""},
            { "mu_11_bgm02_boss_ne.ice", ""},
            { "mu_11_bgm02_boss_nea.ice", ""},
            { "mu_11_bgm02_cl.ice", ""},
            { "mu_11_bgm02_clear.ice", ""},
            { "mu_11_bgm02_cm.ice", ""},
            { "mu_11_bgm02_col001.ice", ""},
            { "mu_11_bgm02_ct.ice", ""},
            { "mu_11_bgm02_cte.ice", ""},
            { "mu_11_bgm02_defense_1.ice", ""},
            { "mu_11_bgm02_defense_1_before.ice", ""},
            { "mu_11_bgm02_defense_1_clear.ice", ""},
            { "mu_11_bgm02_enemy_st.ice", ""},
            { "mu_11_bgm02_qw01.ice", ""},
            { "mu_11_bgm02_rg01-01.ice", ""},
            { "mu_11_bgm02_rg01-02.ice", ""},
            { "mu_11_bgm02_rg01-03.ice", ""},
            { "mu_11_bgm02_rg01-04.ice", ""},
            { "mu_11_bgm02_rg01-05.ice", ""},
            { "mu_11_bgm02_rg01-06.ice", ""},
            { "mu_11_bgm02_sc.ice", ""},
            { "mu_11_bgm02_se_halloween.ice", ""},
            { "mu_11_bgm02_se_tsukimi.ice", ""},
            { "mu_11_bgm02_tcc01.ice", ""},
            { "mu_11_bgm02_tccf.ice", ""},
            { "mu_11_bgm02_tccs.ice", ""},
            { "mu_11_bgm02_tilg.ice", ""},
            { "mu_11_bgm02_ttcf.ice", ""},
            { "mu_11_bgm02_ttcs.ice", ""},
            { "mu_11_bgm02_ttwp01.ice", ""},
            { "mu_11_bgm02_ttwp02.ice", ""},
            { "mu_11_bgm02_rg02_01day_md.ice", ""},
            { "mu_11_bgm02_rg02_01night_md.ice", ""},
            { "mu_11_bgm02_rg02_02_md.ice", ""},
            { "mu_11_bgm02_rg02_03_md.ice", ""},
            { "mu_11_bgm02_rg02_04_md.ice", ""},
            { "mu_11_bgm02_twp03.ice", ""},
            { "mu_11_bgm02_tpy01.ice", ""},
            { "mu_11_bgm02_rg01_06_md.ice", ""},
            { "mu_11_bgm02_rg01_01night_md.ice", ""},
            { "mu_11_bgm02_boss_rg03_kh.ice", ""},
            { "mu_11_bgm02_se_christmas.ice", ""},
            { "mu_11_bgm02_se_newyear.ice", ""},
            { "mu_11_bgm02_boss_f02.ice", ""},
            { "mu_11_bgm02_rg01_03day_md.ice", ""},
            { "mu_11_bgm02_rg02_02.ice", ""},
            { "mu_11_bgm02_rg01_02_md.ice", ""},
            { "mu_11_bgm02_boss_rg02_rr.ice", ""},
            { "mu_11_bgm02_boss_rg02_rr_md.ice", ""},
            { "mu_11_bgm02_boss_rg02_rra.ice", ""},
            { "mu_11_bgm02_tr_md.ice", ""},
            { "mu_11_bgm02_ct_md.ice", ""},
            { "mu_11_bgm02_boss_ne_md.ice", ""},
            { "mu_11_bgm01_wopal3.ice", ""},
            { "mu_11_bgm02_boss_rg03_m01.ice", ""},
            { "mu_11_bgm02_rg01_03night_md.ice", ""},
            { "mu_11_bgm01_cave.ice", ""},
            { "mu_11_bgm02_ct_r02.ice", ""},
            { "mu_11_bgm02_enemy_st2.ice", ""},
            { "mu_11_bgm02_boss_f02_md.ice", ""},
            { "mu_11_bgm02_boss_b01_md.ice", ""},
            { "mu_11_bgm02_boss_nea_md.ice", ""},
            { "mu_11_bgm02_rg03_07.ice", ""},
            { "mu_11_bgm01_col_rg02_desert.ice", ""},
            { "mu_11_bgm02_boss_f02_2.ice", ""},
            { "mu_11_bgm02_rg03_06.ice", ""},
            { "mu_11_bgm02_se_spring.ice", ""},
            { "mu_11_bgm02_ct_r01.ice", ""},
            { "mu_11_bgm02_tilg_md.ice", ""},
            { "mu_11_bgm02_rg02_04.ice", ""},
            { "mu_11_bgm02_se_1year.ice", ""},
            { "mu_11_bgm01_col_rg02_wopal3.ice", ""},
            { "mu_11_bgm02_tpcf.ice", ""},
            { "mu_11_bgm02_boss_f_sb.ice", ""},
            { "mu_11_bgm02_boss_rg02_m01.ice", ""},
            { "mu_11_bgm02_qw02_i.ice", ""},
            { "mu_11_bgm02_enemy_st_md.ice", ""},
            { "mu_11_bgm02_ttw01.ice", ""},
            { "mu_11_bgm02_boss_rg03_b01.ice", ""},
            { "mu_11_bgm02_boss_rg02_b01.ice", ""},
            { "mu_11_bgm01_desert.ice", ""},
            { "mu_11_bgm02_anv10.ice", ""},
            { "mu_11_bgm01_col_rg02_cave.ice", ""},
            { "mu_11_bgm02_ct_k02.ice", ""},
            { "mu_11_bgm02_rg03_01.ice", ""},
            { "mu_11_bgm02_twp02.ice", ""},
            { "mu_11_bgm02_fr01.ice", ""},
            { "mu_11_bgm02_twp01.ice", ""},
            { "mu_11_bgm02_boss_m01_md.ice", ""},
            { "mu_11_bgm02_qw02.ice", ""},
            { "mu_11_bgm02_ct_k01.ice", ""},
            { "mu_11_bgm02_tpcs.ice", ""},
            { "mu_11_bgm02_10year.ice", ""},
            { "mu_11_bgm02_rg03_05.ice", ""},
            { "mu_11_bgm02_rg01_01day_md.ice", ""},
            { "mu_11_bgm02_rg01_04_md.ice", ""},
            { "mu_11_bgm02_rg03_04.ice", ""},
            { "mu_11_bgm02_se_winter.ice", ""},
        };

        public static Dictionary<string, string> ngsStreamNames = new Dictionary<string, string>()
        {
            { "11_bgm_pso2_lobby.hca", ""},
            { "11_bgm_test_twnw.hca", ""},
            { "11_bgm02_bm_e1_001.hca", ""},
            { "11_bgm02_col_st_001.hca", ""},
            { "11_bgm02_col_st_002.hca", ""},
            { "11_bgm02_col_st_003.hca", ""},
            { "11_bgm02_defense_1_plg.hca", ""},
            { "11_bgm02_event_e1_001.hca", ""},
            { "11_bgm02_event_e1_002.hca", ""},
            { "11_bgm02_event_e1_003.hca", ""},
            { "11_bgm02_event_e1_004.hca", ""},
            { "11_bgm02_event_e1_005.hca", ""},
            { "11_bgm02_event_e1_006.hca", ""},
            { "11_bgm02_event_e1_007.hca", ""},
            { "11_bgm02_event_e1_008.hca", ""},
            { "11_bgm02_event_e1_009.hca", ""},
            { "11_bgm02_event_e1_016.hca", ""},
            { "11_bgm02_sr_e1_001.hca", ""},
        };

        public static Dictionary<string, string> classicStreamHashes = new Dictionary<string, string>()
        {
            { "2fbb7443eef24ca0bc9542eaa559805d", "The MMORPG Addicts Anthem,The MMORPG Addicts Anthem"},
            { "22b94b757fac06570a8add4de93d3070", "Catch the Wave,Catch the Wave"},
            { "95c8a56f64b070b64788095436df7022", "Miku Miku Ni Shite Ageru,Miku Miku Ni Shite Ageru"},
            { "99f34007db020150befac94af7ad3637", "Snowman,Snowman"},
            { "564d8ab9766cc19709149947cc015d89", "Luka Luka Night Fever,Luka Luka Night Fever"},
            { "a2cecac4b2423573ce50de05669576e9", "World's End Dancehall,World's End Dancehall"},
            { "d16738bff6fac061d6d8c252f1226a90", "Alien Alien,Alien Alien"},
        };

        public static Dictionary<string, string> classicStreamNames = new Dictionary<string, string>()
        {
            {"11_bgm_20b1.hca", ""},
            {"11_bgm_20b2.hca", ""},
            {"11_bgm_ballade_vocal_st012100.hca", ""},
            {"11_bgm_ballade_vocal_un12100.hca", ""},
            {"11_bgm_bd010010.hca", ""},
            {"11_bgm_bd010020.hca", ""},
            {"11_bgm_bd010030.hca", ""},
            {"11_bgm_bd010040.hca", ""},
            {"11_bgm_bd010050.hca", ""},
            {"11_bgm_bd010060.hca", ""},
            {"11_bgm_bench161.hca", ""},
            {"11_bgm_bench162.hca", ""},
            {"11_bgm_boss_sh2_streamloop.hca", ""},
            {"11_bgm_boss_sh3_streamloop.hca", ""},
            {"11_bgm_city_streamloop.hca", ""},
            {"11_bgm_clb04_1.hca", ""},
            {"11_bgm_clb04_2.hca", ""},
            {"11_bgm_clb04_3.hca", ""},
            {"11_bgm_clb04_4.hca", ""},
            {"11_bgm_clb04_5.hca", ""},
            {"11_bgm_clb19_1-1.hca", ""},
            {"11_bgm_clb19_1-2.hca", ""},
            {"11_bgm_clb19_1-3.hca", ""},
            {"11_bgm_clb19_1-4.hca", ""},
            {"11_bgm_clb19_1-5.hca", ""},
            {"11_bgm_edinst_1_pf.hca", ""},
            {"11_bgm_edinst_1_str.hca", ""},
            {"11_bgm_edinst_1_strpf.hca", ""},
            {"11_bgm_edinst_2_pf.hca", ""},
            {"11_bgm_edinst_2_str.hca", ""},
            {"11_bgm_edinst_2_strpf.hca", ""},
            {"11_bgm_edinst_add_1_harfintro_pf.hca", ""},
            {"11_bgm_edinst_add_1_harfintro_str.hca", ""},
            {"11_bgm_edinst_add_1_harfintro_strpf.hca", ""},
            {"11_bgm_edinst_add_1_nointro_pf.hca", ""},
            {"11_bgm_edinst_add_1_nointro_str.hca", ""},
            {"11_bgm_edinst_add_1_nointro_strpf.hca", ""},
            {"11_bgm_edinst_add_2-2_pf.hca", ""},
            {"11_bgm_edinst_add_2-2_str.hca", ""},
            {"11_bgm_edinst_add_2-2_strpf.hca", ""},
            {"11_bgm_edinst_add_full_nointro_pf.hca", ""},
            {"11_bgm_edinst_add_full_nointro_str.hca", ""},
            {"11_bgm_edinst_add_full_nointro_strpf.hca", ""},
            {"11_bgm_edinst_add_introloop.hca", ""},
            {"11_bgm_edinst_full_pf.hca", ""},
            {"11_bgm_edinst_full_str.hca", ""},
            {"11_bgm_edinst_full_strpf.hca", ""},
            {"11_bgm_ep2ed_endroll.hca", ""},
            {"11_bgm_ep3ed_bad_endroll.hca", ""},
            {"11_bgm_ep3ed_true_endroll.hca", ""},
            {"11_bgm_ep4ed_endroll.hca", ""},
            {"11_bgm_event_aether.hca", ""},
            {"11_bgm_event_after.hca", ""},
            {"11_bgm_event_am_e.hca", ""},
            {"11_bgm_event_am_g.hca", ""},
            {"11_bgm_event_angry.hca", ""},
            {"11_bgm_event_arks.hca", ""},
            {"11_bgm_event_aru.hca", ""},
            {"11_bgm_event_ballade_piano_full.hca", ""},
            {"11_bgm_event_ballade_piano_sabi.hca", ""},
            {"11_bgm_event_before7.hca", ""},
            {"11_bgm_event_brain.hca", ""},
            {"11_bgm_event_brave.hca", ""},
            {"11_bgm_event_comical.hca", ""},
            {"11_bgm_event_cool.hca", ""},
            {"11_bgm_event_daily.hca", ""},
            {"11_bgm_event_darker_kyoku.hca", ""},
            {"11_bgm_event_darker.hca", ""},
            {"11_bgm_event_deh.hca", ""},
            {"11_bgm_event_densyo.hca", ""},
            {"11_bgm_event_e5_001_01.hca", ""},
            {"11_bgm_event_e5_001_02.hca", ""},
            {"11_bgm_event_e5_001_03.hca", ""},
            {"11_bgm_event_e5_001_04.hca", ""},
            {"11_bgm_event_e5_001_05.hca", ""},
            {"11_bgm_event_e5_001_06.hca", ""},
            {"11_bgm_event_e5_001_07.hca", ""},
            {"11_bgm_event_e5_001_08.hca", ""},
            {"11_bgm_event_e5_001_09.hca", ""},
            {"11_bgm_event_e5_001_10.hca", ""},
            {"11_bgm_event_e5_001_11.hca", ""},
            {"11_bgm_event_e5_001_12.hca", ""},
            {"11_bgm_event_e5_001.hca", ""},
            {"11_bgm_event_e5_002.hca", ""},
            {"11_bgm_event_e5_003.hca", ""},
            {"11_bgm_event_e5_004.hca", ""},
            {"11_bgm_event_e5_006.hca", ""},
            {"11_bgm_event_e5_008.hca", ""},
            {"11_bgm_event_e5_009.hca", ""},
            {"11_bgm_event_e5_010.hca", ""},
            {"11_bgm_event_e5_011.hca", ""},
            {"11_bgm_event_e5_012.hca", ""},
            {"11_bgm_event_e5_013.hca", ""},
            {"11_bgm_event_e5_014.hca", ""},
            {"11_bgm_event_e5_015.hca", ""},
            {"11_bgm_event_e5_016.hca", ""},
            {"11_bgm_event_e5_017.hca", ""},
            {"11_bgm_event_e5_018.hca", ""},
            {"11_bgm_event_e5_019.hca", ""},
            {"11_bgm_event_e5_021.hca", ""},
            {"11_bgm_event_e5_022.hca", ""},
            {"11_bgm_event_e5_023.hca", ""},
            {"11_bgm_event_e5_025.hca", ""},
            {"11_bgm_event_e5_026.hca", ""},
            {"11_bgm_event_e5_027.hca", ""},
            {"11_bgm_event_e5_028.hca", ""},
            {"11_bgm_event_e5_029.hca", ""},
            {"11_bgm_event_e5_030.hca", ""},
            {"11_bgm_event_e5_031.hca", ""},
            {"11_bgm_event_e5_032.hca", ""},
            {"11_bgm_event_e5_034.hca", ""},
            {"11_bgm_event_e5_035.hca", ""},
            {"11_bgm_event_e5_036.hca", ""},
            {"11_bgm_event_e5_037.hca", ""},
            {"11_bgm_event_e5_038.hca", ""},
            {"11_bgm_event_e5_039.hca", ""},
            {"11_bgm_event_e5_040.hca", ""},
            {"11_bgm_event_e6_001.hca", ""},
            {"11_bgm_event_e6_002.hca", ""},
            {"11_bgm_event_e6_003.hca", ""},
            {"11_bgm_event_e6_004.hca", ""},
            {"11_bgm_event_e6_005.hca", ""},
            {"11_bgm_event_e6_006.hca", ""},
            {"11_bgm_event_e6_007.hca", ""},
            {"11_bgm_event_e6_008.hca", ""},
            {"11_bgm_event_e6_009.hca", ""},
            {"11_bgm_event_e6_010.hca", ""},
            {"11_bgm_event_e6_011.hca", ""},
            {"11_bgm_event_e6_012.hca", ""},
            {"11_bgm_event_e6_013.hca", ""},
            {"11_bgm_event_e6_014.hca", ""},
            {"11_bgm_event_e6_015.hca", ""},
            {"11_bgm_event_e6_016.hca", ""},
            {"11_bgm_event_e6_017.hca", ""},
            {"11_bgm_event_e6_020.hca", ""},
            {"11_bgm_event_e6_021.hca", ""},
            {"11_bgm_event_e6_022.hca", ""},
            {"11_bgm_event_e6_023.hca", ""},
            {"11_bgm_event_e6_wafu1.hca", ""},
            {"11_bgm_event_earthguide.hca", ""},
            {"11_bgm_event_easy.hca", ""},
            {"11_bgm_event_edf.hca", ""},
            {"11_bgm_event_gensoushu.hca", ""},
            {"11_bgm_event_gmm.hca", ""},
            {"11_bgm_event_hageshii.hca", ""},
            {"11_bgm_event_hg.hca", ""},
            {"11_bgm_event_hime.hca", ""},
            {"11_bgm_event_hitsugi.hca", ""},
            {"11_bgm_event_joy.hca", ""},
            {"11_bgm_event_lb4_2.hca", ""},
            {"11_bgm_event_lb4.hca", ""},
            {"11_bgm_event_matoi.hca", ""},
            {"11_bgm_event_mattari.hca", ""},
            {"11_bgm_event_mcb.hca", ""},
            {"11_bgm_event_mct.hca", ""},
            {"11_bgm_event_mdfch1.hca", ""},
            {"11_bgm_event_motd.hca", ""},
            {"11_bgm_event_mother.hca", ""},
            {"11_bgm_event_nod.hca", ""},
            {"11_bgm_event_non.hca", ""},
            {"11_bgm_event_ofuro.hca", ""},
            {"11_bgm_event_oph1.hca", ""},
            {"11_bgm_event_oph2.hca", ""},
            {"11_bgm_event_oph3.hca", ""},
            {"11_bgm_event_peace.hca", ""},
            {"11_bgm_event_pg_h.hca", ""},
            {"11_bgm_event_pg_s.hca", ""},
            {"11_bgm_event_sad.hca", ""},
            {"11_bgm_event_sad2_2.hca", ""},
            {"11_bgm_event_sad2.hca", ""},
            {"11_bgm_event_seabed.hca", ""},
            {"11_bgm_event_shutugeki.hca", ""},
            {"11_bgm_event_sion.hca", ""},
            {"11_bgm_event_title.hca", ""},
            {"11_bgm_event_tkd.hca", ""},
            {"11_bgm_event_tkn.hca", ""},
            {"11_bgm_event_uneasy1.hca", ""},
            {"11_bgm_event_uneasy2.hca", ""},
            {"11_bgm_event_uneasy3.hca", ""},
            {"11_bgm_ls010010.hca", ""},
            {"11_bgm_ls010020.hca", ""},
            {"11_bgm_ls010030.hca", ""},
            {"11_bgm_ls010040.hca", ""},
            {"11_bgm_ls010050.hca", ""},
            {"11_bgm_ls010060.hca", ""},
            {"11_bgm_ls010070.hca", ""},
            {"11_bgm_ls010080.hca", ""},
            {"11_bgm_movielive.hca", ""},
            {"11_bgm_musicdisc_001.hca", "PSO2 メインテーマ,PSO2 Main Theme"},
            {"11_bgm_musicdisc_002.hca", "Our Fighting,Our Fighting"},
            {"11_bgm_musicdisc_003.hca", "永遠のencore,Eternal Encore"},
            {"11_bgm_musicdisc_004.hca", "PSO2 メインテーマVer2,PSO2 Main Theme 2nd Arrangement"},
            {"11_bgm_musicdisc_005.hca", ""},
            {"11_bgm_musicdisc_006.hca", ""},
            {"11_bgm_musicdisc_007.hca", ""},
            {"11_bgm_musicdisc_008.hca", ""},
            {"11_bgm_musicdisc_009.hca", ""},
            {"11_bgm_musicdisc_010.hca", ""},
            {"11_bgm_musicdisc_011.hca", ""},
            {"11_bgm_musicdisc_012.hca", ""},
            {"11_bgm_musicdisc_013.hca", ""},
            {"11_bgm_musicdisc_014.hca", ""},
            {"11_bgm_musicdisc_015.hca", ""},
            {"11_bgm_musicdisc_016.hca", ""},
            {"11_bgm_musicdisc_017.hca", ""},
            {"11_bgm_musicdisc_018.hca", ""},
            {"11_bgm_musicdisc_019.hca", ""},
            {"11_bgm_musicdisc_020.hca", ""},
            {"11_bgm_musicdisc_021.hca", ""},
            {"11_bgm_musicdisc_022.hca", ""},
            {"11_bgm_musicdisc_023.hca", ""},
            {"11_bgm_musicdisc_024_1.hca", ""},
            {"11_bgm_musicdisc_024_2.hca", ""},
            {"11_bgm_musicdisc_024_3.hca", ""},
            {"11_bgm_musicdisc_024_4.hca", ""},
            {"11_bgm_musicdisc_024_5.hca", ""},
            {"11_bgm_musicdisc_024_6.hca", ""},
            {"11_bgm_musicdisc_026.hca", ""},
            {"11_bgm_musicdisc_027.hca", ""},
            {"11_bgm_musicdisc_028.hca", ""},
            {"11_bgm_musicdisc_029.hca", ""},
            {"11_bgm_musicdisc_030.hca", ""},
            {"11_bgm_musicdisc_031.hca", ""},
            {"11_bgm_musicdisc_032.hca", ""},
            {"11_bgm_musicdisc_033.hca", ""},
            {"11_bgm_musicdisc_034.hca", ""},
            {"11_bgm_musicdisc_035.hca", ""},
            {"11_bgm_musicdisc_040.hca", ""},
            {"11_bgm_musicdisc_062.hca", ""},
            {"11_bgm_musicdisc_101.hca", ""},
            {"11_bgm_musicdisc_102.hca", ""},
            {"11_bgm_musicdisc_103.hca", ""},
            {"11_bgm_musicdisc_104.hca", ""},
            {"11_bgm_musicdisc_105.hca", ""},
            {"11_bgm_musicdisc_106.hca", ""},
            {"11_bgm_musicdisc_107.hca", ""},
            {"11_bgm_musicdisc_108.hca", ""},
            {"11_bgm_musicdisc_109.hca", ""},
            {"11_bgm_musicdisc_110.hca", ""},
            {"11_bgm_musicdisc_111.hca", ""},
            {"11_bgm_musicdisc_112.hca", ""},
            {"11_bgm_musicdisc_113.hca", ""},
            {"11_bgm_musicdisc_114.hca", ""},
            {"11_bgm_musicdisc_116.hca", ""},
            {"11_bgm_musicdisc_119.hca", ""},
            {"11_bgm_musicdisc_120.hca", ""},
            {"11_bgm_musicdisc_121.hca", ""},
            {"11_bgm_musicdisc_135.hca", ""},
            {"11_bgm_musicdisc_136.hca", ""},
            {"11_bgm_musicdisc_137.hca", ""},
            {"11_bgm_musicdisc_138.hca", ""},
            {"11_bgm_musicdisc_139.hca", ""},
            {"11_bgm_musicdisc_140.hca", ""},
            {"11_bgm_musicdisc_141.hca", ""},
            {"11_bgm_musicdisc_142.hca", ""},
            {"11_bgm_musicdisc_143.hca", ""},
            {"11_bgm_musicdisc_144.hca", ""},
            {"11_bgm_musicdisc_145.hca", ""},
            {"11_bgm_musicdisc_146.hca", ""},
            {"11_bgm_musicdisc_147.hca", ""},
            {"11_bgm_musicdisc_148.hca", ""},
            {"11_bgm_musicdisc_149.hca", ""},
            {"11_bgm_musicdisc_151.hca", ""},
            {"11_bgm_musicdisc_152.hca", ""},
            {"11_bgm_musicdisc_153.hca", ""},
            {"11_bgm_musicdisc_154.hca", ""},
            {"11_bgm_musicdisc_155.hca", ""},
            {"11_bgm_musicdisc_156.hca", ""},
            {"11_bgm_musicdisc_157.hca", ""},
            {"11_bgm_musicdisc_158.hca", ""},
            {"11_bgm_musicdisc_159.hca", ""},
            {"11_bgm_musicdisc_160.hca", ""},
            {"11_bgm_musicdisc_161.hca", ""},
            {"11_bgm_musicdisc_162.hca", ""},
            {"11_bgm_musicdisc_163.hca", ""},
            {"11_bgm_musicdisc_164.hca", ""},
            {"11_bgm_musicdisc_165.hca", ""},
            {"11_bgm_musicdisc_166.hca", ""},
            {"11_bgm_musicdisc_167.hca", ""},
            {"11_bgm_musicdisc_168.hca", ""},
            {"11_bgm_musicdisc_169.hca", ""},
            {"11_bgm_musicdisc_170.hca", ""},
            {"11_bgm_musicdisc_171.hca", ""},
            {"11_bgm_musicdisc_172.hca", ""},
            {"11_bgm_musicdisc_173.hca", ""},
            {"11_bgm_musicdisc_174.hca", ""},
            {"11_bgm_musicdisc_175.hca", ""},
            {"11_bgm_musicdisc_176.hca", ""},
            {"11_bgm_musicdisc_177.hca", ""},
            {"11_bgm_musicdisc_178.hca", ""},
            {"11_bgm_musicdisc_179.hca", ""},
            {"11_bgm_musicdisc_180.hca", ""},
            {"11_bgm_musicdisc_181.hca", ""},
            {"11_bgm_musicdisc_182.hca", ""},
            {"11_bgm_musicdisc_183.hca", ""},
            {"11_bgm_musicdisc_184.hca", ""},
            {"11_bgm_musicdisc_185.hca", ""},
            {"11_bgm_musicdisc_186.hca", ""},
            {"11_bgm_musicdisc_187.hca", ""},
            {"11_bgm_musicdisc_190.hca", ""},
            {"11_bgm_musicdisc_191.hca", ""},
            {"11_bgm_musicdisc_193.hca", ""},
            {"11_bgm_musicdisc_194.hca", ""},
            {"11_bgm_musicdisc_195.hca", ""},
            {"11_bgm_musicdisc_196.hca", ""},
            {"11_bgm_musicdisc_197.hca", ""},
            {"11_bgm_musicdisc_198.hca", ""},
            {"11_bgm_musicdisc_199.hca", ""},
            {"11_bgm_musicdisc_201.hca", ""},
            {"11_bgm_musicdisc_202.hca", ""},
            {"11_bgm_musicdisc_203.hca", ""},
            {"11_bgm_musicdisc_204.hca", ""},
            {"11_bgm_musicdisc_208.hca", ""},
            {"11_bgm_musicdisc_209.hca", ""},
            {"11_bgm_musicdisc_210.hca", ""},
            {"11_bgm_musicdisc_211.hca", ""},
            {"11_bgm_musicdisc_212.hca", ""},
            {"11_bgm_musicdisc_213.hca", ""},
            {"11_bgm_musicdisc_214.hca", ""},
            {"11_bgm_musicdisc_215.hca", ""},
            {"11_bgm_musicdisc_216.hca", ""},
            {"11_bgm_musicdisc_217.hca", ""},
            {"11_bgm_musicdisc_218.hca", ""},
            {"11_bgm_musicdisc_219.hca", ""},
            {"11_bgm_musicdisc_220.hca", ""},
            {"11_bgm_musicdisc_221.hca", ""},
            {"11_bgm_musicdisc_222.hca", ""},
            {"11_bgm_musicdisc_223.hca", ""},
            {"11_bgm_musicdisc_224.hca", ""},
            {"11_bgm_musicdisc_229.hca", ""},
            {"11_bgm_musicdisc_251.hca", ""},
            {"11_bgm_musicdisc_252.hca", ""},
            {"11_bgm_musicdisc_253.hca", ""},
            {"11_bgm_musicdisc_254.hca", ""},
            {"11_bgm_musicdisc_255.hca", ""},
            {"11_bgm_musicdisc_256.hca", ""},
            {"11_bgm_musicdisc_257.hca", ""},
            {"11_bgm_musicdisc_258.hca", ""},
            {"11_bgm_musicdisc_259.hca", ""},
            {"11_bgm_musicdisc_260.hca", ""},
            {"11_bgm_musicdisc_261.hca", ""},
            {"11_bgm_musicdisc_262.hca", ""},
            {"11_bgm_musicdisc_263.hca", ""},
            {"11_bgm_musicdisc_264.hca", ""},
            {"11_bgm_musicdisc_265.hca", ""},
            {"11_bgm_musicdisc_266.hca", ""},
            {"11_bgm_musicdisc_267.hca", ""},
            {"11_bgm_musicdisc_268.hca", ""},
            {"11_bgm_musicdisc_269.hca", ""},
            {"11_bgm_musicdisc_270.hca", ""},
            {"11_bgm_musicdisc_271.hca", ""},
            {"11_bgm_musicdisc_272.hca", ""},
            {"11_bgm_musicdisc_273.hca", ""},
            {"11_bgm_musicdisc_274.hca", ""},
            {"11_bgm_musicdisc_275.hca", ""},
            {"11_bgm_musicdisc_276.hca", ""},
            {"11_bgm_musicdisc_277.hca", ""},
            {"11_bgm_musicdisc_278.hca", ""},
            {"11_bgm_musicdisc_279.hca", ""},
            {"11_bgm_musicdisc_280.hca", ""},
            {"11_bgm_musicdisc_281.hca", ""},
            {"11_bgm_musicdisc_282.hca", ""},
            {"11_bgm_musicdisc_283.hca", ""},
            {"11_bgm_musicdisc_284.hca", ""},
            {"11_bgm_musicdisc_285.hca", ""},
            {"11_bgm_musicdisc_286.hca", ""},
            {"11_bgm_musicdisc_287.hca", ""},
            {"11_bgm_musicdisc_288.hca", ""},
            {"11_bgm_musicdisc_289.hca", ""},
            {"11_bgm_musicdisc_290.hca", ""},
            {"11_bgm_musicdisc_291.hca", ""},
            {"11_bgm_musicdisc_292.hca", ""},
            {"11_bgm_musicdisc_293.hca", ""},
            {"11_bgm_musicdisc_294.hca", ""},
            {"11_bgm_musicdisc_295.hca", ""},
            {"11_bgm_musicdisc_296.hca", ""},
            {"11_bgm_musicdisc_297.hca", ""},
            {"11_bgm_musicdisc_298.hca", ""},
            {"11_bgm_musicdisc_299.hca", ""},
            {"11_bgm_musicdisc_300.hca", ""},
            {"11_bgm_musicdisc_301.hca", ""},
            {"11_bgm_musicdisc_302.hca", ""},
            {"11_bgm_musicdisc_303.hca", ""},
            {"11_bgm_musicdisc_304.hca", ""},
            {"11_bgm_musicdisc_305.hca", ""},
            {"11_bgm_musicdisc_306.hca", ""},
            {"11_bgm_musicdisc_307.hca", ""},
            {"11_bgm_musicdisc_308.hca", ""},
            {"11_bgm_musicdisc_309.hca", ""},
            {"11_bgm_musicdisc_310.hca", ""},
            {"11_bgm_musicdisc_311.hca", ""},
            {"11_bgm_musicdisc_312.hca", ""},
            {"11_bgm_musicdisc_313.hca", ""},
            {"11_bgm_musicdisc_314.hca", ""},
            {"11_bgm_musicdisc_315.hca", ""},
            {"11_bgm_musicdisc_316.hca", ""},
            {"11_bgm_musicdisc_317.hca", ""},
            {"11_bgm_musicdisc_318.hca", ""},
            {"11_bgm_musicdisc_319.hca", ""},
            {"11_bgm_musicdisc_320.hca", ""},
            {"11_bgm_musicdisc_321.hca", ""},
            {"11_bgm_musicdisc_322.hca", ""},
            {"11_bgm_musicdisc_323.hca", ""},
            {"11_bgm_musicdisc_324.hca", ""},
            {"11_bgm_musicdisc_325.hca", ""},
            {"11_bgm_musicdisc_326.hca", ""},
            {"11_bgm_musicdisc_327.hca", ""},
            {"11_bgm_musicdisc_328.hca", ""},
            {"11_bgm_musicdisc_329.hca", ""},
            {"11_bgm_musicdisc_330.hca", ""},
            {"11_bgm_musicdisc_331.hca", ""},
            {"11_bgm_musicdisc_332.hca", ""},
            {"11_bgm_musicdisc_333.hca", ""},
            {"11_bgm_musicdisc_334_lobby.hca", ""},
            {"11_bgm_musicdisc_334.hca", ""},
            {"11_bgm_musicdisc_335.hca", ""},
            {"11_bgm_musicdisc_336.hca", ""},
            {"11_bgm_musicdisc_337.hca", ""},
            {"11_bgm_musicdisc_338.hca", ""},
            {"11_bgm_musicdisc_339.hca", ""},
            {"11_bgm_musicdisc_340.hca", ""},
            {"11_bgm_musicdisc_341.hca", ""},
            {"11_bgm_musicdisc_342.hca", ""},
            {"11_bgm_musicdisc_343.hca", ""},
            {"11_bgm_musicdisc_344.hca", ""},
            {"11_bgm_musicdisc_345.hca", ""},
            {"11_bgm_musicdisc_346.hca", ""},
            {"11_bgm_musicdisc_347.hca", ""},
            {"11_bgm_musicdisc_348.hca", ""},
            {"11_bgm_musicdisc_349.hca", ""},
            {"11_bgm_musicdisc_350.hca", ""},
            {"11_bgm_musicdisc_351.hca", ""},
            {"11_bgm_musicdisc_352.hca", ""},
            {"11_bgm_musicdisc_353.hca", ""},
            {"11_bgm_musicdisc_354.hca", ""},
            {"11_bgm_musicdisc_355.hca", ""},
            {"11_bgm_musicdisc_356.hca", ""},
            {"11_bgm_musicdisc_357.hca", ""},
            {"11_bgm_musicdisc_358.hca", ""},
            {"11_bgm_musicdisc_359.hca", ""},
            {"11_bgm_musicdisc_360.hca", ""},
            {"11_bgm_musicdisc_361.hca", ""},
            {"11_bgm_musicdisc_362.hca", ""},
            {"11_bgm_musicdisc_363.hca", ""},
            {"11_bgm_musicdisc_364.hca", ""},
            {"11_bgm_musicdisc_365.hca", ""},
            {"11_bgm_musicdisc_366.hca", ""},
            {"11_bgm_musicdisc_367.hca", ""},
            {"11_bgm_musicdisc_368.hca", ""},
            {"11_bgm_musicdisc_369.hca", ""},
            {"11_bgm_musicdisc_370.hca", ""},
            {"11_bgm_musicdisc_371.hca", ""},
            {"11_bgm_musicdisc_372.hca", ""},
            {"11_bgm_musicdisc_373.hca", ""},
            {"11_bgm_musicdisc_374.hca", ""},
            {"11_bgm_musicdisc_375.hca", ""},
            {"11_bgm_musicdisc_381.hca", ""},
            {"11_bgm_musicdisc_382.hca", ""},
            {"11_bgm_musicdisc_383.hca", ""},
            {"11_bgm_musicdisc_385.hca", ""},
            {"11_bgm_musicdisc_386.hca", ""},
            {"11_bgm_musicdisc_388.hca", ""},
            {"11_bgm_musicdisc_389.hca", ""},
            {"11_bgm_musicdisc_391.hca", ""},
            {"11_bgm_musicdisc_392.hca", ""},
            {"11_bgm_musicdisc_393.hca", ""},
            {"11_bgm_musicdisc_394.hca", ""},
            {"11_bgm_musicdisc_395.hca", ""},
            {"11_bgm_musicdisc_396.hca", ""},
            {"11_bgm_musicdisc_397.hca", ""},
            {"11_bgm_musicdisc_398.hca", ""},
            {"11_bgm_musicdisc_399.hca", ""},
            {"11_bgm_musicdisc_403.hca", ""},
            {"11_bgm_musicdisc_404.hca", ""},
            {"11_bgm_musicdisc_405.hca", ""},
            {"11_bgm_musicdisc_406.hca", ""},
            {"11_bgm_musicdisc_407.hca", ""},
            {"11_bgm_musicdisc_408.hca", ""},
            {"11_bgm_musicdisc_409.hca", ""},
            {"11_bgm_musicdisc_410.hca", ""},
            {"11_bgm_musicdisc_412.hca", ""},
            {"11_bgm_musicdisc_413.hca", ""},
            {"11_bgm_musicdisc_414.hca", ""},
            {"11_bgm_musicdisc_415.hca", ""},
            {"11_bgm_musicdisc_416.hca", ""},
            {"11_bgm_musicdisc_417.hca", ""},
            {"11_bgm_musicdisc_418.hca", ""},
            {"11_bgm_musicdisc_419.hca", ""},
            {"11_bgm_musicdisc_420.hca", ""},
            {"11_bgm_musicdisc_421.hca", ""},
            {"11_bgm_musicdisc_422.hca", ""},
            {"11_bgm_musicdisc_423.hca", ""},
            {"11_bgm_musicdisc_424.hca", ""},
            {"11_bgm_musicdisc_425.hca", ""},
            {"11_bgm_musicdisc_426.hca", ""},
            {"11_bgm_musicdisc_427.hca", ""},
            {"11_bgm_musicdisc_428.hca", ""},
            {"11_bgm_musicdisc_429.hca", ""},
            {"11_bgm_musicdisc_430.hca", ""},
            {"11_bgm_musicdisc_431.hca", ""},
            {"11_bgm_musicdisc_432.hca", ""},
            {"11_bgm_musicdisc_433.hca", ""},
            {"11_bgm_musicdisc_434.hca", ""},
            {"11_bgm_musicdisc_435.hca", ""},
            {"11_bgm_musicdisc_436.hca", ""},
            {"11_bgm_musicdisc_437.hca", ""},
            {"11_bgm_musicdisc_438.hca", ""},
            {"11_bgm_musicdisc_439.hca", ""},
            {"11_bgm_musicdisc_440.hca", ""},
            {"11_bgm_musicdisc_441.hca", ""},
            {"11_bgm_musicdisc_442.hca", ""},
            {"11_bgm_musicdisc_443.hca", ""},
            {"11_bgm_musicdisc_444.hca", ""},
            {"11_bgm_musicdisc_445.hca", ""},
            {"11_bgm_musicdisc_446.hca", ""},
            {"11_bgm_musicdisc_447.hca", ""},
            {"11_bgm_musicdisc_448.hca", ""},
            {"11_bgm_musicdisc_449.hca", ""},
            {"11_bgm_musicdisc_450.hca", ""},
            {"11_bgm_musicdisc_451.hca", ""},
            {"11_bgm_musicdisc_452.hca", ""},
            {"11_bgm_musicdisc_453.hca", ""},
            {"11_bgm_musicdisc_454.hca", ""},
            {"11_bgm_musicdisc_455.hca", ""},
            {"11_bgm_musicdisc_456.hca", ""},
            {"11_bgm_musicdisc_457.hca", ""},
            {"11_bgm_musicdisc_458.hca", ""},
            {"11_bgm_musicdisc_459.hca", ""},
            {"11_bgm_musicdisc_460.hca", ""},
            {"11_bgm_musicdisc_461.hca", ""},
            {"11_bgm_musicdisc_462.hca", ""},
            {"11_bgm_musicdisc_463.hca", ""},
            {"11_bgm_musicdisc_464.hca", ""},
            {"11_bgm_musicdisc_465.hca", ""},
            {"11_bgm_musicdisc_466.hca", ""},
            {"11_bgm_musicdisc_467.hca", ""},
            {"11_bgm_musicdisc_468.hca", ""},
            {"11_bgm_musicdisc_469.hca", ""},
            {"11_bgm_musicdisc_470.hca", ""},
            {"11_bgm_musicdisc_471.hca", ""},
            {"11_bgm_musicdisc_472.hca", ""},
            {"11_bgm_musicdisc_473.hca", ""},
            {"11_bgm_musicdisc_519.hca", ""},
            {"11_bgm_musicdisc_520.hca", ""},
            {"11_bgm_musicdisc_521.hca", ""},
            {"11_bgm_musicdisc_522.hca", ""},
            {"11_bgm_musicdisc_523.hca", ""},
            {"11_bgm_musicdisc_524.hca", ""},
            {"11_bgm_musicdisc_525.hca", ""},
            {"11_bgm_musicdisc_526.hca", ""},
            {"11_bgm_musicdisc_527.hca", ""},
            {"11_bgm_musicdisc_528.hca", ""},
            {"11_bgm_musicdisc_529.hca", ""},
            {"11_bgm_musicdisc_530.hca", ""},
            {"11_bgm_musicdisc_531.hca", ""},
            {"11_bgm_musicdisc_532.hca", ""},
            {"11_bgm_musicdisc_533.hca", ""},
            {"11_bgm_musicdisc_534.hca", ""},
            {"11_bgm_musicdisc_535.hca", ""},
            {"11_bgm_musicdisc_536.hca", ""},
            {"11_bgm_musicdisc_537.hca", ""},
            {"11_bgm_musicdisc_538.hca", ""},
            {"11_bgm_musicdisc_539.hca", ""},
            {"11_bgm_musicdisc_540.hca", ""},
            {"11_bgm_musicdisc_541.hca", ""},
            {"11_bgm_musicdisc_542.hca", ""},
            {"11_bgm_musicdisc_543.hca", ""},
            {"11_bgm_musicdisc_544.hca", ""},
            {"11_bgm_musicdisc_545.hca", ""},
            {"11_bgm_musicdisc_546.hca", ""},
            {"11_bgm_musicdisc_547.hca", ""},
            {"11_bgm_musicdisc_548.hca", ""},
            {"11_bgm_musicdisc_549.hca", ""},
            {"11_bgm_musicdisc_550.hca", ""},
            {"11_bgm_musicdisc_551.hca", ""},
            {"11_bgm_musicdisc_552.hca", ""},
            {"11_bgm_musicdisc_553.hca", ""},
            {"11_bgm_musicdisc_554.hca", ""},
            {"11_bgm_musicdisc_555.hca", ""},
            {"11_bgm_musicdisc_556.hca", ""},
            {"11_bgm_musicdisc_557.hca", ""},
            {"11_bgm_musicdisc_558.hca", ""},
            {"11_bgm_musicdisc_559.hca", ""},
            {"11_bgm_musicdisc_560.hca", ""},
            {"11_bgm_musicdisc_561.hca", ""},
            {"11_bgm_musicdisc_562.hca", ""},
            {"11_bgm_musicdisc_563.hca", ""},
            {"11_bgm_musicdisc_565.hca", ""},
            {"11_bgm_musicdisc_566.hca", ""},
            {"11_bgm_musicdisc_567.hca", ""},
            {"11_bgm_musicdisc_568.hca", ""},
            {"11_bgm_musicdisc_569.hca", ""},
            {"11_bgm_musicdisc_570.hca", ""},
            {"11_bgm_musicdisc_571.hca", ""},
            {"11_bgm_musicdisc_572.hca", ""},
            {"11_bgm_musicdisc_573.hca", ""},
            {"11_bgm_musicdisc_574.hca", ""},
            {"11_bgm_musicdisc_575.hca", ""},
            {"11_bgm_musicdisc_576.hca", ""},
            {"11_bgm_musicdisc_578.hca", ""},
            {"11_bgm_musicdisc_579.hca", ""},
            {"11_bgm_musicdisc_580.hca", ""},
            {"11_bgm_musicdisc_581.hca", ""},
            {"11_bgm_musicdisc_583.hca", ""},
            {"11_bgm_musicdisc_584.hca", ""},
            {"11_bgm_musicdisc_585.hca", ""},
            {"11_bgm_musicdisc_586.hca", ""},
            {"11_bgm_musicdisc_587.hca", ""},
            {"11_bgm_musicdisc_589.hca", ""},
            {"11_bgm_musicdisc_590.hca", ""},
            {"11_bgm_musicdisc_591.hca", ""},
            {"11_bgm_musicdisc_592.hca", ""},
            {"11_bgm_musicdisc_593.hca", ""},
            {"11_bgm_musicdisc_594.hca", ""},
            {"11_bgm_musicdisc_595.hca", ""},
            {"11_bgm_musicdisc_603.hca", ""},
            {"11_bgm_musicdisc_606.hca", ""},
            {"11_bgm_musicdisc_607.hca", ""},
            {"11_bgm_musicdisc_608.hca", ""},
            {"11_bgm_musicdisc_609.hca", ""},
            {"11_bgm_musicdisc_610.hca", ""},
            {"11_bgm_musicdisc_611.hca", ""},
            {"11_bgm_musicdisc_612.hca", ""},
            {"11_bgm_musicdisc_613.hca", ""},
            {"11_bgm_musicdisc_614.hca", ""},
            {"11_bgm_musicdisc_615.hca", ""},
            {"11_bgm_musicdisc_616.hca", ""},
            {"11_bgm_musicdisc_617.hca", ""},
            {"11_bgm_musicdisc_618.hca", ""},
            {"11_bgm_musicdisc_619.hca", ""},
            {"11_bgm_musicdisc_620.hca", ""},
            {"11_bgm_musicdisc_621.hca", ""},
            {"11_bgm_musicdisc_622.hca", ""},
            {"11_bgm_musicdisc_623.hca", ""},
            {"11_bgm_musicdisc_624.hca", ""},
            {"11_bgm_musicdisc_625.hca", ""},
            {"11_bgm_musicdisc_626.hca", ""},
            {"11_bgm_musicdisc_629.hca", ""},
            {"11_bgm_musicdisc_630.hca", ""},
            {"11_bgm_musicdisc_634.hca", ""},
            {"11_bgm_musicdisc_635.hca", ""},
            {"11_bgm_musicdisc_636.hca", ""},
            {"11_bgm_musicdisc_637.hca", ""},
            {"11_bgm_musicdisc_638.hca", ""},
            {"11_bgm_musicdisc_639.hca", ""},
            {"11_bgm_musicdisc_640.hca", ""},
            {"11_bgm_musicdisc_641.hca", ""},
            {"11_bgm_musicdisc_642.hca", ""},
            {"11_bgm_musicdisc_643.hca", ""},
            {"11_bgm_musicdisc_644.hca", ""},
            {"11_bgm_musicdisc_645.hca", ""},
            {"11_bgm_musicdisc_646.hca", ""},
            {"11_bgm_musicdisc_647.hca", ""},
            {"11_bgm_musicdisc_648.hca", ""},
            {"11_bgm_musicdisc_649.hca", ""},
            {"11_bgm_musicdisc_650.hca", ""},
            {"11_bgm_musicdisc_651.hca", ""},
            {"11_bgm_musicdisc_652.hca", ""},
            {"11_bgm_musicdisc_653.hca", ""},
            {"11_bgm_musicdisc_654.hca", ""},
            {"11_bgm_musicdisc_655.hca", ""},
            {"11_bgm_musicdisc_656.hca", ""},
            {"11_bgm_musicdisc_658.hca", ""},
            {"11_bgm_musicdisc_660.hca", ""},
            {"11_bgm_musicdisc_661.hca", ""},
            {"11_bgm_musicdisc_662.hca", ""},
            {"11_bgm_musicdisc_663.hca", ""},
            {"11_bgm_musicdisc_664.hca", ""},
            {"11_bgm_musicdisc_665.hca", ""},
            {"11_bgm_musicdisc_666.hca", ""},
            {"11_bgm_musicdisc_667.hca", ""},
            {"11_bgm_musicdisc_668.hca", ""},
            {"11_bgm_musicdisc_669.hca", ""},
            {"11_bgm_musicdisc_670.hca", ""},
            {"11_bgm_musicdisc_671.hca", ""},
            {"11_bgm_musicdisc_672.hca", ""},
            {"11_bgm_musicdisc_673.hca", ""},
            {"11_bgm_musicdisc_674.hca", ""},
            {"11_bgm_musicdisc_675.hca", ""},
            {"11_bgm_musicdisc_676.hca", ""},
            {"11_bgm_musicdisc_677.hca", ""},
            {"11_bgm_musicdisc_678.hca", ""},
            {"11_bgm_musicdisc_679.hca", ""},
            {"11_bgm_musicdisc_683.hca", ""},
            {"11_bgm_musicdisc_685.hca", ""},
            {"11_bgm_musicdisc_686.hca", ""},
            {"11_bgm_musicdisc_687.hca", ""},
            {"11_bgm_musicdisc_688.hca", ""},
            {"11_bgm_musicdisc_689.hca", ""},
            {"11_bgm_musicdisc_690.hca", ""},
            {"11_bgm_musicdisc_691.hca", ""},
            {"11_bgm_musicdisc_692.hca", ""},
            {"11_bgm_musicdisc_693.hca", ""},
            {"11_bgm_musicdisc_694.hca", ""},
            {"11_bgm_musicdisc_695.hca", ""},
            {"11_bgm_musicdisc_696.hca", ""},
            {"11_bgm_musicdisc_697.hca", ""},
            {"11_bgm_musicdisc_698.hca", ""},
            {"11_bgm_musicdisc_699.hca", ""},
            {"11_bgm_musicdisc_700.hca", ""},
            {"11_bgm_musicdisc_701.hca", ""},
            {"11_bgm_musicdisc_702.hca", ""},
            {"11_bgm_musicdisc_703.hca", ""},
            {"11_bgm_musicdisc_704.hca", ""},
            {"11_bgm_musicdisc_705.hca", ""},
            {"11_bgm_musicdisc_706.hca", ""},
            {"11_bgm_musicdisc_707.hca", ""},
            {"11_bgm_musicdisc_708.hca", ""},
            {"11_bgm_musicdisc_709.hca", ""},
            {"11_bgm_musicdisc_710.hca", ""},
            {"11_bgm_musicdisc_711.hca", ""},
            {"11_bgm_musicdisc_713.hca", ""},
            {"11_bgm_musicdisc_714.hca", ""},
            {"11_bgm_musicdisc_715.hca", ""},
            {"11_bgm_musicdisc_716.hca", ""},
            {"11_bgm_musicdisc_717.hca", ""},
            {"11_bgm_musicdisc_718.hca", ""},
            {"11_bgm_musicdisc_719.hca", ""},
            {"11_bgm_musicdisc_800.hca", ""},
            {"11_bgm_musicdisc_801.hca", ""},
            {"11_bgm_musicdisc_802.hca", ""},
            {"11_bgm_musicdisc_803.hca", ""},
            {"11_bgm_musicdisc_804.hca", ""},
            {"11_bgm_musicdisc_805.hca", ""},
            {"11_bgm_musicdisc_806.hca", ""},
            {"11_bgm_musicdisc_807.hca", ""},
            {"11_bgm_musicdisc_808.hca", ""},
            {"11_bgm_musicdisc_809.hca", ""},
            {"11_bgm_musicdisc_810.hca", ""},
            {"11_bgm_musicdisc_811.hca", ""},
            {"11_bgm_musicdisc_812.hca", ""},
            {"11_bgm_musicdisc_813.hca", ""},
            {"11_bgm_musicdisc_814.hca", ""},
            {"11_bgm_musicdisc_815.hca", ""},
            {"11_bgm_musicdisc_816.hca", ""},
            {"11_bgm_musicdisc_817.hca", ""},
            {"11_bgm_musicdisc_818.hca", ""},
            {"11_bgm_musicdisc_819.hca", ""},
            {"11_bgm_musicdisc_820.hca", ""},
            {"11_bgm_musicdisc_821.hca", ""},
            {"11_bgm_musicdisc_822.hca", ""},
            {"11_bgm_musicdisc_823.hca", ""},
            {"11_bgm_musicdisc_824.hca", ""},
            {"11_bgm_musicdisc_825.hca", ""},
            {"11_bgm_musicdisc_826.hca", ""},
            {"11_bgm_musicdisc_827.hca", ""},
            {"11_bgm_musicdisc_828.hca", ""},
            {"11_bgm_musicdisc_829.hca", ""},
            {"11_bgm_musicdisc_830.hca", ""},
            {"11_bgm_musicdisc_831.hca", ""},
            {"11_bgm_musicdisc_832.hca", ""},
            {"11_bgm_musicdisc_833.hca", ""},
            {"11_bgm_musicdisc_834.hca", ""},
            {"11_bgm_musicdisc_835.hca", ""},
            {"11_bgm_musicdisc_836.hca", ""},
            {"11_bgm_musicdisc_837.hca", ""},
            {"11_bgm_musicdisc_838.hca", ""},
            {"11_bgm_musicdisc_842.hca", ""},
            {"11_bgm_musicdisc_843.hca", ""},
            {"11_bgm_musicdisc_844.hca", ""},
            {"11_bgm_musicdisc_846.hca", ""},
            {"11_bgm_musicdisc_847.hca", ""},
            {"11_bgm_musicdisc_848.hca", ""},
            {"11_bgm_musicdisc_849.hca", ""},
            {"11_bgm_musicdisc_850.hca", ""},
            {"11_bgm_musicdisc_851.hca", ""},
            {"11_bgm_musicdisc_852.hca", ""},
            {"11_bgm_musicdisc_853.hca", ""},
            {"11_bgm_musicdisc_854.hca", ""},
            {"11_bgm_musicdisc_855.hca", ""},
            {"11_bgm_musicdisc_902.hca", ""},
            {"11_bgm_musicdisc_903.hca", ""},
            {"11_bgm_musicdisc_922.hca", ""},
            {"11_bgm_musicdisc_937.hca", ""},
            {"11_bgm_musicdisc_959.hca", ""},
            {"11_bgm_musicdisc_991.hca", ""},
            {"11_bgm_musicdisc_996.hca", ""},
            {"11_bgm_musicdisc_997.hca", ""},
            {"11_bgm_myroom_streamloop.hca", ""},
            {"11_bgm_P_CITY.hca", ""},
            {"11_bgm_pkv_btf.hca", ""},
            {"11_bgm_pkv_btfr.hca", ""},
            {"11_bgm_pkv_btt.hca", ""},
            {"11_bgm_pkv_btv.hca", ""},
            {"11_bgm_pkv_lobby.hca", ""},
            {"11_bgm_pop_vocal_un012170.hca", ""},
            {"11_bgm_pop_vocal_un012520.hca", ""},
            {"11_bgm_pso2_theme_long.hca", ""},
            {"11_bgm_pso2op_long_kouhan_bench.hca", ""},
            {"11_bgm_pso2op_long_kouhan.hca", ""},
            {"11_bgm_quest_arks01.hca", ""},
            {"11_bgm_quest_arks02.hca", ""},
            {"11_bgm_quest_arks03.hca", ""},
            {"11_bgm_quest_copy406.hca", ""},
            {"11_bgm_quest_copy413.hca", ""},
            {"11_bgm_quest_copy417.hca", ""},
            {"11_bgm_quest_copy423.hca", ""},
            {"11_bgm_quest_copy424.hca", ""},
            {"11_bgm_quest_copy425.hca", ""},
            {"11_bgm_quest_copy426.hca", ""},
            {"11_bgm_quest_copy437.hca", ""},
            {"11_bgm_quest_copy438.hca", ""},
            {"11_bgm_quest_copy439.hca", ""},
            {"11_bgm_quest_copy576.hca", ""},
            {"11_bgm_quest_copy592.hca", ""},
            {"11_bgm_quest_copy828.hca", ""},
            {"11_bgm_quest_I19_1.hca", ""},
            {"11_bgm_quest_I19_2.hca", ""},
            {"11_bgm_quest_w18_1.hca", ""},
            {"11_bgm_quest_w18_2.hca", ""},
            {"11_bgm_seasonevent_june.hca", ""},
            {"11_bgm_st660_1and2.hca", ""},
            {"11_bgm_st660_3.hca", ""},
            {"11_bgm_vocal_ballade_demo.hca", ""},
            {"11_bgm_vocal_ballade_short.hca", ""},
            {"11_bgm_vocal_pop_demo.hca", ""},
            {"movie_mothership2.hca", ""},
            {"WAVE4_stream.hca", ""},
            {"WoW_forLOOP.hca", ""},
        };

        public static Dictionary<string, string> classicAdaptiveNames = new Dictionary<string, string>()
        {
            {"mu_11_bgm_01.ice", "Mother earth of dishonesty,Mother earth of dishonesty"},
            {"mu_11_bgm_02.ice", "The kink in the wind and the way,The kink in the wind and the way"},
            {"mu_11_bgm_03.ice", "Empty space out of control,Empty space out of control"},
            {"mu_11_bgm_04.ice", "Revolution to the origin,Revolution to the origin"},
            {"mu_11_bgm_05.ice", "A longing to ancient times,A longing to ancient times"},
            {"mu_11_bgm_06.ice", "Tricktrack,Tricktrack"},
            {"mu_11_bgm_07.ice", "Jungle,Jungle"},
            {"mu_11_bgm_08.ice", "Abysmal ball,Abysmal ball"},
            {"mu_11_bgm_09.ice", "Nostalgia in solitude"},
            {"mu_11_bgm_10.ice", "Entry into the crater,Entry into the crater"},
            {"mu_11_bgm_11.ice", "Underworld,Underworld"},
            {"mu_11_bgm_2001.ice", ""},
            {"mu_11_bgm_2002.ice", ""},
            {"mu_11_bgm_2003.ice", ""},
            {"mu_11_bgm_2004.ice", ""},
            {"mu_11_bgm_act_md.ice", ""},
            {"mu_11_bgm_act.ice", "アークストレインニング,Arks Training"},
            {"mu_11_bgm_aks_md.ice", ""},
            {"mu_11_bgm_amu_hall.ice", "カジノ,Casino"},
            {"mu_11_bgm_amu_shooter.ice", "カジノメセタンシューター,Casino Mesetan Shooter"},
            {"mu_11_bgm_ancient.ice", ""},
            {"mu_11_bgm_ba.ice", ""},
            {"mu_11_bgm_bat.ice", ""},
            {"mu_11_bgm_bb1.ice", ""},
            {"mu_11_bgm_bb2.ice", ""},
            {"mu_11_bgm_beach.ice", ""},
            {"mu_11_bgm_before.ice", "ダークファルス・エルダ ワープエリア,Dark Falz Elder Warp Area"},
            {"mu_11_bgm_before2.ice", ""},
            {"mu_11_bgm_before2o.ice", ""},
            {"mu_11_bgm_before3.ice", ""},
            {"mu_11_bgm_before4.ice", ""},
            {"mu_11_bgm_before5.ice", ""},
            {"mu_11_bgm_before6_md.ice", ""},
            {"mu_11_bgm_before6.ice", ""},
            {"mu_11_bgm_before7.ice", ""},
            {"mu_11_bgm_before8.ice", ""},
            {"mu_11_bgm_bonus.ice", ""},
            {"mu_11_bgm_boss_aph.ice", ""},
            {"mu_11_bgm_boss_apz_md.ice", ""},
            {"mu_11_bgm_boss_apz.ice", ""},
            {"mu_11_bgm_boss_arh.ice", ""},
            {"mu_11_bgm_boss_arousal.ice", ""},
            {"mu_11_bgm_boss_bdf_md.ice", ""},
            {"mu_11_bgm_boss_bdf.ice", ""},
            {"mu_11_bgm_boss_bdfo_md.ice", ""},
            {"mu_11_bgm_boss_bdfo.ice", ""},
            {"mu_11_bgm_boss_bdragon.ice", ""},
            {"mu_11_bgm_boss_braid.ice", ""},
            {"mu_11_bgm_boss_centaurus.ice", ""},
            {"mu_11_bgm_boss_crystaldragon.ice", "クォーツ・ドラゴン,Quartz Dragon"},
            {"mu_11_bgm_boss_deepsea.ice", ""},
            {"mu_11_bgm_boss_df2.ice", ""},
            {"mu_11_bgm_boss_df3.ice", "ダークファルス・エルダ,Dark Falz Elder"},
            {"mu_11_bgm_boss_dfb.ice", ""},
            {"mu_11_bgm_boss_dfman.ice", ""},
            {"mu_11_bgm_boss_dfman2_md.ice", ""},
            {"mu_11_bgm_boss_dfman2.ice", ""},
            {"mu_11_bgm_boss_dfman3_1.ice", ""},
            {"mu_11_bgm_boss_dfman3_2.ice", ""},
            {"mu_11_bgm_boss_dft.ice", ""},
            {"mu_11_bgm_boss_dr.ice", ""},
            {"mu_11_bgm_boss_dragon.ice", ""},
            {"mu_11_bgm_boss_drt.ice", ""},
            {"mu_11_bgm_boss_edf1_md.ice", ""},
            {"mu_11_bgm_boss_edf1.ice", ""},
            {"mu_11_bgm_boss_edf2_md.ice", ""},
            {"mu_11_bgm_boss_edf2.ice", ""},
            {"mu_11_bgm_boss_eg.ice", ""},
            {"mu_11_bgm_boss_fdf.ice", ""},
            {"mu_11_bgm_boss_fg.ice", ""},
            {"mu_11_bgm_boss_flt.ice", ""},
            {"mu_11_bgm_boss_gdragon.ice", ""},
            {"mu_11_bgm_boss_gg.ice", ""},
            {"mu_11_bgm_boss_km_md.ice", ""},
            {"mu_11_bgm_boss_km.ice", ""},
            {"mu_11_bgm_boss_kohri.ice", ""},
            {"mu_11_bgm_boss_luther.ice", ""},
            {"mu_11_bgm_boss_machine.ice", ""},
            {"mu_11_bgm_boss_mdfch1.ice", ""},
            {"mu_11_bgm_boss_mdfch2.ice", ""},
            {"mu_11_bgm_boss_mdfch3.ice", ""},
            {"mu_11_bgm_boss_mdfch4.ice", ""},
            {"mu_11_bgm_boss_mdfcl1.ice", ""},
            {"mu_11_bgm_boss_mdfcl2.ice", ""},
            {"mu_11_bgm_boss_mge_md.ice", ""},
            {"mu_11_bgm_boss_mge.ice", ""},
            {"mu_11_bgm_boss_nge_md.ice", ""},
            {"mu_11_bgm_boss_nge.ice", ""},
            {"mu_11_bgm_boss_of.ice", ""},
            {"mu_11_bgm_boss_oph_md.ice", ""},
            {"mu_11_bgm_boss_oph1.ice", ""},
            {"mu_11_bgm_boss_oph2.ice", ""},
            {"mu_11_bgm_boss_oph3.ice", ""},
            {"mu_11_bgm_boss_ophs.ice", ""},
            {"mu_11_bgm_boss_opr_f1_md.ice", ""},
            {"mu_11_bgm_boss_opr_f2_md.ice", ""},
            {"mu_11_bgm_boss_opr_f3_md.ice", ""},
            {"mu_11_bgm_boss_opr_f4_md.ice", ""},
            {"mu_11_bgm_boss_opr_f5_md.ice", ""},
            {"mu_11_bgm_boss_opr_f6_md.ice", ""},
            {"mu_11_bgm_boss_opr.ice", ""},
            {"mu_11_bgm_boss_panther.ice", ""},
            {"mu_11_bgm_boss_pd1.ice", ""},
            {"mu_11_bgm_boss_pd1before.ice", ""},
            {"mu_11_bgm_boss_pd2.ice", ""},
            {"mu_11_bgm_boss_pd2before.ice", ""},
            {"mu_11_bgm_boss_sfg.ice", ""},
            {"mu_11_bgm_boss_sh1.ice", ""},
            {"mu_11_bgm_boss_sh2.ice", ""},
            {"mu_11_bgm_boss_spider.ice", ""},
            {"mu_11_bgm_boss_teodoll.ice", ""},
            {"mu_11_bgm_boss_tt.ice", ""},
            {"mu_11_bgm_boss_tt2.ice", ""},
            {"mu_11_bgm_boss_ultcave.ice", ""},
            {"mu_11_bgm_boss_ultcyp.ice", ""},
            {"mu_11_bgm_boss_wafu1.ice", ""},
            {"mu_11_bgm_boss_wafu2.ice", ""},
            {"mu_11_bgm_boss_wanigame.ice", ""},
            {"mu_11_bgm_boss_wdragon.ice", ""},
            {"mu_11_bgm_boss_wdragon2.ice", ""},
            {"mu_11_bgm_boss_wopal3.ice", ""},
            {"mu_11_bgm_boss_zaco.ice", ""},
            {"mu_11_bgm_bst_01_md.ice", ""},
            {"mu_11_bgm_bst_01.ice", ""},
            {"mu_11_bgm_bst_02_md.ice", ""},
            {"mu_11_bgm_bst_02.ice", ""},
            {"mu_11_bgm_bst_03_md.ice", ""},
            {"mu_11_bgm_bst_03.ice", ""},
            {"mu_11_bgm_bsth1_01.ice", ""},
            {"mu_11_bgm_bsth1_02.ice", ""},
            {"mu_11_bgm_bsth1_03.ice", ""},
            {"mu_11_bgm_bsth2_01.ice", ""},
            {"mu_11_bgm_bsth2_02.ice", ""},
            {"mu_11_bgm_bsth2_03.ice", ""},
            {"mu_11_bgm_bstk_01.ice", ""},
            {"mu_11_bgm_bstk_02.ice", ""},
            {"mu_11_bgm_bstk_03.ice", ""},
            {"mu_11_bgm_bv_before.ice", ""},
            {"mu_11_bgm_bv_event.ice", ""},
            {"mu_11_bgm_bv_first.ice", ""},
            {"mu_11_bgm_bv_second_md.ice", ""},
            {"mu_11_bgm_bv_second.ice", ""},
            {"mu_11_bgm_cafe_frost.ice", ""},
            {"mu_11_bgm_cafe_n.ice", ""},
            {"mu_11_bgm_cafe_night.ice", ""},
            {"mu_11_bgm_cafe_sea.ice", ""},
            {"mu_11_bgm_cafe_wf.ice", ""},
            {"mu_11_bgm_cave.ice", ""},
            {"mu_11_bgm_cg_area_md.ice", ""},
            {"mu_11_bgm_cg_area.ice", ""},
            {"mu_11_bgm_cg_lobby.ice", ""},
            {"mu_11_bgm_charamake.ice", ""},
            {"mu_11_bgm_city.ice", ""},
            {"mu_11_bgm_clb19_1.ice", ""},
            {"mu_11_bgm_clear.ice", ""},
            {"mu_11_bgm_darkernest.ice", ""},
            {"mu_11_bgm_deepsea.ice", ""},
            {"mu_11_bgm_defence_1_1.ice", ""},
            {"mu_11_bgm_defence_1_2.ice", ""},
            {"mu_11_bgm_defence_1_3.ice", ""},
            {"mu_11_bgm_defence_1_4.ice", ""},
            {"mu_11_bgm_defence_1_5.ice", ""},
            {"mu_11_bgm_defence_1_6.ice", ""},
            {"mu_11_bgm_defence_1.ice", ""},
            {"mu_11_bgm_defence_mdan.ice", ""},
            {"mu_11_bgm_defence_mdap.ice", ""},
            {"mu_11_bgm_defence_mdn.ice", ""},
            {"mu_11_bgm_defence_mdp.ice", ""},
            {"mu_11_bgm_defence2_md1.ice", ""},
            {"mu_11_bgm_defence2_md2.ice", ""},
            {"mu_11_bgm_defence2.ice", ""},
            {"mu_11_bgm_defence261.ice", ""},
            {"mu_11_bgm_defence262.ice", ""},
            {"mu_11_bgm_defence263.ice", ""},
            {"mu_11_bgm_desert.ice", ""},
            {"mu_11_bgm_dragonland.ice", ""},
            {"mu_11_bgm_e5_005.ice", ""},
            {"mu_11_bgm_elobby.ice", ""},
            {"mu_11_bgm_flt_before.ice", ""},
            {"mu_11_bgm_flt1.ice", ""},
            {"mu_11_bgm_flt2.ice", ""},
            {"mu_11_bgm_flt3_2.ice", ""},
            {"mu_11_bgm_flt3.ice", ""},
            {"mu_11_bgm_forest.ice", ""},
            {"mu_11_bgm_frozen.ice", ""},
            {"mu_11_bgm_gear.ice", ""},
            {"mu_11_bgm_gmm.ice", ""},
            {"mu_11_bgm_inst_1.ice", "Our Fighting (マイルームの楽器),Our Fighting MyRoom Instruments"},
            {"mu_11_bgm_inst_2.ice", ""},
            {"mu_11_bgm_kmbefore_md.ice", ""},
            {"mu_11_bgm_kmbefore.ice", ""},
            {"mu_11_bgm_kuro.ice", ""},
            {"mu_11_bgm_lillipa3.ice", ""},
            {"mu_11_bgm_mdfcl.ice", ""},
            {"mu_11_bgm_mgr.ice", ""},
            {"mu_11_bgm_mothership_a.ice", ""},
            {"mu_11_bgm_mothership_b.ice", ""},
            {"mu_11_bgm_msx.ice", ""},
            {"mu_11_bgm_myroom.ice", ""},
            {"mu_11_bgm_neo.ice", ""},
            {"mu_11_bgm_nod_md.ice", ""},
            {"mu_11_bgm_nod.ice", ""},
            {"mu_11_bgm_nodf.ice", ""},
            {"mu_11_bgm_non_md.ice", ""},
            {"mu_11_bgm_non.ice", ""},
            {"mu_11_bgm_nonf.ice", ""},
            {"mu_11_bgm_not.ice", ""},
            {"mu_11_bgm_of.ice", ""},
            {"mu_11_bgm_opf.ice", ""},
            {"mu_11_bgm_opft.ice", ""},
            {"mu_11_bgm_orgel_1.ice", ""},
            {"mu_11_bgm_pk_area.ice", ""},
            {"mu_11_bgm_pk_draw.ice", ""},
            {"mu_11_bgm_pk_lobby.ice", ""},
            {"mu_11_bgm_pk_lose.ice", ""},
            {"mu_11_bgm_pk_md.ice", ""},
            {"mu_11_bgm_pk_result.ice", ""},
            {"mu_11_bgm_pk_win.ice", ""},
            {"mu_11_bgm_pkv_before.ice", ""},
            {"mu_11_bgm_pkv_draw.ice", ""},
            {"mu_11_bgm_pkv_lose.ice", ""},
            {"mu_11_bgm_pkv_win.ice", ""},
            {"mu_11_bgm_rps_md.ice", ""},
            {"mu_11_bgm_sanctuary.ice", ""},
            {"mu_11_bgm_shaft.ice", ""},
            {"mu_11_bgm_slb.ice", ""},
            {"mu_11_bgm_sv1.ice", ""},
            {"mu_11_bgm_sv2.ice", ""},
            {"mu_11_bgm_sv3.ice", ""},
            {"mu_11_bgm_system.ice", ""},
            {"mu_11_bgm_team.ice", ""},
            {"mu_11_bgm_tkd.ice", ""},
            {"mu_11_bgm_tkdb.ice", ""},
            {"mu_11_bgm_tkdt_md.ice", ""},
            {"mu_11_bgm_tkdt.ice", ""},
            {"mu_11_bgm_tkn.ice", ""},
            {"mu_11_bgm_tknb.ice", ""},
            {"mu_11_bgm_tknt.ice", ""},
            {"mu_11_bgm_tn.ice", ""},
            {"mu_11_bgm_ug.ice", ""},
            {"mu_11_bgm_ult_cave_quest.ice", ""},
            {"mu_11_bgm_ult_cave.ice", ""},
            {"mu_11_bgm_ult_cyp.ice", ""},
            {"mu_11_bgm_ult_forest.ice", ""},
            {"mu_11_bgm_ult_lillipa3.ice", ""},
            {"mu_11_bgm_ult_shaft.ice", ""},
            {"mu_11_bgm_ult_shaft2.ice", ""},
            {"mu_11_bgm_unknown.ice", ""},
            {"mu_11_bgm_urban.ice", ""},
            {"mu_11_bgm_v2_1.ice", ""},
            {"mu_11_bgm_v2_2.ice", ""},
            {"mu_11_bgm_w17.ice", ""},
            {"mu_11_bgm_wafu_i.ice", ""},
            {"mu_11_bgm_wafu1.ice", ""},
            {"mu_11_bgm_wopal3.ice", ""},
            {"mu_11_bgm_wt_md.ice", ""},
            {"mu_11_bgm_wt.ice", ""},
            {"mu_11_bgm_xh2ancient.ice", ""},
            {"mu_11_bgm_xh2beach.ice", ""},
            {"mu_11_bgm_xh2deepsea.ice", ""},
            {"mu_11_bgm_xh2desert.ice", ""},
            {"mu_11_bgm_xh2forest.ice", ""},
            {"mu_11_bgm_xh2frozen.ice", ""},
            {"mu_11_bgm_xh2kuro.ice", ""},
            {"mu_11_bgm_xh2wafu1.ice", ""},
            {"mu_11_bgm_xh2wopal3_md1.ice", ""},
            {"mu_11_bgm_xh2wopal3_md2.ice", ""},
            {"mu_11_bgm_xh2wopal3.ice", ""},
        };
    }
}
