namespace AquaModelLibrary.Data.PSO2.Constants
{
    public static class StageFilenames
    {
        public static string effectPath = "stage/effect/"; //Used only for a few late game areas in classic
        public static string radarPath = "stage/radar/"; //In NGS, only exists for trainia, though unused as of writing
        public static string skyboxPath = "stage/weather/";
        public static string stageOut = @"Stage\";
        public static string lnAreaTemplateCommon = "stage/ln_area_template_common.ice"; //LPS files inside tell the game what layout models exist etc.
        public static string lnAreaTemplateCommonReboot = "stage/ln_area_template_common_reboot.ice"; //LPS files inside tell the game what layout models exist etc. for NGS. Only applicable for areas like Trainia, open worlds use a different system

        public static string charCreatorRoom = "sn_0000_chararea1.ice";

        //Some names may differ on areas and objects. Notably, my room rooms.
        //Immense thanks to Arredoval for this
        public static Dictionary<int, string> areaNames = new Dictionary<int, string>()
        {
            {0007,"Shader Playground (デバッグ),Shader Playground (Debug)" },
            {0008,"_,_" },
            {0009,"Playground (デバッグ),Playground (Debug)" },
            {0010,"青,Blue" },
            {0011,"_,_" },
            {0012,"_,_" },
            {0013,"_,_" },
            {0014,"_,_" },
            {0015,"プロトタイプ ハルファ,Prototype Halpha" },
            {0016,"プロトタイプ ハルファ,Prototype Halpha" },
            {0017,"プロトタイプ ハルファ,Prototype Halpha" },
            {0018,"プロトタイプ ハルファ,Prototype Halpha" },
            {0019,"プロトタイプ ハルファ,Prototype Halpha" },
            {0020,"プロトタイプ ハルファ,Prototype Halpha" },
            {0050,"_,_" },
            {0100,"ロッビ (1st版),Lobby (1st Demo)" },
            {0101,"ロッビ (アルファ),Lobby (Alpha)" },
            {0102,"ロッビ (Ep1),Lobby (Ep1)" },
            {0103,"チャレンジモードロッビ,Challenge Mode Lobby" },
            {0104,"カジノ,Casino" },
            {0105,"カジノメセタンシューター,Casino Mesetan Shooter" },
            {0106,"ロッビ (Ep3),Lobby (Ep3)" },
            {0107,"船橋,Ship Bridge" },
            {0108,"バトルモードロッビ,Battle Mode Lobby" },
            {0109,"ロッビ (Ep3 コピ),Lobby (Ep3 Copy)" },
            {0150,"キャンプシップ,Campship" },
            {0160,"フランカ’s カフェ,Franka's Cafe" },
            {0161,"海のカフェ,Franka's Cafe (Coast)" },
            {0162,"夜のカフェ,Franka's Cafe (Night View)" },
            {0163,"雪のカフェ,Franka's Cafe (Tundra)" },
            {0164,"桜のカフェ,Franka's Cafe (Shironia)" },
            {0170,"病室／カットシーンの水の背景,Hospital Room／Cutscene Water Background" },
            {0171,"Ep3 クレジット,Ep3 Credits" },
            {0172,"Ep4 オープニング,Ep4 Opening Sequence" },
            {0173,"外宇宙 (Ep5),Outer Space (Ep5 Rift)" },
            {0174,"カシナ／カットシーンの水の背景,Kashina Central Core／Cutscene Water Background" },
            {0175,"_,_" },
            {0176,"クロマキー,Chroma Key" },
            {0177,"船橋 (コピ),Ship Bridge (Copy)" },
            {0180,"チームルーム (初期ルーム),Team Room (Default)" },
            {0181,"チームルーム (森林),Team Room (Forest)" },
            {0182,"チームルーム (温泉),Team Room (Hot Springs)" },
            {0183,"チームルーム (砂漠),Team Room (Desert)" },
            {0184,"チームルーム (海岸),Team Room (Coast)" },
            {0185,"チームルーム (夜景),Team Room (Night View)" },
            {0186,"チームルーム (凍土),Team Room (Tundra)" },
            {0187,"チームルーム (浮遊),Team Room (Floating)" },
            {0188,"チームルーム (和風),Team Room (Japanese-Style)" },
            {0189,"チームルーム (水上遺跡),Team Room (Water Ruins)" },
            {0190,"チームルーム (パイオニア2),Team Room (Pioneer II)" },
            {0191,"チームルーム (妖精の尻尾のギルド),Team Room (Fairy Tail Guild)" },
            {0192,"チームルーム (東京),Team Room (Tokyo)" },
            {0193,"チームルーム (戦艦),Team Room (Battleship)" },
            {0194,"チームルーム (月面),Team Room (Moon Surface)" },
            {0195,"チームルーム (渓流),Team Room (Mountain Stream)" },
            {0210,"市街地 (1st版),Urban Streets(1st Demo)" },
            {0211,"市街地 (エリア１),Urban Streets (Area 1)" },
            {0212,"市街地 (エリア２),Urban Streets (Area 2)" },
            {0213,"星芒喰らう闇の狂宴 (ボス),Dark Revelry Consumes Starlight (Boss)" },
            {0214,"第６使徒殲滅作戦,Operation To Eliminate the 6th Angel" },
            {0220,"ダーカーの巣窟 (エリア１),Darker Nest (Area 1)" },
            {0221,"ダーカーの巣窟 (エリア２),Darker Nest (Area 2)" },
            {0230,"マザーシップ (エリア１),Mothership (Area 1)" },
            {0231,"マザーシップ (エリア２),Mothership (Area 2)" },
            {0232,"マザーシップ (シャオ),Mothership (Xiao)" },
            {0233,"マザーシップ (シバ),Mothership (Shiva)" },
            {0240,"内的宇宙,Double's Inner Universe" },
            {0290,"市街地 (ボス),Urban Streets (Boss)" },
            {0291,"ダークファルス・ルーサー,Dark Falz Loser" },
            {0292,"マザーシップ (シバ),Mothership (Shiva)" },
            {0310,"森林 (エリア１／ボス),Forest (Area 1／Boss)" },
            {0311,"森林 (エリア２),Forest (Area 2)" },
            {0320,"凍土 (エリア２／ボス),Tundra (Area 2／Boss)" },
            {0321,"凍土 (エリア１),Tundra (Area 1)" },
            {0330,"遺跡,Ruins" },
            {0390,"ダークファルスアーム,Dark Falz Arms" },
            {0391,"ダークファルスエルダ,Dark Falz Elder" },
            {0392,"ダークファルスダブル,Dark Falz Double" },
            {0393,"深遠なる闇,Profound Darkness" },
            {0410,"砂漠 (エリア２／ボス),Desert (Area 2／Boss)" },
            {0411,"砂漠 (エリア１),Desert (Area 1)" },
            {0420,"地下坑道 (エリア１),Underground Shafts (Area 1)" },
            {0421,"地下坑道 (エリア２),Underground Shafts (Area 2)" },
            {0430,"採掘場跡 (エリア１),Abandoned Mine (Area 1)" },
            {0431,"採掘場跡 (エリア２／ボス),Abandoned Mine (Area 2／Boss)" },
            {0490,"地下坑道 (ボス),Underground Shafts (Boss)" },
            {0491,"砂漠 (ビッグヴァーダー１),Desert (Big Varder 1)" },
            {0492,"砂漠 (ビッグヴァーダー２),Desert (Big Varder 2)" },
            {0493,"砂漠 (ビッグヴァーダー３),Desert (Big Varder 3)" },
            {0494,"砂漠 (ビッグヴァーダー４),Desert (Big Varder 4)" },
            {0510,"火山洞窟 (エリア１),Volcanic Caves (Area 1)" },
            {0511,"火山洞窟 (エリア２／ボス),Volcanic Caves (Area 2／Boss)" },
            {0520,"浮遊大陸 (エリア２),Floating Continent (Area 2)" },
            {0521,"浮遊大陸 (エリア１),Floating Continent (Area 1)" },
            {0530,"龍祭壇,Dragon Altar" },
            {0590,"浮遊大陸 (ボス),Floating Continent (Boss)" },
            {0591,"クローム・ドラゴン,Chrome Dragon" },
            {0610,"海岸 (エリア１),Coast (Area 1)" },
            {0611,"海岸 (エリア２),Coast (Area 2)" },
            {0620,"海底 (エリア１),Seabed (Area 1)" },
            {0621,"海底 (エリア２／ボス),Seabed (Area 2／Boss)" },
            {0630,"浮上施設,Floating Facility" },
            {0690,"海岸 (ボス),Coast (Boss)" },
            {0710,"白ノ領域,Daybreak Province" },
            {0711,"天地を葬る災禍の凶神 (エリア１),,Death, Destroyer of Worlds (Area 1)" },
            {0720,"黒ノ領域,Nightfall Province" },
            {0790,"白ノ領域 (ボス),Daybreak Province (Boss)" },
            {0791,"マガツ印鑑,Magatsu Seal" },
            {0792,"幽世,Kakuriyo" },
            {0810,"東京,Tokyo" },
            {0820,"ラスベガス (パリホテル),Las Vegas (Paris Hotel)" },
            {0821,"ラスベガス (ニューヨーク・ニューヨーク・ホテル),Las Vegas (New York New York Hotel)" },
            {0822,"ラスベガス (フリーモントストリート),Las Vegas (Fremont Street)" },
            {0830,"月駆ける幻創の母 (エリア１),Esca Falz Mother (Area 1)" },
            {0831,"衛星・月 放棄施設,The Moon Abandoned Facility" },
            {0832,"月駆ける幻創の母 (エリア２),Esca Falz Mother (Area 2)" },
            {0833,"衛星・月 地下中枢施設,The Moon Underground Nexus" },
            {0834,"衛星・月 地下中枢施設 (ボス),The Moon Underground Nexus (Boss)" },
            {0840,"新世を成す幻創の造神 (エリア１),Deus Esca (Area 1)" },
            {0841,"新世を成す幻創の造神 (エリア２),Deus Esca (Area 2)" },
            {0842,"惑星・地球アースガイド本部地下,Earth - Earth Guide Headquarters Basement Level" },
            {0843,"惑星・地球 幻創園,Earth - Phantasm Park" },
            {0844,"新世を成す幻創の造神 (エリア３),Deus Esca (Area 3)" },
            {0890,"東京 (ボス),Tokyo (Boss)" },
            {0891,"幻創戦艦・大和 (エリア１),Phantom Battleship Yamato (Area 1)" },
            {0892,"幻創戦艦・大和 (エリア２),Phantom Battleship Yamato (Area 2)" },
            {0893,"東京ドミトリー／浴場,Tokyo Dormitory／Bathhouse" },
            {0894,"東京陸上競技場,Tokyo Athletic Field" },
            {0895,"惑星・地球アースガイド本部,Earth - Earth Guide Headquarters" },
            {0896,"幻創戦艦・大和 (ストリ),Phantom Battleship Yamato (Story)" },
            {0897,"東京校入学式 (夜),Tokyo School Entrance (Night)" },
            {0898,"ロンドン,London" },
            {0900,"パラレルエリア;　森林,Parallel Area; Forest" },
            {0901,"パラレルエリア;　凍土,Parallel Area; Tundra" },
            {0902,"パラレルエリア;　砂漠,Parallel Area; Desert" },
            {0903,"パラレルエリア;　海岸,Parallel Area; Coast" },
            {0904,"ガル・ダ・バル,Gal Da Val" },
            {0905,"The Black Shroud; Urth's Fount,The Black Shroud; Urth's Fount" },
            {0906,"パラレルエリア;　森林 (ボーナスクエスト),Parallel Area; Forest (Bonus Quest)" },
            {0907,"____ 古塔 (エルゼリオン),____ Old Tower (Eruzerion)" },
            {1000,"シーナリーパス・市街地,Scenery Pass; City" },
            {1001,"シーナリーパス・森林,Scenery Pass; Forest" },
            {1002,"シーナリーパス・宇宙,Scenery Pass; Space" },
            {1003,"シーナリーパス・砂漠,Scenery Pass; Desert" },
            {1004,"シーナリーパス・凍土,Scenery Pass; Tundra" },
            {1005,"シーナリーパス・火山洞窟,Scenery Pass; Volcanic Caves" },
            {1006,"シーナリーパス・浮遊大陸,Scenery Pass; Float. Continent" },
            {1007,"シーナリーパス・遺跡,Scenery Pass; Ruins" },
            {1008,"シーナリーパス・地下坑道,Scenery Pass; Undergrnd Shafts" },
            {1009,"シーナリーパス・龍祭壇,Scenery Pass; Dragon Altar" },
            {1010,"シーナリーパス・海岸,Scenery Pass; Coast" },
            {1011,"シーナリーパス・採掘場跡,Scenery Pass; Abandoned Mine" },
            {1012,"シーナリーパス・海底,Scenery Pass; Seabed" },
            {1013,"シーナリーパス・Mシップ,Scenery Pass; Mothership" },
            {1014,"シーナリーパス・巨人,Scenery Pass; Titan" },
            {1015,"シーナリーパス・UBW,Scenery Pass; Unlimited Blade Works" },
            {1016,"シーナリーパス・白ノ領域,Scenery Pass; Daybreak Prov." },
            {1017,"シーナリーパス・浮上施設,Scenery Pass; Floating Facility" },
            {1018,"シーナリーパス・ヤマト,Scenery Pass; Yamato" },
            {1019,"シーナリーパス・黒ノ領域,Scenery Pass; Nightfall Province" },
            {1020,"シーナリーパス・内的宇宙,Scenery Pass; Inner Universe" },
            {1024,"シーナリーパス・幽世,Scenery Pass; Kakuriyo" },
            {1500,"ミニルーム,Mini Room" },
            {2000,"極限訓練：森林と龍,Extreme Training; Forest and Dragons" },
            {2001,"極限訓練：凍土と機甲,Extreme Training; Tundra & Automata" },
            {2002,"極限訓練：遺跡と海王,Extreme Training; Ruins & Oceanids" },
            {2010,"練習クエスト,Practice Quest" },
            {2100,"採掘基地防衛戦 (１-３),Mining Base Defense (1-3)" },
            {2110,"採掘基地防衛戦 (4),Mining Base Defense (4)" },
            {2200,"壊世調査：ナベリウス,Corruption Investigation; Naverius" },
            {2210,"壊世調査：リリーパ,Corruption Investigation; Lilipa" },
            {2220,"壊世調査：遺跡,Corruption Investigation; Ruins" },
            {2230,"壊世調査：アムドゥスキア,Corruption Investigation; Amduskia" },
            {2231,"惑星アムドゥスキア磁獄龍墓最奥・入口,Amduskia - Hellwyrm's Grave Inner Sanctum Entrance" },
            {2232,"カシナ　コア,Kashina Core" },
            {2300,"マガツ (エリア１),Magatsu (Area 1)" },
            {2301,"_,_" },
            {2310,"マガツ (エリア２),Magatsu (Area 2)" },
            {2320,"天地を葬る災禍の凶神 (エリア２),Death, Destroyer of Worlds (Area 2)"},
            {3000,"バトルアリーナ; 森林,Battle Arena; Forest" },
            {3001,"バトルアリーナ; 火山洞窟,Battle Arena; Caves" },
            {3002,"バトルアリーナ; 東京,Battle Arena; Tokyo" },
            {3003,"_,_" },
            {3004,"バトルアリーナ; 森林 (雨),Battle Arena; Forest (Rain)" },
            {3005,"バトルアリーナ; 火山洞窟 (夜),Battle Arena; Volcanic Caves (Night)" },
            {3100,"クエント プレーリー,Cuento Prairie" },
            {3101,"イス＝アルス 国堺,Ys Artia Border" },
            {3102,"クエント 中央プレーリー,Cuento Central Prairie" },
            {3110,"クエント 荒れ地,Cuent Wasteland" },
            {3120,"魔神城戦：不尽の狂気,Castrum Demonica; Madness" },
            {3121,"クエント峡谷,Cuento Canyon Caldera" },
            {3130,"クエント城跡,Cuento Castle Ruins" },
            {3140,"幻惑の森,Bewitched Woods" },
            {3141,"エルガマスカレーダ,Elga Masquerade" },
            {3150,"エピック砂漠,Epyk Desert" },
            {3160,"イス＝アルス 城下町／実験室,Ys Artia Castle Town and Laboratory" },
            {3161,"イス＝アルスキャピタル／エンブレムの部屋,Ys Artia Capital and Emblem Chamber" },
            {3170,"地底を染めし女王の悪夢 (エリア１),Queen's Nightmare; Earth Depths (Area 1)" },
            {3171,"地底を染めし女王の悪夢 (エリア２),Queen's Nightmare; Earth Depths (Area 2)" },
            {3180,"エピック首都圏 (城),Epyk Capital City (Castle)" },
            {3181,"エピック首都圏,Epyk Capital City" },
            {3182,"東砦・北砦・南砦,East Fort, North Fort, and South Fort" },
            {3183,"クエントキャニオン内部,Cuento Canyon Interior" },
            {3184,"ルイーザの湖畔,Lakeside of Luisa" },
            {3188,"黒き繭 内部,Inside the Dark Cocoon" },
            {3189,"オラクル外宇宙,Oracle Space" },
            {3190,"クエント王都玉座の間,Cuento Royal Capital Throne Room" },
            {3191,"オメガ南市,Omega Southern City" },
            {3192,"ネオクエント王都,Neo Cuento Royal Capital" },
            {3193,"クエント民兵隊,Cuento Militia Camp" },
            {3194,"ヴェルン御座所,Weyland Throne Room" },
            {3195,"ヴェルン南村,Weyland Souther Village" },
            {3196,"オメガダークファルス・ルーサー,Omega Dark Falz Loser" },
            {3197,"クエント王都 (夜),Cuento Royal Capital (Night)" },
            {3198,"ルーサーの研究施設,Luther's Research Facility" },
            {3199,"ルイーザの湖畔,Lakeside of Luisa" },
            {3200,"オラクル宇宙,Oracle Sector" },
            {3201,"_,_" },
            {3202,"破滅の艦隊 セクター3（戦艦解体編）,Armada of Demise Sector 3 (Battleship Demolition)" },
            {3203,"_,_" },
            {3204,"_,_" },
            {3210,"艦隊迎撃戦：味方救援,Fleet Intercept; Allied Relief" },
            {3211,"艦隊迎撃戦：敵艦襲撃,Fleet Intercept; Enemy Ship Assault" },
            {3220,"_,_"},
            {3221,"アルマダ・バトルスフィア待機場所,Armada Battlesphere Waiting Area" },
            {3230,"アルマダ・バトルスフィア内部,Armada Battlesphere Interior" },
            {3240,"破滅の艦隊 セクター3（首都圏侵攻作戦）,Armada of Demise Sector 3 (Capital Ship Invasion)" },
            {3250,"虚無より睨む原初の闇 (エリア１),Primordial Darkness (Area 1)" },
            {3251,"虚無より睨む原初の闇 (エリア２),Primordial Darkness (Area 2)"},
            {3260,"マザーシップ コア(シバ),Mothership Core (Shiva)" },
            {3290,"アークスシップ司令部, Arks Ship Command Center" },
            {3291,"A.I.S.開発室,A.I.S. Development Room" },
            {5000,"ハルファ,Halpha" },
            {5001,"ハルファ (エアリオタウン),Halpha (Aelio Town)" },
            {5100,"トレイニア,Trainia" },
            {5101,"トレイニア,Trainia" },
            {6000,"_,_" },
            {9000,"_,_" },
        };

        public static Dictionary<int, string> areaNamesIllegalPathChars = new Dictionary<int, string>()
        {
            {0007,"Shader Playground (デバッグ),Shader Playground (Debug)" },
            {0008,"?,?" },
            {0009,"Playground (デバッグ),Playground (Debug)" },
            {0010,"? 青,? Blue" },
            {0011,"?,?" },
            {0012,"?,?" },
            {0013,"?,?" },
            {0014,"?,?" },
            {0015,"プロトタイプ ハルファ,Prototype Halpha" },
            {0016,"プロトタイプ ハルファ,Prototype Halpha" },
            {0017,"プロトタイプ ハルファ,Prototype Halpha" },
            {0018,"プロトタイプ ハルファ,Prototype Halpha" },
            {0019,"プロトタイプ ハルファ,Prototype Halpha" },
            {0020,"プロトタイプ ハルファ,Prototype Halpha" },
            {0050,"?,?" },
            {0100,"ロッビ (1st版),Lobby (1st Demo)" },
            {0101,"ロッビ (アルファ),Lobby (Alpha)" },
            {0102,"ロッビ (Ep1),Lobby (Ep1)" },
            {0103,"チャレンジモードロッビ,Challenge Mode Lobby" },
            {0104,"カジノ,Casino" },
            {0105,"カジノメセタンシューター,Casino Mesetan Shooter" },
            {0106,"ロッビ (Ep3),Lobby (Ep3)" },
            {0107,"船橋,Ship Bridge" },
            {0108,"バトルモードロッビ,Battle Mode Lobby" },
            {0109,"ロッビ (Ep3 コピ),Lobby (Ep3 Copy)" },
            {0150,"キャンプシップ,Campship" },
            {0160,"フランカ’s カフェ,Franka's Cafe" },
            {0161,"海のカフェ,Franka's Cafe (Coast)" },
            {0162,"夜のカフェ,Franka's Cafe (Night View)" },
            {0163,"雪のカフェ,Franka's Cafe (Tundra)" },
            {0164,"桜のカフェ,Franka's Cafe (Shironia)" },
            {0170,"病室/カットシーンの水の背景,Hospital Room/Cutscene Water Background" },
            {0171,"Ep3 クレジット,Ep3 Credits" },
            {0172,"Ep4 オープニング,Ep4 Opening Sequence" },
            {0173,"外宇宙 (Ep5),Outer Space (Ep5 Rift)" },
            {0174,"カシナ/カットシーンの水の背景,Kashina Central Core/Cutscene Water Background" },
            {0175,"?,?" },
            {0176,"クロマキー,Chroma Key" },
            {0177,"船橋 (コピ),Ship Bridge (Copy)" },
            {0180,"チームルーム (初期ルーム),Team Room (Default)" },
            {0181,"チームルーム (森林),Team Room (Forest)" },
            {0182,"チームルーム (温泉),Team Room (Hot Springs)" },
            {0183,"チームルーム (砂漠),Team Room (Desert)" },
            {0184,"チームルーム (海岸),Team Room (Coast)" },
            {0185,"チームルーム (夜景),Team Room (Night View)" },
            {0186,"チームルーム (凍土),Team Room (Tundra)" },
            {0187,"チームルーム (浮遊),Team Room (Floating)" },
            {0188,"チームルーム (和風),Team Room (Japanese-Style)" },
            {0189,"チームルーム (水上遺跡),Team Room (Water Ruins)" },
            {0190,"チームルーム (パイオニア2),Team Room (Pioneer II)" },
            {0191,"チームルーム (妖精の尻尾のギルド),Team Room (Fairy Tail Guild)" },
            {0192,"チームルーム (東京),Team Room (Tokyo)" },
            {0193,"チームルーム (戦艦),Team Room (Battleship)" },
            {0194,"チームルーム (月面),Team Room (Moon Surface)" },
            {0195,"チームルーム (渓流),Team Room (Mountain Stream)" },
            {0210,"市街地 (1st版),Urban Streets(1st Demo)" },
            {0211,"市街地 (エリア１),Urban Streets (Area 1)" },
            {0212,"市街地 (エリア２),Urban Streets (Area 2)" },
            {0213,"星芒喰らう闇の狂宴 (ボス),Dark Revelry Consumes Starlight (Boss)" },
            {0214,"第６使徒殲滅作戦,Operation To Eliminate the 6th Angel" },
            {0220,"ダーカーの巣窟 (エリア１),Darker Nest (Area 1)" },
            {0221,"ダーカーの巣窟 (エリア２),Darker Nest (Area 2)" },
            {0230,"マザーシップ (エリア１),Mothership (Area 1)" },
            {0231,"マザーシップ (エリア２),Mothership (Area 2)" },
            {0232,"マザーシップ (シャオ),Mothership (Xiao)" },
            {0233,"マザーシップ (シバ),Mothership (Shiva)" },
            {0240,"内的宇宙,Double's Inner Universe" },
            {0290,"市街地 (ボス),Urban Streets (Boss)" },
            {0291,"ダークファルス・ルーサー,Dark Falz Loser" },
            {0292,"マザーシップ (シバ),Mothership (Shiva)" },
            {0310,"森林 (エリア１/ボス),Forest (Area 1/Boss)" },
            {0311,"森林 (エリア２),Forest (Area 2)" },
            {0320,"凍土 (エリア２/ボス),Tundra (Area 2/Boss)" },
            {0321,"凍土 (エリア１),Tundra (Area 1)" },
            {0330,"遺跡,Ruins" },
            {0390,"ダークファルスアーム,Dark Falz Arms" },
            {0391,"ダークファルスエルダ,Dark Falz Elder" },
            {0392,"ダークファルスダブル,Dark Falz Double" },
            {0393,"深遠なる闇,Profound Darkness" },
            {0410,"砂漠 (エリア２/ボス),Desert (Area 2/Boss)" },
            {0411,"砂漠 (エリア１),Desert (Area 1)" },
            {0420,"地下坑道 (エリア１),Underground Shafts (Area 1)" },
            {0421,"地下坑道 (エリア２),Underground Shafts (Area 2)" },
            {0430,"採掘場跡 (エリア１),Abandoned Mine (Area 1)" },
            {0431,"採掘場跡 (エリア２/ボス),Abandoned Mine (Area 2/Boss)" },
            {0490,"地下坑道 (ボス),Underground Shafts (Boss)" },
            {0491,"砂漠 (ビッグヴァーダー１),Desert (Big Varder 1)" },
            {0492,"砂漠 (ビッグヴァーダー２),Desert (Big Varder 2)" },
            {0493,"砂漠 (ビッグヴァーダー３),Desert (Big Varder 3)" },
            {0494,"砂漠 (ビッグヴァーダー４),Desert (Big Varder 4)" },
            {0510,"火山洞窟 (エリア１),Volcanic Caves (Area 1)" },
            {0511,"火山洞窟 (エリア２/ボス),Volcanic Caves (Area 2/Boss)" },
            {0520,"浮遊大陸 (エリア２),Floating Continent (Area 2)" },
            {0521,"浮遊大陸 (エリア１),Floating Continent (Area 1)" },
            {0530,"龍祭壇,Dragon Altar" },
            {0590,"浮遊大陸 (ボス),Floating Continent (Boss)" },
            {0591,"クローム・ドラゴン,Chrome Dragon" },
            {0610,"海岸 (エリア１),Coast (Area 1)" },
            {0611,"海岸 (エリア２),Coast (Area 2)" },
            {0620,"海底 (エリア１),Seabed (Area 1)" },
            {0621,"海底 (エリア２/ボス),Seabed (Area 2/Boss)" },
            {0630,"浮上施設,Floating Facility" },
            {0690,"海岸 (ボス),Coast (Boss)" },
            {0710,"白ノ領域,Daybreak Province" },
            {0711,"天地を葬る災禍の凶神 (エリア１),,Death, Destroyer of Worlds (Area 1)" },
            {0720,"黒ノ領域,Nightfall Province" },
            {0790,"白ノ領域 (ボス),Daybreak Province (Boss)" },
            {0791,"マガツ印鑑,Magatsu Seal" },
            {0792,"幽世,Kakuriyo" },
            {0810,"東京,Tokyo" },
            {0820,"ラスベガス (パリホテル),Las Vegas (Paris Hotel)" },
            {0821,"ラスベガス (ニューヨーク・ニューヨーク・ホテル),Las Vegas (New York New York Hotel)" },
            {0822,"ラスベガス (フリーモントストリート),Las Vegas (Fremont Street)" },
            {0830,"月駆ける幻創の母 (エリア１),Esca Falz Mother (Area 1)" },
            {0831,"衛星・月 放棄施設,The Moon Abandoned Facility" },
            {0832,"月駆ける幻創の母 (エリア２),Esca Falz Mother (Area 2)" },
            {0833,"衛星・月 地下中枢施設,The Moon Underground Nexus" },
            {0834,"衛星・月 地下中枢施設 (ボス),The Moon Underground Nexus (Boss)" },
            {0840,"新世を成す幻創の造神 (エリア１),Deus Esca (Area 1)" },
            {0841,"新世を成す幻創の造神 (エリア２),Deus Esca (Area 2)" },
            {0842,"惑星・地球アースガイド本部地下,Earth - Earth Guide Headquarters Basement Level" },
            {0843,"惑星・地球 幻創園,Earth - Phantasm Park" },
            {0844,"新世を成す幻創の造神 (エリア３),Deus Esca (Area 3)" },
            {0890,"東京 (ボス),Tokyo (Boss)" },
            {0891,"幻創戦艦・大和 (エリア１),Phantom Battleship Yamato (Area 1)" },
            {0892,"幻創戦艦・大和 (エリア２),Phantom Battleship Yamato (Area 2)" },
            {0893,"東京ドミトリー/浴場,Tokyo Dormitory/Bathhouse" },
            {0894,"東京陸上競技場,Tokyo Athletic Field" },
            {0895,"惑星・地球アースガイド本部,Earth - Earth Guide Headquarters" },
            {0896,"幻創戦艦・大和 (ストリ),Phantom Battleship Yamato (Story)" },
            {0897,"東京校入学式 (夜),Tokyo School Entrance (Night)" },
            {0898,"ロンドン,London" },
            {0900,"パラレルエリア:　森林,Parallel Area: Forest" },
            {0901,"パラレルエリア:　凍土,Parallel Area: Tundra" },
            {0902,"パラレルエリア:　砂漠,Parallel Area: Desert" },
            {0903,"パラレルエリア:　海岸,Parallel Area: Coast" },
            {0904,"ガル・ダ・バル,Gal Da Val" },
            {0905,"The Black Shroud: Urth's Fount,The Black Shroud: Urth's Fount" },
            {0906,"パラレルエリア:　森林 (ボーナスクエスト),Parallel Area: Forest (Bonus Quest)" },
            {0907,"???? 古塔 (エルゼリオン),???? Old Tower (Eruzerion)" },
            {1000,"シーナリーパス・市街地,Scenery Pass: City" },
            {1001,"シーナリーパス・森林,Scenery Pass: Forest" },
            {1002,"シーナリーパス・宇宙,Scenery Pass: Space" },
            {1003,"シーナリーパス・砂漠,Scenery Pass: Desert" },
            {1004,"シーナリーパス・凍土,Scenery Pass: Tundra" },
            {1005,"シーナリーパス・火山洞窟,Scenery Pass: Volcanic Caves" },
            {1006,"シーナリーパス・浮遊大陸,Scenery Pass: Float. Continent" },
            {1007,"シーナリーパス・遺跡,Scenery Pass: Ruins" },
            {1008,"シーナリーパス・地下坑道,Scenery Pass: Undergrnd Shafts" },
            {1009,"シーナリーパス・龍祭壇,Scenery Pass: Dragon Altar" },
            {1010,"シーナリーパス・海岸,Scenery Pass: Coast" },
            {1011,"シーナリーパス・採掘場跡,Scenery Pass: Abandoned Mine" },
            {1012,"	シーナリーパス・海底,Scenery Pass: Seabed" },
            {1013,"シーナリーパス・Mシップ,Scenery Pass: Mothership" },
            {1014,"シーナリーパス・巨人,Scenery Pass: Titan" },
            {1015,"シーナリーパス・UBW,Scenery Pass: Unlimited Blade Works" },
            {1016,"	シーナリーパス・白ノ領域,Scenery Pass: Daybreak Prov." },
            {1017,"シーナリーパス・浮上施設,Scenery Pass: Floating Facility" },
            {1018,"シーナリーパス・ヤマト,Scenery Pass: Yamato" },
            {1019,"シーナリーパス・黒ノ領域,Scenery Pass: Nightfall Province" },
            {1020,"シーナリーパス・内的宇宙,Scenery Pass: Inner Universe" },
            {1024,"シーナリーパス・幽世,Scenery Pass: Kakuriyo" },
            {1500,"ミニルーム,Mini Room" },
            {2000,"極限訓練：森林と龍,Extreme Training: Forest and Dragons" },
            {2001,"極限訓練：凍土と機甲,Extreme Training: Tundra & Automata" },
            {2002,"極限訓練：遺跡と海王,Extreme Training: Ruins & Oceanids" },
            {2010,"練習クエスト,Practice Quest" },
            {2100,"採掘基地防衛戦 (１-３),Mining Base Defense (1-3)" },
            {2110,"採掘基地防衛戦 (4),Mining Base Defense (4)" },
            {2200,"壊世調査：ナベリウス,Corruption Investigation: Naverius" },
            {2210,"壊世調査：リリーパ,Corruption Investigation: Lilipa" },
            {2220,"壊世調査：遺跡,Corruption Investigation: Ruins" },
            {2230,"壊世調査：アムドゥスキア,Corruption Investigation: Amduskia" },
            {2231,"惑星アムドゥスキア磁獄龍墓最奥・入口,Amduskia - Hellwyrm's Grave Inner Sanctum Entrance" },
            {2232,"カシナ　コア,Kashina Core" },
            {2300,"マガツ (エリア１),Magatsu (Area 1)" },
            {2301,"?,?" },
            {2310,"マガツ (エリア２),Magatsu (Area 2)" },
            {2320,"天地を葬る災禍の凶神 (エリア２),Death, Destroyer of Worlds (Area 2)"},
            {3000,"バトルアリーナ: 森林,Battle Arena: Forest" },
            {3001,"バトルアリーナ: 火山洞窟,Battle Arena: Caves" },
            {3002,"バトルアリーナ: 東京,Battle Arena: Tokyo" },
            {3003,"?,?" },
            {3004,"バトルアリーナ: 森林 (雨),Battle Arena: Forest (Rain)" },
            {3005,"バトルアリーナ: 火山洞窟 (夜),Battle Arena: Volcanic Caves (Night)" },
            {3100,"クエント プレーリー,Cuento Prairie" },
            {3101,"イス＝アルス 国堺,Ys Artia Border" },
            {3102,"クエント 中央プレーリー,Cuento Central Prairie" },
            {3110,"クエント 荒れ地,Cuent Wasteland" },
            {3120,"魔神城戦：不尽の狂気,Castrum Demonica: Madness" },
            {3121,"クエント峡谷,Cuento Canyon Caldera" },
            {3130,"クエント城跡,Cuento Castle Ruins" },
            {3140,"幻惑の森,Bewitched Woods" },
            {3141,"エルガマスカレーダ,Elga Masquerade" },
            {3150,"エピック砂漠,Epyk Desert" },
            {3160,"イス＝アルス 城下町/実験室,Ys Artia Castle Town and Laboratory" },
            {3161,"イス＝アルスキャピタル/エンブレムの部屋,Ys Artia Capital and Emblem Chamber" },
            {3170,"地底を染めし女王の悪夢 (エリア１),Queen's Nightmare: Earth Depths (Area 1)" },
            {3171,"地底を染めし女王の悪夢 (エリア２),Queen's Nightmare: Earth Depths (Area 2)" },
            {3180,"エピック首都圏 (城),Epyk Capital City (Castle)" },
            {3181,"エピック首都圏,Epyk Capital City" },
            {3182,"東砦・北砦・南砦,East Fort, North Fort, and South Fort" },
            {3183,"クエントキャニオン内部,Cuento Canyon Interior" },
            {3184,"ルイーザの湖畔,Lakeside of Luisa" },
            {3188,"黒き繭 内部,Inside the Dark Cocoon" },
            {3189,"オラクル外宇宙,Oracle Space" },
            {3190,"クエント王都玉座の間,Cuento Royal Capital Throne Room" },
            {3191,"オメガ南市,Omega Southern City" },
            {3192,"ネオクエント王都,Neo Cuento Royal Capital" },
            {3193,"クエント民兵隊,Cuento Militia Camp" },
            {3194,"ヴェルン御座所,Weyland Throne Room" },
            {3195,"ヴェルン南村,Weyland Souther Village" },
            {3196,"オメガダークファルス・ルーサー,Omega Dark Falz Loser" },
            {3197,"クエント王都 (夜),Cuento Royal Capital (Night)" },
            {3198,"ルーサーの研究施設,Luther's Research Facility" },
            {3199,"ルイーザの湖畔,Lakeside of Luisa" },
            {3200,"オラクル宇宙,Oracle Sector" },
            {3201,"?,?" },
            {3202,"破滅の艦隊 セクター3（戦艦解体編）,Armada of Demise Sector 3 (Battleship Demolition)" },
            {3203,"?,?" },
            {3204,"?,?" },
            {3210,"艦隊迎撃戦：味方救援,Fleet Intercept: Allied Relief" },
            {3211,"艦隊迎撃戦：敵艦襲撃,Fleet Intercept: Enemy Ship Assault" },
            {3220,"?,?"},
            {3221,"アルマダ・バトルスフィア待機場所,Armada Battlesphere Waiting Area" },
            {3230,"アルマダ・バトルスフィア内部,Armada Battlesphere Interior" },
            {3240,"破滅の艦隊 セクター3（首都圏侵攻作戦）,Armada of Demise Sector 3 (Capital Ship Invasion)" },
            {3250,"虚無より睨む原初の闇 (エリア１),Primordial Darkness (Area 1)" },
            {3251,"虚無より睨む原初の闇 (エリア２),Primordial Darkness (Area 2)"},
            {3260,"マザーシップ コア(シバ),Mothership Core (Shiva)" },
            {3290,"アークスシップ司令部, Arks Ship Command Center" },
            {3291,"A.I.S.開発室,A.I.S. Development Room" },
            {5000,"ハルファ,Halpha" },
            {5001,"ハルファ (エアリオタウン),Halpha (Aelio Town)" },
            {5100,"トレイニア,Trainia" },
            {5101,"トレイニア,Trainia" },
            {6000,"?,?" },
            {9000,"?,?" },
        };
    }
}
