using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AquaExtras
{
    public static class FilenameConstants
    {
        public static string mgxName = "setting.mgx";
        public static string pbCreatures = "photon_blast/photon_blast_";
        public static string db_vehicle = "vehicle/";
        public static string colorPaletteOut = @"colorPalettes\";
        public static string weaponDir = "item/weapon/";
        public static string baseWeaponString = "it_wp_00_base_";
        public static string weaponString = "it_wp_";
        public static string defaultWeaponString = "it_wp_xxx_";
        //Types for weapon default files (fig, default anims)
        public static List<string> weaponTypes = new List<string>()
        {
            "sword",            //1
            "wiredlance",       //2
            "partisan",         //3
            "twindagger",       //4
            "doublesaber",      //5
            "knuckle",          //6
            "gunslash",         //7
            "assaultrifle",     //8
            "grenadelauncher",  //9
            "twinmachinegun",   //10
            "rod",              //11
            "thalys",           //12
            "wand",             //13
            "ktn",              //14
            "bow",              //15
            "jetboots",         //16
            "dualblade",        //17
            "tact"              //18
        };

        public static List<string> weaponTypesNGS = new List<string>()
        {
            "sword",            //1
            "wiredlance",       //2
            "partisan",         //3
            "twindagger",       //4
            "doublesaber",      //5
            "knuckle",          //6
            "gunslash",         //7
            "rifle",            //8
            "launcher",         //9
            "twinmachinegun",   //10
            "rod",              //11
            "thalys",           //12
            "wand",             //13
            "ktn",              //14
            "bow",              //15
            "jetboots",         //16
            "dualblade",        //17
            "tact"              //18
        };

        //Types for default weapon model files? Dual blade seemingly doesn't have one...
        public static List<string> weaponTypesShort = new List<string>()
        {
            "sw",            //1
            "ln",            //2
            "pa",            //3
            "td",            //4
            "ds",            //5
            "kn",            //6
            "gs",            //7
            "rf",            //8
            "lu",            //9
            "tm",            //10
            "rd",            //11
            "ta",            //12
            "wa",            //13
            "kt",            //14
            "cb",            //15
            "jb",            //16
            null,//"dualblade",     //17 not used?
            "tc"             //18
        };

        public static Dictionary<int, string> swordNames = new Dictionary<int, string>()
        {
            { 001, "ソード,Sword"},
            { 002, "アルバソード,Alba Sword"},
            { 003, "ヴィタソード,Vita Sword"},
            { 004, "ギガッシュ,Gigush"},
            { 005, "アルバギガッシュ,Alba Gigush"},
            { 006, "ヴィタギガッシュ,Vita Gigush"},
            { 007, "ブレイカー,Breaker"},
            { 008, "アルバブレイカー,Alba Breaker"},
            { 009, "ヴィタブレイカー,Vita Breaker"},
            { 010, "クレイモア,Claymore"},
            { 011, "アルバクレイモア,Alba Claymore"},
            { 012, "ヴィタクレイモア,Vita Claymore"},
            { 013, "キャリバー,Calibur"},
            { 014, "アルバキャリバー,Alba Calibur"},
            { 015, "ヴィタキャリバー,Vita Calibur"},
            { 016, "コートエッジ,Coated Edge"},
            { 017, "タルナーダ,Tarnada"},
            { 018, "ラムダアーディロウ,Lambda Ardillo"},
            { 019, "ディオアーディロウ,Dio Ardillo"},
            { 020, "アーディロウ,Ardillo"},
            { 021, "ザックス,Zaxe"},
            { 022, "＊ブラッドサイズ,* Blood Scythe"},
            { 023, "ラストサバイバー,Last Survivor"},
            { 024, "ザンバ,Zamba"},
            { 025, "＊世果・封 (NPC),Yonohate Fu (NPC)"},
            { 026, "＊世果・印 (NPC),Yonohate In (NPC)"},
            { 027, "ドラゴンスレイヤー,Dragon Slayer" },
            { 028, "フォルトゥナ,Fortuna" },
            { 029, "マダムノアマガサ,Madam's Umbrella" },
            { 030, "エリュシオーヌ,Ely-Sion" },
            { 031, "アカツキ,Akatsuki" },
            { 033, "ブリザックス,Blizaxe" },
            { 034, "ブレイザックス,Blazaxe" },
            { 035, "アリスティン,Aristine" },
            { 036, "ディオアリスティン,Dio Aristine" },
            { 037, "ラムダアリスティン,Lambda Aristine" },
            { 038, "イクタチ,Ikutachi" },
            { 039, "ディニアエッジ,Dinia Edge" },
            { 040, "ヴォルスケイル,Vol Scale" },
            { 041, "サディーナエッジ,Sadiena Edge" },
            { 042, "バーンスパーダ,Burn Spada" },
            { 043, "コートエッジD,Coated Edge D" },
            { 044, "スペース・ツナ,Space Tuna"},
            { 045, "トラディシオン／ナハト,Tradicion / Nacht" },
            { 046, "ルインシャルム,Ruin Charm" },
            { 047, "エルダーペイン,Elder Pain" },
            { 048, "スペース・ツナ,Freeze Tuna" },
            { 049, "ルインミラーシ,Ruin Mirage" },
            { 050, "ルイングローム,Ruin Gloam" },
            { 051, "＊レイディアント,* Radiant" },
            { 052, "アーレスソード,Ares Sword" },
            { 053, "紅葉姫,Momijihime" },
            { 054, "フラメブランド,Flamme Brand" },
            { 055, "トレイターリニア,Traitor Linear" },
            { 056, "ザッパーエッジ,Zapper Edge" },
            { 057, "アズロリンガー,Azzurro Ringer" },
            { 058, "ロッソリンガー,Rosso Ringer" },
            { 059, "ヴェルデリンガー,Verde Ringer" },
            { 060, "クルセイドロア,Crusade Lore" },
            { 061, "＊テト・ザ・レオ,* Tet the Leo"},
            { 062, "シャープサイクラー,Sharp Cycler" },
            { 063, "ライトニングエスパーダ,Lightning Espada" },
            { 064, "デイジーチェイン,Daisy Chain" },
            { 065, "＊SW-ティアダウナー,* SW-Teardowner" },
            { 066, "＊スティールハーツ,* Steel Hearts" },
            { 067, "＊ゲイ・ボルク,* Gae Bolg" },
            { 068, "トレイターグリフ,Traitor Glyph" },
            { 069, "トレイター?,Traitor ?" },
            { 070, "ウィングスパーダ,Wing Spada" },
            { 071, "赤のソード,Red Sword" },
            { 072, "青のソード,Blue Sword" },
            { 073, "クラハダチ,Kurahadachi" },
            { 074, "カグダチ,Kagudachi" },
            { 075, "ザッパー?,Zapper ?" },
            { 076, "ザッパー?,Zapper ?" },
            { 077, "＊スマッシュハリセン,* Smash Harisen" },
            { 078, "ウルシハリセン,Urushi Harisen" },
            { 080, "キレートエディア,Chelate Edia" },
            { 081, "グリッドエディア,Grid Edia" },
            { 082, "ファラストエディア,Falast Edia" },
            { 084, "ホーリーツリー,Holy Tree" },
            { 085, "サイレントツリー,Silent Tree" },
            { 086, "ウェーブボード,Wave Board" },
            { 087, "レインボーボード,Rainbow Board" },
            { 088, "＊スペースボード,* Space Board" },
            { 089, "＊錨,* Anchor" },
            { 095, "＊ヒュージカッター,* Huge Cutter" },
            { 096, "＊封印ノダチ,Sealed Nodachi" },
            { 097, "＊ツミキリ,* Tsumikiri" },
            { 098, "＊零織・イザヨイ,* Zero-type Izayoi"},
            { 103, "＊守護女神ノ太刀,* Guardian Goddess's L. Sword"},
            { 104, "＊フロウウェンの大剣,* Flowen's Sword"},
            { 106, "＊ジャンクヤード・ドッグ,* Junkyard Dog"},
            { 107, "＊マグノリアエクレール2,* Magnolia Éclair II"},
            { 110, "＊ローズセイバー,* Rose Saber"},
            { 112, "＊ローズオーナメント,* Rose Ornament"},
            { 114, "キーンサイクラー,Keen Cycler"},
            { 115, "ギアフレイド,Gearfreid" },
            { 116, "バイオグリオン,Bio Glion" },
            { 117, "ライブグリオン,Live Glion" },
            { 118, "ブラッドグリオン,Blood Glion" },
            { 119, "ジェラーテ,Gelate" },
            { 121, "ウェドルエイド,Weddle Aid" },
            { 124, "＊ボードグレイ,* Bode Gray" },
            { 125, "＊ボード ?,* Bode ?"  },
            { 126, "＊ボード ?,* Bode ?"  },
            { 130, "＊約束された勝利の剣,* The Sword of Promised Victory"},
            { 131, "＊乖離剣エア,* Sword of Rupture, Ea"},
            { 133, "ウェドルラビエイト,Weddle Rabiate" },
            { 134, "ダーヴルソード,Darvle Sword" },
            { 135, "ダルバダソード,Darbada Sword" },
            { 136, "ダヴィアルソード,Davial Sword" },
            { 137, "＊イクリプス,* Eclipse" },
            { 138, "サステインロック,Sustain Rock" },
            { 139, "＊サウンド・オブ・ロック,* Sound of Rock" },
            { 141, "サファイザリア,Saphizaria" },
            { 142, "サファイフィーア,Sapphivier" },
            { 144, "ダルスソレイド,Dalz Soleid" },
            { 145, "フォンリーゼス,Phonlieses" },
            { 147, "ロサードリーゼス,Rosadoriezes" },
            { 148, "ブレイクライナー,Break Liner" },
            { 151, "ファーレンエンダー,Fahrenender" },
            { 152, "＊レイゲンリアーム,Reigan Rearm" },
            { 154, "レイトラス,Raytrus" },
            { 155, "リードトラス,Leadtrus" },
            { 157, "＊セブンリリーパ,* Seven Lilipans" },
            { 158, "＊アポトーシス,* Apoptosis" },
            { 159, "ジャグローク,Jugroque" },
            { 162, "新光大刃,Pristine Greatsword" },
            { 165, "イクサコウシャ,Ikusa Kousha" },
            { 168, "ルインレーヴェ,Ruin Rahvay" },
            { 169, "＊無杖ライノルト (NPC),Reinold (NPC)" },
            { 170, "ストラジオ,Stradio" },
            { 171, "ストラジェス,Strages" },
            { 173, "＊ニャウ・ソード,* Nyau Sword" },
            { 176, "＊焔龍閃滅刀,＊Dragon Flame Sword" },
            { 177, "＊スライプナーＭｋ６,* Sleipnir Mk6"},
            { 178, "＊真島吾朗バット,* Goro Majima's Bat"},
            { 179, "＊阿鼻,* Abi"},
            { 180, "＊アルマゲスト,* Almagest"},
            { 181, "＊ナイトギアエッジ,* Knight Gear Edge"},
            { 182, "＊MJ国士無双剣,＊MJ Thirteen Orphans Sword"},
            { 183, "＊スライプナーＭｋ６Ｄ,* Sleipnir Mk6D"},
            { 184, "＊スライプナーＭｋ６Ｒ,* Sleipnir Mk6R"},
            { 185, "アルケラス,Alceras"},
            { 187, "カディムケラス,Kadimceras"},
            { 188, "＊霊刀雪姫,* Soul Blade Yukihime"},
            { 189, "＊シンガー・マイク,* Singer Mic"},
            { 190, "ネメシスキャリバー,Nemesis Calibur"},
            { 191, "スレイヴキャリバー,Slave Calibur"},
            { 192, "ギグルドミナ,Gigur Domina"},
            { 194, "＊ハニュエーラー,* HUnewearl"},
            { 195, "＊フォニュエーラー,* FOnewearl"},
            { 196, "イデアルエッジ,Ideal Edge"},
            { 197, "アウェイクエッジ,Awake Edge"},
            { 198, "＊メセタリバーン,Mesetalivern"},
            { 203, "朔桜,Saku Sakura"},
            { 204, "アハトアンジ,Acht Anzhi"},
            { 207, "トウシャロウ,Tousharou"},
            { 210, "チェインソード,Chainsawd"},
            { 212, "＊チェインベルク,* Chainbelk"},
            { 216, "＊狂戦士の斧剣,* Berserker's Axe-Sword"},
            { 217, "＊ドリームブレード,* Dream Blade"},
            { 218, "＊エクスカリバーモルガン,* Excalibur Morgan"},
            { 219, "リンドクレイ,Lindcray"},
            { 220, "アルタクレイ,Altacray"},
            { 224, "＊シュヴァリエプレッジ,* Chevalier Pledge"},
            { 225, "＊儀礼剣,* Ceremonial Sword"},
            { 226, "ノクスクヴェル,Nox Kvelle"},
            { 227, "レーテクヴェル,Raete Kvelle"},
            { 228, "クヴェルアリオン,Kvelle Arion"},
            { 229, "＊セラフィ・マクラ,* Seraphy Pillow"},
            { 231, "バジリスバニフィク,Basilisk Panifique"},
            { 232, "ネブロスバニフィク,Nebros Panifique"},
            { 233, "ディアザングルム,Dia Zangulum"},
            { 234, "グラテスザングルム,Gratis Zangulum"},
            { 235, "ギクスザングルム,Gix Zangulum"},
            { 236, "＊龍鳴剣ヴァンデルホーン,* Dragon Blade Vanderhorn"},
            { 237, "＊禍装シオイナルヤンペ,* Evil Shioinaruyanpe"},
            { 238, "＊ブルー・ハート,* Blue Heart"},
            { 240, "＊ランドルオービット,* Randle Orbit"},
            { 241, "＊ランドルミラージュ,* Randle Mirage"},
            { 242, "＊ランドルノヴァ,* Randle Nova"},
            { 243, "インヴェイドカリバー,Invade Calibur"},
            { 244, "オフスティアカリバー,Ophistia Calibur"},
            { 245, "セイガーソード,Seiga Sword"},
            { 246, "セイカイザーソード,Seikaiser"},
            { 247, "＊六刃合体ゴッドセイガー,＊Six-Bladed Fusion God Seiga"},
            { 248, "D-A.I.Sセイバー,D-AIS Saber"},
            { 249, "＊霊剣・荒鷹,* Reiken-Arataka"},
            { 251, "＊龍吼魔笛グラビネット,* Magical Dragon Flute Grabinett"},
            { 252, "＊神刀スサノオ,* Divine Katana Susanoo"},
            { 253, "＊デスブリンガー,* Deathbringer"},
            { 254, "＊斬鉄剣,* Zantetsuken"},
            { 256, "ソードレボルシオ,Sword Revolucio"},
            { 257, "ソードドミナシオ,Sword Dominacio"},
            { 258, "ソードインクルシオ,Sword Inclusio"},
            { 259, "＊ラウラの両手剣,* Laura's Two-Handed Sword"},
            { 260, "＊世果・封,* Yonohate Fu"},
            { 261, "＊世果・印,* Yonohate In"},
            { 262, "＊無杖ライノルト,* Reinolt the Shapeless"},
            { 263, "リグゼレッダー,Rig Zeredder"},
            { 264, "ジグマゼレッダー,Sigma Zeredder"},
            { 265, "＊グラムゼレッター,* Gram Zeredder"},
            { 266, "＊煙管ノ槍,* Enkan-no-Sou"},
            { 267, "＊墜剣・グラム (NPC),* Fallen Sword Gram (NPC)"},
            { 271, "イヴリダハンダー,Ivlida Hander"},
            { 272, "クリシスハンダー,Cleasis Hander"},
            { 273, "シュベルハンダー,Schvelle Hander"},
            { 274, "＊ジェネ・マクラ,	* Gene Pillow"},
            { 275, "レイソード,Ray Sword"},
            { 276, "ユニオンソード,Union Sword"},
            { 277, "＊バレトレイズ,* Bullet Rays"},
            { 280, "リュミエルラーミナ,Lumiere Lamina"},
            { 281, "ジュティスラーミナ,Jutus Lamina"},
            { 282, "アレティアラーミナ,Aletheia Lamina"},
            { 283, "アストラセパル,Astra Separ"},
            { 284, "＊トール・ハンマー (NPC),* Thor's Hammer (NPC)"},
            { 285, "フォルニスジエン,Fornis Diene"},
            { 286, "アクルドジエン,Aculd Diene"},
            { 287, "コートエッジVer2,Coat Edge Ver2"},
            { 288, "雪華椿,Snow Camellia"},
            { 289, "＊バトルソード,* Battle Sword"},
            { 290, "＊ウォリアーソード,* Warrior Sword"},
            { 291, "＊ジラドザルバ,* Jilad Zalba"},
            { 293, "ウェルクレドーム,Welk Radome"},
            { 294, "＊壊世錫杖レクイエム,* Apocalypse Staff Requiem"},
            { 295, "＊神剣クロストリーズ,* Divine Blade Qrostriz"},
            { 296, "＊魔法の派・エクスカリバー,* Sorcery King Excalibur"},
            { 297, "＊クラウ・ソラス,* Claiomh Solais"},
            { 298, "＊バイオセルラ,* White Disaster"},
            { 299, "＊ゼイネシスアンガジマ,* Zeinesis Angajima"},
            { 300, "＊クリファドルサンチマン,* Clifard Ressentiment"},
            { 301, "クリーサブランド,Croesus Brand"},
            { 302, "ミリオンブランド,Millionaire Brand"},
            { 303, "＊魔剣・グラム (NPC),* Magic Sword Gram (NPC)"},
            { 304, "＊アネット・マクラ,* Annete Pillow"},
            { 306, "＊ソリテヴァイエン,* Solite Weihen"},
            { 307, "＊ファータセイバー,* Fata Saber"},
            { 308, "デモニアセイバー,Demonia Saber"},
            { 310, "＊呪刃エンレイ,* Cursed Sword Enrei"},
            { 312, "＊クイナスピカ,* Quina Spica"},
            { 313, "＊エリアコーディ,* Ely Accordi"},
            { 314, "＊白の契約／百獣の剣王,* Virtuous Contract/Beastlord"},
            { 315, "＊三式拳鍔／三式戦術刀,* Type-3 Fists/Type-3 Sword"},
            { 316, "＊三式戦術槍／三式斬機刀,* Type-3 Lance/Type-3 Blade"},
            { 317, "＊墜剣・グラム,* Fallen Sword Gram"},
            { 318, "＊魔剣・グラム,* Magic Sword Gram"},
            { 319, "バルファーダ,Val Farder"},
            { 320, "アトラファーダ,Atlas Farder"},
            { 321, "アトラファーダ・イクス,Atlas Farder Ex"},
            { 322, "＊スカルシュトルム,* Skull Sturm"},
            { 323, "＊ルクスフリーデン,* Lux Frieden"},
            { 324, "ゴレムブラフス,Golem Bluffs"},
            { 325, "ゴレムグラフォール,Golem Grafoil"},
            { 326, "＊ヴィタソード,* Vita Sword"},
            { 327, "ディトネションレイジ,Detonation Rage"},
            { 328, "＊カムラディオアモク,* Camradio Amok"},
            { 330, "＊クエンティンソード,* Cuentin Sword"},
            { 331, "＊コートエッジ,* Coated Edge"},
            { 332, "＊ガンブレードランス,* Gunblade Lance"},
            { 333, "＊レヴァティーン,* Laevateinn"},
            { 334, "ノヴェルソード,Novel Sword"},
            { 335, "リバレイトソード,Rivalate Sword"},
            { 336, "ルクスフリーデン (NPC),Lux Frieden (NPC)"},
            { 337, "ラコニウムソード (NPC),Laconium Sword (NPC)"},
            { 338, "ハリエットの剣 (NPC),Hariette's Sword(NPC)"},
            { 339, "ヴェルンドアングリフ (NPC),Weyland Angriff (NPC)"},
            { 340, "＊ヴェルンドアングリフ,* Weyland Angriff"},
            { 341, "＊クイナスピカ,* Quina Spica"},
            { 342, "＊ザメリーキャノン,* The Merry Cannon"},
            { 343, "＊ヤミガラス・マクラ,* Yamigarasu Pillow"},
            { 344, "＊閃撃ブリッツクリーク,* Jolting Blitzkrieg"},
            { 345, "エルダーペイン・オメガ,Elder Pain Omega"},
            { 346, "＊ネイソードRF,* Nei Sword RF"},
            { 347, "ブルークリスタルソード,* Blue Crystal Sword"},
            { 348, "＊マスターソード,* Master Sword"},
            { 349, "フォボスエスパディオ,Phobos Espadio"},
            { 350, "ニーケエスパディオ,Nike Espadio"},
            { 351, "ジェンスティル,Jen Steel"},
            { 352, "ジェンピュラス,Jen Puras"},
            { 353, "＊トール・ハンマー,* Thor's Hammer"},
            { 356, "＊アストクローネ,* Astokrone"},
            { 357, "＊スプライトプライト,* Sprite's Plight"},
            { 358, "＊リュミエールフォンセ,* Lumiere Fonse"},
            { 359, "＊ハイパーNINJA,* Hyper Ninja"},
            { 360, "ネメシスキャリバー-NT,Nemesis Calibur-NT"},
            { 361, "スレイヴキャリバー-NT,Slave Calibur-NT"},
            { 362, "＊上条専用スライプナー,* Sleipnir for Kamijo"},
            { 363, "＊スライプナー,* Sleipnir"},
            { 364, "グレンノオオダチ,Guren no Ohdachi"},
            { 365, "深遠剣ディメシオン,Profound Sword Dimexion"},
            { 366, "星震剣ディメシオン,Starquake Sword Dimexion"},
            { 367, "光跡剣ディメシオン,Trailblazer Sword Dimexion"},
            { 370, "＊モーニング・レッド,* Morning Red"},
            { 371, "＊ファーストアプローチ,* First Approach"},
            { 374, "＊ＢＬＡＣＫ　ＭＯＮＯＬＩＴＨ,* Black Monolith"},
            { 375, "＊ＢＬＯＯＤ　ＰＲＡＹＥＲＳ,* Blood Prayers"},
            { 376, "セレファウルス,Ceres Fouls"},
            { 377, "セレファウルス・ザラ,Ceres Fouls-Zara"},
            { 378, "＊メガスラッシュエッジ,* Mega Slash Edge"},
            { 379, "＊ホープネコソード,* Hope Neko Sword"},
            { 380, "＊灼零エルゼソード,* Burning Zero Elze Sword"},
            { 381, "＊灼零エルゼスパーダ,* Burning Zero Elze Spada"},
            { 382, "＊灼零エルゼアクス,* Burning Zero Elze Axe"},
            { 383, "ホムラノオオダチ,Homura no Ohdachi"},
            { 384, "シエンノオオダチ,Shien no Ohdachi"},
            { 387, "＊天遂リタヴラタ,* Eschaton Ritavlata"},
            { 388, "＊ライトニングエスパーダ,* Lightning Espada"},
            { 389, "＊ミラキュルマジック,* Miracle Magic"},
            { 391, "＊デスペレート,* Desperate"},
            { 392, "＊日本帝国標準兵装,* Imperial Army Std. Equipment"},
            { 393, "オブリサナヴフト,Oblisana Wucht"},
            { 394, "＊オブリアンストーベン,* Oblivion Stoven"},
            { 395, "＊フェリシテエーデル,* Felicate Edel"},
            { 396, "＊淑花春遊,* Shukuka Shunyuu"},
            { 397, "ダインヘスペラー,Dyne Hespelaro"},
            { 398, "＊武器ステルス化,* Weapon Stealthing"},
            { 399, "＊アルタードディバイド,* Altered Divide"},
            { 400, "ディムソード,Dim Sword"},
            { 401, "＊ローズセイバー,* Rose Saber"},
            { 402, "＊シッドストリッド,* Cydstrid"},
            { 403, "＊ＢＤ・ホーネット,BD Hornet"},
            { 404, "＊アフタル・マクラ,* Aphtal Pillow"},
            { 405, "＊リーン・マクラ,* Lin Pillow"},
            { 406, "＊ロンギヌスの槍,* Spear of Longinus"},
            { 407, "＊アルテミス＆レイピア,* Artemis & Rapier"},
            { 408, "フォルゴレウェベン,Fol Golweven"},
            { 412, "エリュシオーヌ-NT,Ely-Sion-NT"},
            { 413, "＊ラコニウムソード,* Laconium Sword"},
            { 414, "シャヴァルユーベル,Shaval Ueber"},
            { 415, "＊サマージェネマクラ,* Summer Gene Pillow"},
            { 416, "＊サマーアネットマクラ,* Summer Annette Pillow"},
            { 417, "＊光纏器クラーステイル,* Lightweave Klauz Tail"},
            { 418, "＊グラッド・サッド,* Glad Sad"},
            { 419, "＊インペリアルクリムゾン,* Imperial Crimson"},
            { 420, "＊ロンヴェマキラー,* Lonvema Killer"},
            { 422, "＊インペリアルクリムゾン2,* Imperial Crimson 2"},
            { 423, "＊霊刀ツムガリ,* Spirit Sword Tsumugari"},
            { 424, "＊憑依器サンガモリ,* Sangamori the Possessed"},
            { 426, "＊ノヴァストリーム,* Nova Stream"},
            { 428, "＊XM-8 ドゥーム,* XM-8 Doom"},
            { 429, "＊虹の剣,* Rainbow Blade"},
            { 430, "＊マルタ・ハーモニー,* Malta Harmony"},
            { 431, "＊凍玄幽閃,* Frostcrypt Essence"},
            { 432, "ボンズアシェット,Bonds Hachette"},
            { 433, "アデルリーネア,Adell Lienea"},
            { 434, "＊荒風十七葉,* Tempest Leaves"},
            { 435, "＊ターキーレッグ,* Turkey Leg"},
            { 438, "＊ホルシード・マクラ,* Khorshid Pillow"},
            { 441, "フルクシオヴェルラ,Fluxio Vella"},
            { 442, "リンザーヴェルラ,Rinser Vella"},
            { 443, "＊グリッドマンキャリバー,* Gridman Calibur"},
            { 444, "闇征剣アジェルエッジ,Darkweave Agile Edge"},
            { 445, "＊バール,* Crowbar"},
            { 446, "＊ビクシュサンジコウ,* Bix Sanjiko"},
            { 447, "＊艶武麗護刀,* Glorious Sentinel"},
            { 449, "＊スウィートジュエル,* Sweet Jewel"},
            { 450, "＊アスナの細剣,* Asuna's Rapier"},
            { 451, "＊キリトの双剣,* Kirito's Twin Swords"},
            { 456, "＊雅緋の黒刀,* Miyabi Black Sword"},
            { 457, "＊A.I.Sヴェガアームズ,* AIS Vega Arms"},
            { 458, "＊テイルススパナ,* Tails Wrench"},
            { 459, "＊勇者の聖剣,* The Hero’s Holy Sword"},
            { 460, "＊ソウルバニッシュ,* Soul Banish"},
        };
        public static Dictionary<int, string> wiredLanceNames = new Dictionary<int, string>()
        {
            { 001, "ワイヤードランス,Wired Lance"},
            { 002, "アルバランス,Alba Lance"},
            { 003, "ヴィタランス,Vita Lance"},
            { 004, "ワイヤードゲイン,Wired Gain"},
            { 005, "アルバゲイン,Alba Gain"},
            { 006, "ヴィタゲイン,Vita Gain"},
            { 007, "ワイヤードオーバー,Wired Over"},
            { 008, "アルバオーバー,Alba Over"},
            { 009, "ヴィタオーバー,Vita Over"},
            { 010, "ワイヤードアーチ,Wired Arch"},
            { 011, "アルバアーチ,Alba Arch"},
            { 012, "ヴィタアーチ,Vita Arch"},
            { 013, "ワイヤードトライ,Wired Tri"},
            { 014, "アルバトライ,Alba Tri"},
            { 015, "ヴィタトライ,Vita Tri"},
            { 016, "クシャネビュラ,Kuscha Nebula"},
            { 017, "ラムダジャグリアス,Lambda Jagriath"},
            { 018, "ディオジャグリアス,Dio Jagriath"},
            { 019, "ジャグリアス,Jagriath"},
            { 020, "ベルカード,Belcard"},
            { 021, "ハイペリオン,Hyperion"},
            { 022, "デイライトスカー,Daylight Scar"},
            { 023, "ファルクロー,Falclaw"},
            { 024, "ギガススピナー,Gigas Spinner"},
            { 025, "ディアボリックガント,Diabolic Gauntlet"},
            { 026, "アサシンクロー,Assassin Claw"},
            { 027, "ネイクロー,Neiclaw"},
            { 028, "ロケットパンチ,Rocket Punch"},
            { 029, "ファティウーマ,Phyteuma"},
            { 030, "グッダスケラ,Gudda Skela"},
            { 031, "ディオクシャネビュラ,Dio Kuscha Nebula"},
            { 032, "ラムダクシャネビュラ,Lambda Kuscha Nebula"},
            { 033, "ラムダベルカード,Lambda Belcard"},
            { 034, "ディオベルカード,Dio Belcard"},
            { 035, "ディオハイペリオン,Dio Hyperion"},
            { 036, "ラムダハイペリオン,Lambda Hyperion"},
            { 037, "マルモスファング,Malmoth Fang"},
            { 080, "＊ラッピーケージ,* Rappy Cage"},
            { 135, "＊超硬質ブレード,* Ultrahard Blades"},
            { 168, "＊荊,* Thorn"},
            { 197, "ランスレボルシオ,Lance Revolucio"},
            { 198, "ランスドミナシオ,Lance Dominacio"},
            { 199, "ランスインクルシオ,Lance Inclusio"},
            { 247, "ゲノンズィーバ,Genon Ziva"},
            { 259, "＊レヴァティーン,* Laevateinn"},
        };
        public static Dictionary<int, string> partizanNames = new Dictionary<int, string>()
        {
            { 061, "＊零織・イザヨイ,* Zero-type Izayoi"},
            { 201, "スピアレボルシオ,Spear Revolucio"},
            { 202, "スピアドミナシオ,Spear Dominacio"},
            { 203, "スピアインクルシオ,Spear Inclusio"},
            { 274, "＊レヴァティーン,* Laevateinn"},
            { 335, "＊ロンギヌスの槍,* Longinus Lance"},
        };
        public static Dictionary<int, string> twinDaggerNames = new Dictionary<int, string>()
        {
            { 217, "スラストレボルシオ,Thrust Revolucio"},
            { 218, "スラストドミナシオ,Thrust Dominacio"},
            { 219, "スラストインクルシオ,Thrust Inclusio"},
            { 278, "＊レヴァティーン,* Laevateinn"},
        };
        public static Dictionary<int, string> doubleSaberNames = new Dictionary<int, string>()
        {
            { 062, "＊ブルー・ハート,* Blue Heart"},
            { 078, "＊ブラッドサイズ,* Blood Scythe"},
            { 196, "＊ジャンクヤード・ドッグ,* Junkyard Dog"},
            { 210, "ストームレボルシオ,Storm Revolucio"},
            { 211, "ストームドミナシオ,Storm Dominacio"},
            { 212, "ストームインクルシオ,Storm Inclusio"},
            { 308, "＊レヴァティーン,* Laevateinn"},
        };
        public static Dictionary<int, string> knucklesNames = new Dictionary<int, string>()
        {
            { 197, "スパイクレボルシオ,Spike Revolucio"},
            { 198, "スパイクドミナシオ,Spike Dominacio"},
            { 199, "スパイクインクルシオ,Spike Inclusio"},
        };
        public static Dictionary<int, string> gunslashNames = new Dictionary<int, string>()
        {
            { 152, "＊スライプナーＭｋ６,* Sleipnir Mk6"},
            { 156, "＊スライプナーＭｋ６Ｄ,* Sleipnir Mk6D"},
            { 157, "＊スライプナーＭｋ６Ｒ,* Sleipnir Mk6R"},
            { 213, "スラッシュレボルシオ,Slash Revolucio"},
            { 214, "スラッシュドミナシオ,Slash Dominacio"},
            { 215, "スラッシュインクルシオ,Slash Inclusio"},
        };
        public static Dictionary<int, string> rifleNames = new Dictionary<int, string>()
        {
            { 237, "ショットレボルシオ,Shot Revolucio"},
            { 238, "ショットドミナシオ,Shot Dominacio"},
            { 239, "ショットインクルシオ,Shot Inclusio"},
        };
        public static Dictionary<int, string> launcherNames = new Dictionary<int, string>()
        {
            { 027, "フォトンランチャー,Photon Launcher"},
            { 037, "レッドスコルピオ,Red Scorpio"},
            { 038, "ギルティライト,Guilty Light"},
            { 165, "＊メセタンシューター,* Mesetan Shooter"},
            { 193, "＊スクルド,* Skuld"},
            { 237, "キャノンレボルシオ,Cannon Revolucio"},
            { 238, "キャノンドミナシオ,Cannon Dominacio"},
            { 239, "キャノンインクルシオ,Cannon Inclusio"},
            { 250, "フォルニスルーギア,Fornis Lugia"},
            { 251, "アクルドルーギア,Aculd Lugia"},
            { 255, "＊ＲＡトラベラー,RA Traberah"},
            { 269, "＊ジラドボルス,* Jilad Volse"},
            { 311, "＊ＢＬＡＣＫ　ＭＯＮＯＬＩＴＨ,* Black Monolith"},
            { 312, "＊ＢＬＯＯＤ　ＰＲＡＹＥＲＳ,* Blood Prayers"},
            { 316, "＊灼零エルゼガンツェ,* Burning Zero Elze Ganze"},
        };
        public static Dictionary<int, string> tmgNames = new Dictionary<int, string>()
        {
            { 276, "バレットレボルシオ,Bullet Revolucio"},
            { 277, "バレットドミナシオ,Bullet Dominacio"},
            { 278, "バレットインクルシオ,Bullet Inclusio"},
        };
        public static Dictionary<int, string> rodNames = new Dictionary<int, string>()
        {
            { 010, "フォールオンス,Fallounce"},
            { 011, "アルバフォールオンス,Alba Fallounce"},
            { 012, "ヴィタフォールオンス,Vita Fallounce"},
            { 259, "シャフトレボルシオ,Shaft Revolucio"},
            { 260, "シャフトドミナシオ,Shaft Dominacio"},
            { 261, "シャフトインクルシオ,Shaft Inclusio"},
            { 323, "＊ヴィタフォールオンス,＊ Vita Fallounce"},
            { 335, "＊リバレイトアーマリー,* Rivalate Armory"},
            { 352, "＊レヴァティーン,* Laevateinn"},
        };
        public static Dictionary<int, string> talysNames = new Dictionary<int, string>()
        {
            { 234, "カードレボルシオ,Card Revolucio"},
            { 235, "カードドミナシオ,Card Dominacio"},
            { 236, "カードインクルシオ,Card Inclusio"},
            { 254, "＊ジラドベリス,* Jilad Veris"},
        };
        public static Dictionary<int, string> wandNames = new Dictionary<int, string>()
        {
            { 055, "＊マジカルサファイア,* Magical Saphire"},
            { 066, "＊ジャンクヤード・ドッグ,* Junkyard Dog"},
            { 139, "＊マジカルルビー,* Magical Ruby"},
            { 253, "エッジレボルシオ,Saika Revolucio"},
            { 254, "エッジドミナシオ,Saika Dominacio"},
            { 255, "エッジインクルシオ,Saika Inclusio"},
            { 354, "＊レヴァティーン,* Laevateinn"},
        };
        public static Dictionary<int, string> katanaNames = new Dictionary<int, string>()
        {
            { 100, "＊ソウル・オブ・ウォパル,* Soul of Vopar"},
            { 169, "カザミノタチ,Kazami-no-tachi"},
            { 210, "サイカレボルシオ,Saika Revolucio"},
            { 211, "サイカドミナシオ,Saika Dominacio"},
            { 212, "サイカインクルシオ,Saika Inclusio"},
            { 291, "＊レヴァティーン,* Laevateinn"},
        };
        public static Dictionary<int, string> bowNames = new Dictionary<int, string>()
        {
            { 198, "アーチレボルシオ,Arch Revolucio"},
            { 199, "アーチドミナシオ,Arch Dominacio"},
            { 200, "アーチインクルシオ,Arch Inclusio"},
        };
        public static Dictionary<int, string> jetBootsNames = new Dictionary<int, string>()
        {
            { 125, "＊キジカナルカミ,* Kizika Narukami"},
            { 181, "ブレードレボルシオ,Shoes Revolucio"},
            { 182, "ブレードドミナシオ,Shoes Dominacio"},
            { 183, "ブレードインクルシオ,Shoes Inclusio"},
        };
        public static Dictionary<int, string> dualBladesNames = new Dictionary<int, string>()
        {
            { 215, "ブレードレボルシオ,Blade Revolucio"},
            { 216, "ブレードドミナシオ,Blade Dominacio"},
            { 217, "ブレードインクルシオ,Blade Inclusio"},
            { 271, "＊レヴァティーン,* Laevateinn"},
        };
        public static Dictionary<int, string> tactNames = new Dictionary<int, string>()
        {
            { 017, "タクトレボルシオ,Takt Revolucio"},
            { 019, "タクトインクルシオ,Takt Inclusio"}
        };


        public static Dictionary<int, string> swordNGSNames = new Dictionary<int, string>()
        {
            { 022, "＊ブラッドサイズ,* Blood Scythe"},
            { 044, "＊スペース・ツナ,* Space Tuna"},
            { 098, "＊零織・イザヨイ,* Zero-type Izayoi"},
            { 104, "＊フロウウェンの大剣,* Flowen's Sword"},
            { 106, "＊ジャンクヤード・ドッグ,* Junkyard Dog"},
            { 130, "＊約束された勝利の剣,* The Sword of Promised Victory"},
            { 131, "＊乖離剣エア,* Sword of Rupture, Ea"},
            { 177, "＊スライプナーＭｋ６,* Sleipnir Mk6"},
            { 183, "＊スライプナーＭｋ６Ｄ,* Sleipnir Mk6D"},
            { 184, "＊スライプナーＭｋ６Ｒ,* Sleipnir Mk6R"},
            { 238, "＊ブルー・ハート,* Blue Heart"},
            { 256, "ソードレボルシオ,Sword Revolucio"},
            { 257, "ソードドミナシオ,Sword Dominacio"},
            { 258, "ソードインクルシオ,Sword Inclusio"},
            { 333, "＊レヴァティーン,* Laevateinn"},
            { 362, "＊上条専用スライプナー,* Sleipnir for Kamijo"},
            { 363, "＊スライプナー,* Sleipnir"},            
            { 374, "＊ＢＬＡＣＫ　ＭＯＮＯＬＩＴＨ,* Black Monolith"},
            { 375, "＊ＢＬＯＯＤ　ＰＲＡＹＥＲＳ,* Blood Prayers"},
            { 501, "プリムソード,Primm Sword"},
            { 503, "ゴルドプリムソード?,Gold Primm Sword?"},
            { 504, "ツヴィアソード,Tzvia Sword"},
            { 505, "リサージュソード,Resurgir Sword"},
            { 508, "テルセウスソード,Theseus Sword"},
            { 509, "キャトリアソード,Cattleya Sword"},
            { 513, "グリッセンソード,Glissen Sword"},
            { 514, "プリムソード?,Primm Sword?"},
            { 515, "エヴォルコートソード,Evolcoat Sword"},
            { 524, "ゴルドプリムソード,Gold Primm Sword"},
            { 525, "シルヴァプリムソード,Silver Primm Sword"},
            { 526, "ストラーガソード,Straga Sword"},
        };
        public static Dictionary<int, string> wiredLanceNGSNames = new Dictionary<int, string>()
        {
            { 080, "＊ラッピーケージ,* Rappy Cage"},
            { 135, "＊超硬質ブレード,* Ultrahard Blades"},
            { 168, "＊荊,* Thorn"},
            { 197, "ランスレボルシオ,Lance Revolucio"},
            { 198, "ランスドミナシオ,Lance Dominacio"},
            { 199, "ランスインクルシオ,Lance Inclusio"},
            { 247, "ゲノンズィーバ,Genon Ziva"},
            { 259, "＊レヴァティーン,* Laevateinn"},
            { 501, "プリムワイヤー,Primm Wire"},
            { 502, "リサージュワイヤー,Resurgir Wire"},
            { 504, "テルセウスワイヤー,Theseus Wire"},
            { 505, "フォーシスワイヤー,Foursis Wire"},
            { 506, "グリッセンワイヤー,Glissen Wire"},
            { 508, "ツヴィアワイヤー,Tzvia Wire"},
            { 509, "エヴォルコートワイヤー,Evolcoat Wire"},
            { 513, "フロステルワイヤー,Frostel Wire"},
            { 521, "ゴルドプリムワイヤー,Gold Primm Wire"},
            { 522, "シルヴァプリムワイヤー,Silver Primm Wire"},
            { 523, "ストラーガワイヤー,Straga Wire"},
        };
        public static Dictionary<int, string> partizanNGSNames = new Dictionary<int, string>()
        {
            { 061, "＊零織・イザヨイ,* Zero-type Izayoi"},
            { 201, "スピアレボルシオ,Spear Revolucio"},
            { 202, "スピアドミナシオ,Spear Dominacio"},
            { 203, "スピアインクルシオ,Spear Inclusio"},
            { 274, "＊レヴァティーン,* Laevateinn"},
            { 335, "＊ロンギヌスの槍,* Longinus Lance"},
            { 501, "プリムスピア,Primm Spear"},
            { 502, "リサージュスピア,Resurgir Spear"},
            { 503, "テルセウススピア,Theseus Spear"},
            { 504, "＊ガロアスピア,* Garoa Spear"},
            { 506, "ヴィアルトスピア,Vialto Spear"},
            { 508, "ツヴィアスピア,Tzvia Spear"},
            { 509, "＊ブルッジスピア,* Dozerro Spear"},
            { 510, "エヴォルコートスピア,Evolcoat Spear"},
            { 522, "ゴルドプリムスピア,Gold Primm Spear"},
            { 523, "シルヴァプリムスピア,Silver Primm Spear"},
            { 524, "ストラーガスピア,Straga Spear"},
        };
        public static Dictionary<int, string> twinDaggerNGSNames = new Dictionary<int, string>()
        {
            { 217, "スラストレボルシオ,Thrust Revolucio"},
            { 218, "スラストドミナシオ,Thrust Dominacio"},
            { 219, "スラストインクルシオ,Thrust Inclusio"},
            { 278, "＊レヴァティーン,* Laevateinn"},
            { 501, "プリムダガー,Primm Daggers"},
            { 502, "リサージュダガー,Resurgir Daggers"},
            { 503, "フォーシスダガー,Foursis Daggers"},
            { 504, "＊マノフィーマルテ,* Manophi Marte"},
            { 505, "エヴォルコートダガー,Evolcoat Daggers"},
            { 507, "トロワーデダガー,Trois De Daggers"},
            { 508, "ツヴィアダガー,Tzvia Daggers"},
            { 522, "ゴルドプリムダガー,Gold Primm Daggers"},
            { 523, "シルヴァプリムダガー,Silver Primm Daggers"},
            { 524, "ストラーガアダガー,Straga Daggers"},
        };
        public static Dictionary<int, string> doubleSaberNGSNames = new Dictionary<int, string>()
        {
            { 062, "＊ブルー・ハート,* Blue Heart"},
            { 078, "＊ブラッドサイズ,* Blood Scythe"},
            { 196, "＊ジャンクヤード・ドッグ,* Junkyard Dog"},
            { 210, "ストームレボルシオ,Storm Revolucio"},
            { 211, "ストームドミナシオ,Storm Dominacio"},
            { 212, "ストームインクルシオ,Storm Inclusio"},
            { 308, "＊レヴァティーン,* Laevateinn"},
            { 501, "プリムセイバー,Primm Saber"},
            { 502, "リサージュセイバー,Resurgir Saber"},
            { 503, "ヴィアルトセイバー,Vialto Saber"},
            { 505, "トロワーデセイバー,Trois De Saber"},
            { 506, "ツヴィアセイバー,Tzvia Saber"},
            { 507, "グリッセンセイバー,Glissen Saber"},
            { 508, "エヴォルコートセイバー,Evolcoat Saber"},
            { 513, "フロステルセイバー,Frostel Saber"},
            { 523, "ゴルドプリムセイバー,Gold Primm Saber"},
            { 524, "シルヴァプリムセイバー,Silver Primm Saber"},
            { 525, "ストラーガプリムセイバー,Straga Saber"},
        };
        public static Dictionary<int, string> knucklesNGSNames = new Dictionary<int, string>()
        {
            { 197, "スパイクレボルシオ,Spike Revolucio"},
            { 198, "スパイクドミナシオ,Spike Dominacio"},
            { 199, "スパイクインクルシオ,Spike Inclusio"},
            { 501, "プリムナックル,Primm Knuckles"},
            { 502, "リサージュナックル,Resurgir Knuckles"},
            { 504, "キャトリアナックル,Cattleya Knuckles"},
            { 505, "トロワーデナックル,Trois De Knuckles"},
            { 506, "ツヴィアナックル,Tzvia Knuckles"},
            { 507, "グリッセンナックル,Glissen Knuckles"},
            { 508, "エヴォルコートナックル,Evolcoat Knuckles"},
            { 521, "ゴルドプリムナックル,Gold Primm Knuckles"},
            { 522, "シルヴァプリムナックル,Silver Primm Knuckles"},
            { 523, "ストラーガナックル,Straga Knuckles"},
        };
        public static Dictionary<int, string> gunslashNGSNames = new Dictionary<int, string>()
        {
            { 152, "＊スライプナーＭｋ６,* Sleipnir Mk6"},
            { 156, "＊スライプナーＭｋ６Ｄ,* Sleipnir Mk6D"},
            { 157, "＊スライプナーＭｋ６Ｒ,* Sleipnir Mk6R"},
            { 213, "スラッシュレボルシオ,Slash Revolucio"},
            { 214, "スラッシュドミナシオ,Slash Dominacio"},
            { 215, "スラッシュインクルシオ,Slash Inclusio"},
        };
        public static Dictionary<int, string> rifleNGSNames = new Dictionary<int, string>()
        {
            { 237, "ショットレボルシオ,Shot Revolucio"},
            { 238, "ショットドミナシオ,Shot Dominacio"},
            { 239, "ショットインクルシオ,Shot Inclusio"},
            { 501, "プリムライフル,Primm Rifle"},
            { 502, "リサージュライフル,Resurgir Rifle"},
            { 505, "テルセウスライフル,Theseus Rifle"},
            { 507, "フォーシスライフル,Foursis Rifle"},
            { 508, "＊アイネーロライフル,* Ainerro Rifle"},
            { 510, "ツヴィアライフル,Tzvia Rifle"},
            { 511, "エヴォルコートライフル,Evolcoat Rifle"},
            { 523, "ゴルドプリムライフル,Gold Primm Rifle"},
            { 524, "シルヴァプリムライフル,Silver Primm Rifle"},
            { 525, "ストラーガライフル,Straga Rifle"},
        };
        public static Dictionary<int, string> launcherNGSNames = new Dictionary<int, string>()
        {
            { 027, "フォトンランチャー,Photon Launcher"},
            { 037, "レッドスコルピオ,Red Scorpio"},
            { 038, "ギルティライト,Guilty Light"},
            { 165, "＊メセタンシューター,* Mesetan Shooter"},
            { 193, "＊スクルド,* Skuld"},
            { 237, "キャノンレボルシオ,Cannon Revolucio"},
            { 238, "キャノンドミナシオ,Cannon Dominacio"},
            { 239, "キャノンインクルシオ,Cannon Inclusio"},
            { 250, "フォルニスルーギア,Fornis Lugia"},
            { 251, "アクルドルーギア,Aculd Lugia"},
            { 255, "＊ＲＡトラベラー,RA Traberah"},
            { 269, "＊ジラドボルス,* Jilad Volse"},
            { 311, "＊ＢＬＡＣＫ　ＭＯＮＯＬＩＴＨ,* Black Monolith"},
            { 312, "＊ＢＬＯＯＤ　ＰＲＡＹＥＲＳ,* Blood Prayers"},
            { 316, "＊灼零エルゼガンツェ,* Burning Zero Elze Ganze"},
            { 501, "プリムランチャー,Primm Launcher"},
            { 502, "リサージュランチャー,Resurgir Launcher"},
            { 503, "テルセウスランチャー,Theseus Launcher"},
            { 506, "ヴィアルトランチャー,Vialto Launcher"},
            { 507, "ツヴィアランチャー,Tzvia Launcher"},
            { 508, "グリッセンランチャー,Glissen Launcher"},
            { 510, "エヴォルコートランチャー,Evolcoat Launcher"},
            { 514, "フロステルランチャー,Frostel Launcher"},
            { 521, "ゴルドプリムランチャー,Gold Primm Launcher"},
            { 522, "シルヴァプリムランチャー,Silver Primm Launcher"},
            { 524, "ストラーガランチャー,Straga Launcher"},
        };
        public static Dictionary<int, string> tmgNGSNames = new Dictionary<int, string>()
        {
            { 276, "バレットレボルシオ,Bullet Revolucio"},
            { 277, "バレットドミナシオ,Bullet Dominacio"},
            { 278, "バレットインクルシオ,Bullet Inclusio"},
            { 501, "プリムマシンガン,Primm Twin Machine Guns"},
            { 502, "リサージュマシンガン,Resurgir Machine Guns"},
            { 505, "キャトリアマシンガン,Cattleya Machine Guns"},
            { 506, "テルセウスマシンガン,Theseus Machine Guns"},
            { 507, "ツヴィアマシンガン,Tzvia Machine Guns"},
            { 508, "グリッセンマシンガン,Glissen Machine Guns"},
            { 509, "エヴォルコートマシンガン,Evolcoat Machine Guns"},
            { 514, "フロステルマシンガン,Frostel Machine Guns"},
            { 521, "ゴルドプリムマシンガン,Gold Primm Machine Guns"},
            { 522, "シルヴァプリムマシンガン,Silver Machine Guns"},
            { 524, "ストラーガマシンガン,Straga Machine Guns"},
        };
        public static Dictionary<int, string> rodNGSNames = new Dictionary<int, string>()
        {
            { 010, "フォールオンス,Fallounce"},
            { 011, "アルバフォールオンス,Alba Fallounce"},
            { 012, "ヴィタフォールオンス,Vita Fallounce"},
            { 259, "シャフトレボルシオ,Shaft Revolucio"},
            { 260, "シャフトドミナシオ,Shaft Dominacio"},
            { 261, "シャフトインクルシオ,Shaft Inclusio"},
            { 323, "＊ヴィタフォールオンス,＊ Vita Fallounce"},
            { 335, "＊リバレイトアーマリー,* Rivalate Armory"},
            { 352, "＊レヴァティーン,* Laevateinn"},
            { 501, "プリムロッド,Primm Rod"},
            { 502, "リサージュロッド,Resurgir Rod"},
            { 503, "トロワーデロッド,Trois De Rod"},
            { 504, ","},
            { 505, "＊マノフィーマルテ,* Manophi Marte"},
            { 508, "フォーシスロッド,Foursis Rod"},
            { 510, "ツヴィアロッド,Tzvia Rod"},
            { 511, "エヴォルコートロッド,Evolcoat Rod"},
            { 522, "ゴルドプリムロッド,Gold Primm Rod"},
            { 523, "シルヴァプリムロッド,Silver Primm Rod"},
            { 524, "ストラーガロッド,Straga Rod"},
            { 525, "フロステルロッド,Frostel Rod"},
        };
        public static Dictionary<int, string> talysNGSNames = new Dictionary<int, string>()
        {
            { 234, "カードレボルシオ,Card Revolucio"},
            { 235, "カードドミナシオ,Card Dominacio"},
            { 236, "カードインクルシオ,Card Inclusio"},
            { 254, "＊ジラドベリス,* Jilad Veris"},
            { 501, "プリムタリス,Primm Talis"},
            { 502, "リサージュタリス,Resurgir Talis"},
            { 505, "ヴィアルトタリス,Vialto Talis"},
            { 506, "トロワーデタリス,Trois De Talis"},
            { 507, "ツヴィアタリス,Tzvia Talis"},
            { 508, "グリッセンタリス,Glissen Talis"},
            { 509, "エヴォルコートタリス,Evolcoat Talis"},
            { 520, "ゴルドプリムタリス,Gold Primm Talis"},
            { 521, "シルヴァプリムタリス,Silver Primm Talis"},
            { 522, "ストラーガタリス,Straga Talis"},
        };
        public static Dictionary<int, string> wandNGSNames = new Dictionary<int, string>()
        {
            { 055, "＊マジカルサファイア,* Magical Saphire"},
            { 066, "＊ジャンクヤード・ドッグ,* Junkyard Dog"},
            { 139, "＊マジカルルビー,* Magical Ruby"},
            { 253, "エッジレボルシオ,Saika Revolucio"},
            { 254, "エッジドミナシオ,Saika Dominacio"},
            { 255, "エッジインクルシオ,Saika Inclusio"},
            { 354, "＊レヴァティーン,* Laevateinn"},
            { 501, "プリムウォンド,Primm Wand"},
            { 502, "リサージュウォンド,Resurgir Wand"},
            { 503, "グリッセンウォンド,Glissen Wand"},
            { 505, "クロフォードのウォンド?,Crawford Wand?"},
            { 507, "トロワーデウォンド,Trois De Wand"},
            { 508, "キャトリアウォンド,Cattleya Wand"},
            { 509, "ツヴィアウォンド,Tzvia Wand"},
            { 510, "エヴォルコートウォンド,Evolcoat Wand"},
            { 514, "フロステルウォンド,Frostel Wand"},
            { 521, "ゴルドプリムウォンド,Gold Primm  Wand"},
            { 522, "シルヴァプリムウォンド,Silver Primm Wand"},
            { 524, "ストラーガウォンド,Straga Wand"},
        };
        public static Dictionary<int, string> katanaNGSNames = new Dictionary<int, string>()
        {
            { 100, "＊ソウル・オブ・ウォパル,* Soul of Vopar"},
            { 169, "カザミノタチ,Kazami-no-tachi"},
            { 210, "サイカレボルシオ,Saika Revolucio"},
            { 211, "サイカドミナシオ,Saika Dominacio"},
            { 212, "サイカインクルシオ,Saika Inclusio"},
            { 291, "＊レヴァティーン,* Laevateinn"},
            { 501, "プリムカタナ,Primm Katana"},
            { 502, "リサージュカタナ,Resurgir Katana"},
            { 505, "トロワーデカタナ,Trois De Katana"},
            { 506, "フォーシスカタナ,Foursis Katana"},
            { 508, "ツヴィアカタナ,Tzvia Katana"},
            { 509, "エヴォルコートカタナ,Evolcoat Katana"},
            { 514, "フロステルカタナ,Frostel Katana"},
            { 522, "ゴルドプリムカタナ,Gold Primm Katana"},
            { 523, "シルヴァプリムカタナ,Silver Primm Katana"},
            { 526, "ストラーガカタナ,Straga Katana"},
        };
        public static Dictionary<int, string> bowNGSNames = new Dictionary<int, string>()
        {
            { 198, "アーチレボルシオ,Arch Revolucio"},
            { 199, "アーチドミナシオ,Arch Dominacio"},
            { 200, "アーチインクルシオ,Arch Inclusio"},
            { 501, "プリムボウ,Primm Bow"},
            { 502, "リサージュボウ,Resurgir Bow"},
            { 505, "ヴィアルトボウ,Vialto Bow"},
            { 506, "ツヴィアボウ,Tzvia Bow"},
            { 507, "エヴォルコートボウ,Evolcaot Bow"},
            { 508, "テルセウスボウ,Theseus Bow"},
            { 522, "ゴルドプリムボウ,Gold Primm Bow"},
            { 523, "シルヴァプリムボウ,Silver Primm Bow"},
            { 525, "ストラーガボウ,Straga Bow"},
        };
        public static Dictionary<int, string> jetBootsNGSNames = new Dictionary<int, string>()
        {
            { 125, "＊キジカナルカミ,* Kizika Narukami"},
            { 181, "ブレードレボルシオ,Shoes Revolucio"},
            { 182, "ブレードドミナシオ,Shoes Dominacio"},
            { 183, "ブレードインクルシオ,Shoes Inclusio"},
            { 501, "プリムブーツ,Primm Boots"},
            { 503, ","},
        };
        public static Dictionary<int, string> dualBladesNGSNames = new Dictionary<int, string>()
        {
            { 215, "ブレードレボルシオ,Blade Revolucio"},
            { 216, "ブレードドミナシオ,Blade Dominacio"},
            { 217, "ブレードインクルシオ,Blade Inclusio"},
            { 271, "＊レヴァティーン,* Laevateinn"},
            { 501, "プリムブレード,Primm Blade"},
        };
        public static Dictionary<int, string> tactNGSNames = new Dictionary<int, string>()
        {
            { 017, "タクトレボルシオ,Takt Revolucio"},
            { 019, "タクトインクルシオ,Takt Inclusio"}
        };
        
        public static List<string> csvFilenames = new List<string>() 
        { 
            "SwordNames.csv",
            "WiredLanceNames.csv",
            "PartizanNames.csv",
            "TwinDaggerNames.csv",
            "DoubleSaberNames.csv",
            "KnucklesNames.csv",
            "GunslashNames.csv",
            "RifleNames.csv",
            "LauncherNames.csv",
            "TwinMachineGunNames.csv",
            "RodNames.csv",
            "TalisNames.csv",
            "WandNames.csv",
            "KatanaNames.csv",
            "BowNames.csv",
            "JetBootsNames.csv",
            "DualBladesNames.csv",
            "TactNames.csv",

            "SwordNGSNames.csv",
            "WiredLanceNGSNames.csv",
            "PartizanNGSNames.csv",
            "TwinDaggerNGSNames.csv",
            "DoubleSaberNGSNames.csv",
            "KnucklesNGSNames.csv",
            "GunslashNGSNames.csv",
            "RifleNGSNames.csv",
            "LauncherNGSNames.csv",
            "TwinMachineGunNGSNames.csv",
            "RodNGSNames.csv",
            "TalisNGSNames.csv",
            "WandNGSNames.csv",
            "KatanaNGSNames.csv",
            "BowNGSNames.csv",
            "JetBootsNGSNames.csv",
            "DualBladesNGSNames.csv",
            "TactNGSNames.csv",
        };


        public static List<string> playerEffects = new List<string>()
            {
                "actor/shot/effect_2dg.ice",
                "actor/shot/effect_2sm.ice",
                "actor/shot/effect_arks_buff.ice",
                "actor/shot/effect_aslt.ice",
                "actor/shot/effect_boots.ice",
                "actor/shot/effect_cmpdbow.ice",
                "actor/shot/effect_cs.ice",
                "actor/shot/effect_dbld.ice",
                "actor/shot/effect_dsa.ice",
                "actor/shot/effect_en_sprdbm.ice",
                "actor/shot/effect_ene_sld.ice",
                "actor/shot/effect_gslh.ice",
                "actor/shot/effect_hr2sm.ice",
                "actor/shot/effect_hrswd.ice",
                "actor/shot/effect_hrthlys.ice",
                "actor/shot/effect_knu.ice",
                "actor/shot/effect_ktn.ice",
                "actor/shot/effect_lnch.ice",
                "actor/shot/effect_mag.ice",
                "actor/shot/effect_mrg_buff.ice",
                "actor/shot/effect_mstdbld.ice",
                "actor/shot/effect_mstdsa.ice",
                "actor/shot/effect_mstwnd.ice",
                "actor/shot/effect_mti_buff.ice",
                "actor/shot/effect_parti.ice",
                "actor/shot/effect_sc_success_buff.ice",
                "actor/shot/effect_slagsl.ice",
                "actor/shot/effect_sum.ice",
                "actor/shot/effect_swd.ice",
                "actor/shot/effect_tec.ice",
                "actor/shot/effect_thlys.ice",
                "actor/shot/effect_vlnaslt.ice",
                "actor/shot/effect_vlnktn.ice",
                "actor/shot/effect_vlnrod.ice",
                "actor/shot/effect_wlce.ice",
                "actor/shot/effect_wnd.ice",
                "actor/shot/effect_wp_pot_02_242.ice",
                "actor/shot/effect_wp_pot_06_202.ice",
                "actor/shot/effect_wp_pot_07_091.ice",
                "actor/shot/effect_wp_pot_09_bnk.ice",
                "actor/shot/effect_wp_pot_13_290.ice",
                "actor/shot/effect_wp_pot_14_264.ice",
                "actor/shot/effect_wp_pot_15_059.ice",
                "actor/shot/effect_wp_pot_16_128.ice",
                "actor/shot/effect_wp_pot_absh.ice",
                "actor/shot/effect_wp_pot_ace.ice",
                "actor/shot/effect_wp_pot_ang.ice",
                "actor/shot/effect_wp_pot_arles.ice",
                "actor/shot/effect_wp_pot_aut_recv.ice",
                "actor/shot/effect_wp_pot_autos.ice",
                "actor/shot/effect_wp_pot_barrier.ice",
                "actor/shot/effect_wp_pot_berserk.ice",
                "actor/shot/effect_wp_pot_bldr.ice",
                "actor/shot/effect_wp_pot_bone.ice",
                "actor/shot/effect_wp_pot_chskip.ice",
                "actor/shot/effect_wp_pot_com_plybuff.ice",
                "actor/shot/effect_wp_pot_crystal.ice",
                "actor/shot/effect_wp_pot_dest.ice",
                "actor/shot/effect_wp_pot_dmgst.ice",
                "actor/shot/effect_wp_pot_elebo.ice",
                "actor/shot/effect_wp_pot_elebo2.ice",
                "actor/shot/effect_wp_pot_elm_black.ice",
                "actor/shot/effect_wp_pot_elm_blue.ice",
                "actor/shot/effect_wp_pot_elm_green.ice",
                "actor/shot/effect_wp_pot_elm_red.ice",
                "actor/shot/effect_wp_pot_elm_white.ice",
                "actor/shot/effect_wp_pot_elm_yellow.ice",
                "actor/shot/effect_wp_pot_endstrong.ice",
                "actor/shot/effect_wp_pot_expwep.ice",
                "actor/shot/effect_wp_pot_gearguard_c.ice",
                "actor/shot/effect_wp_pot_homilan.ice",
                "actor/shot/effect_wp_pot_lastbl.ice",
                "actor/shot/effect_wp_pot_med.ice",
                "actor/shot/effect_wp_pot_mira_mnb.ice",
                "actor/shot/effect_wp_pot_mrroid.ice",
                "actor/shot/effect_wp_pot_nodb.ice",
                "actor/shot/effect_wp_pot_non_pbld.ice",
                "actor/shot/effect_wp_pot_phobos.ice",
                "actor/shot/effect_wp_pot_ppfever.ice",
                "actor/shot/effect_wp_pot_preh.ice",
                "actor/shot/effect_wp_pot_preh2.ice",
                "actor/shot/effect_wp_pot_prfdtlck.ice",
                "actor/shot/effect_wp_pot_prod.ice",
                "actor/shot/effect_wp_pot_rdbd.ice",
                "actor/shot/effect_wp_pot_reng.ice",
                "actor/shot/effect_wp_pot_revgift.ice",
                "actor/shot/effect_wp_pot_saberstyle.ice",
                "actor/shot/effect_wp_pot_sbeam.ice",
                "actor/shot/effect_wp_pot_shooting_s.ice",
                "actor/shot/effect_wp_pot_shwtim_onetim.ice",
                "actor/shot/effect_wp_pot_spinfe.ice",
                "actor/shot/effect_wp_pot_stedb.ice",
                "actor/shot/effect_wp_pot_thdmas.ice",
                "actor/shot/effect_wp_pot_time_chan.ice",
                "actor/shot/effect_wp_pot_turt.ice",
                "actor/shot/effect_wp_pot_union.ice",
                "actor/shot/effect_wp_pot_vintrange.ice",
                "actor/shot/effect_wp_pot_vrefine.ice",
                "actor/shot/effect_wp_pot_weekhit.ice",
                "actor/shot/effect_wp_pot_whitig.ice",
                "actor/shot/effect_wp_pot_wideshot.ice",
                "actor/shot/effect_wp_pot_wlance_high.ice",
                "actor/shot/effect_wp_pot_zerodstrong.ice"
            };

        public static Dictionary<int, string> magNames = new Dictionary<int, string>()
        {
            { 1, "???,Alternate Mag?" },
            { 2, "マグ,Mag" },
            { 3, "ライラ,Lyra" },
            { 4, "フォルナクス,Fornax" },
            { 5, "レプス,Lepus"},
            { 6, "アントリア,Antlia"},
            { 7, "ライブラ,Libra"},
            { 8, "ドルフィヌス,Delphinus"},
            { 9, "キグナス,Cygnus"},
            { 10, "カエルム,Caelum"},
            { 11, "ケフェウス,Cepheus"},
            { 12, "ツカナ,Tsukana"},
            { 13, "カリーナ,Carina"},
            { 14, "モノケロス,Monoceros"},
            { 15, "オリオン,Orion"},
            { 16, "アプス,Apus"},
            { 17, "コルブス,Corvus"},
            { 18, "レオ,Leo"},
            { 19, "クルックス,Crux"},
            { 20, "リンクス,Lynx"},
            { 21, "ドラコ,Draco"},
            { 22, "シャト,Sato"},
            { 23, "ラッピー,Rappy"},
            { 24, "ジャック,Jack"},
            { 25, "ピート,Pete"},
            { 26, "キャンサー,Cancer"},
            { 27, "アクベンス,Acubens"},
            { 28, "アセルス,Asers"},
            { 29, "アルタルフ,Altarf"},
            { 30, "キトゥン,Kitten"},
            { 31, "カッツェ,Katze"},
            { 32, "ミーツェ,Miishe"},
            { 33, "クラーリタ,Clarita"},
            { 34, "ナナハナ,nanahana"},
            { 35, "アークマ,Arkuma"},
            { 36, "アークマミ,Arkumami"},
            { 37, "アンブラ,Umbra"},
            { 38, "トロ,Toro"},
            { 39, "クロ,Kuro"},
            { 40, "ハンプティ,Humpty"},
            { 41, "チャムライ,Chamurai"},
            { 42, "チャーク,Chark"},
            { 43, "リリーパ,Lillipan"},
            { 44, "ゴストン,Ghoston"},
            { 45, "ソニチ,Sonichi"},
            { 46, "プーシャン,Pushan"},
            { 47, "ミクダヨー,Mikudayo-"},
            { 48, "緑ぷよ,Green Puyo"},
            { 49, "カーバンクル,Carbuncle"},
            { 50, "キュゥべえ,Kyubey"},
            { 51, "ポリタン,Polytan"},
            { 52, "カガミミ,Kagamimi"},
            { 53, "ラブラッピー,Love Rappy"},
            { 54, "ラヴィラッピー,Lovey Rappy"},
            { 55, "キャリブー,Caribou" },

            { 56, ",Unidentified Black Bear"},

            { 57, "イーツター,Eatster (Intended spelling)"},
            { 58, "ミャリッジ,Wedding Bell"},
            { 59, "ベレイ,Berei"},
            { 60, "ベレイMk2,Berei Mk2"},
            { 61, "エトワル,étoile"},
            { 62, "月見ラッピー,Moon-Viewing Rappy"},
            { 63, "ソニック人形, Sonic Doll"},
            { 64, "モロ星人,Moro Alien"},
            { 65, "モロ星人B,Moro Alien B"},
            { 66, "ナイトギア,Nightgear"},
            { 67, "ニャウ,Nyau"},
            { 68, "ジャクラン,Jack Lan"},
            { 69, "テルクゥ,Teruku"},
            { 70, "キリゾー,Girizoo"},
            { 71, "SFC妖精,SFC Fairy"},
            { 72, "赤ぷよ,Red Puyo"},
            { 73, "ダンボー,Danboard"},
            { 74, "カラッピー,Karappy"},
            { 75, "タマヒメ,Tamahime"},
            { 76, "お団子ヘア,Dumpling Hair"},
            { 77, "ラブリーパ,LoveLipa"},
            { 78, "ラヴィリー,LoveLi"},
            { 79, "ドリキャス,Dreamcast"},
            { 80, "セガサターン,Sega Saturn"},
            { 81, "メガドラ,Mega Drive"},
            { 82, "アナライザー,Analyzer"},
            { 83, "ホヌホヌ,Honuhonu" },
            { 84, "小梅,Xiaomei"},
            { 85, "ニャンドリオン（ニャンD）,Nyandorion (NyanD)"},
            { 86, "A.I.S,A.I.S"},

            { 88, "ジーツター,Jiitsuter"},
            { 89, "レイニャン,Rainyan"},
            { 90, "ルクミン,Rukmin"},
            { 91, "ネッキー,Necky"},
            { 92, "リンクスR,Lynx R"},
            { 93, "キトゥンR,Kitten R"},
            { 96, "キャンサーR,Cancer R"},
            { 97, "アクベンスR,Acubens R"},
            { 100, "波乗ニャウ,Wave Riding Nyau"},
            { 101, "リリダイコ,Lilidaigo"},
            { 102, "RRリコ,RR Rico"},
            { 103, "ニドラー,Nidra"},
            { 104, "ピトリ,Pitri"},
            { 105, "プチアンガ,Petit Anga"},
            { 106, "ウサノヤ,Usanoya"},
            { 107, "モチュゴヤ,Mochugoya"},
            { 108, "オパオパ,Opa-Opa"},
            { 109, "紫ぷよ,Purple Puyo"},
            { 110, "テムジン,Temjin"},
            { 111, "青ぷよ,Blue Puyo"},
            { 112, "ルーシャー,Luther"},
            { 113, "バットリー,Batreat"},
            { 114, "シャノルン,Chanolun"},
            { 115, "ハッピー,Happy"},
            { 116, "ナガミミ,Nagamimi"},
            { 117, "ノルルン,Nolulun"},
            { 118, "クツッピー,Kutsuppy"},
            { 119, "ラブクマミ,Lovekumami"},
            { 120, "ラヴィクマ,LoveyKuma"},
            { 121, "チェリシュ,Cherish"},
            { 122, "オーディン,Odin"},
            { 123, "モーグリ,Moogle"},
            { 124, "プリニー,Prinny"},
            { 125, "東京タワーラッピー,Tokyo Tower Rappy"},
            { 126, "金シャチラッピー,Golden Whale Rappy"},
            { 127, "屋台ラッピー,Food Cart Rappy"},
            { 128, "ジンギスカンラッピー,Jingisukan Rappy"},
            { 129, "通天閣(R)ラッピー,Tsutenkaku (R) Rappy"},
            { 130, "ステルス化,Stealth"},
            { 131, "ケツカッチン,Ketsukacchin"},
            { 132, "エスカくん,Eska-kun"},
            { 133, "プリュミー,Plumii"},
            { 134, "光武二式（大神機）,Koubu MK II (OM)"},
            { 135, "光武二式（さくら機）,Koubu MK II (SM)"},
            { 136, "パティエンティア,Patty & Tiea"},
            { 137, "ワンダラー,Wanderer"},
            { 138, "ミニゴジラ,Mini Godzilla"},
            { 139, "ピートR,Pete R"},
            { 140, "ブラナート,Brownart"},

            { 143, "ポーラー,Polar"},
            { 144, "ポッド０４２,Pod 042"},
            { 145, "ポッド１５３,Pod 153"},
            { 146, "桜ニャウ,Sakura Nyau"},
            { 147, "フログラッピー,Frog Rappy"},
            { 148, "モア,Moa"},
            { 149, "スティレットＧ,Stylet G"},
            { 150, "エンペ・ラッピー,Empe Rappy"},
            { 151, "ヤミガラス,Yamigarasu"},
            { 152, "プラフタ,Plachta"},
            { 153, "ラタン・エンペ,Rotten Empe"},
            { 154, "アクス・ラッピー,ARKS Rappy"},
            { 155, "フェザーキャロル,Feather Carole"},
            { 156, "フェリチェマクス,Felice Max"},
            { 158, "ホワイトラプラス,White Laplace"},
            { 159, "エグ・ラッピー,Egg Rappy"},
            { 160, "ラヴィ・エンペ,Lovey Empe"},
            { 162, "パック,Puck"},
            { 164, "ラブ・エンペ,Love Empe"},
            { 166, "ダークラッピー,Dark Rappy"},
            { 167, "テルテルラッピー,Tell Tell Rappy"},
            { 168, "モルガナ,Morgana"},
            { 169, "バーゼラルドＧ,Baselard G"},
            { 170, "轟雷Ｇ,Gourai G"},
            { 171, "パートニャー,Partnya"},
            { 172, "プーギー,Poogie"},
            { 173, "レイチュ,Reichu"},
            { 174, "セント・ラッピー,Saint Rappy"},
            { 176, "ジャックフロスト,Jack Frost"},

            { 177, ",Ornate Japanese looking black pig"},
            { 178, "ちびレラ,Sabirera (Quartz Dragon/クォーツドラゴン)"},
            { 179, "サクリャ,Sakurya"},
            { 180, "リトルメデューナ,Little Meduna"},
            { 181, "キツネアメ,Kitsune Ame"},
            { 182, "カグヤ,Kaguya"},
            { 183, "ペルチョナ,Perchona"},
            { 184, "タマヒメ2,Tamahime 2"},
            { 185, "ペギー,Pegi"},
            { 186, "ペギータ,Pegita"},
            { 188, "Vハンター,V Hunter"},
            { 190, "パイ,Pai"},
            { 191, ",Ornate Japanese looking black mouse"},
            { 192, "チョトリ,Chotrea"},
            { 193, "ミルトリ,Miltrea"},
            { 194, "フェズ,Feath"},
            { 195, "カエルン,Kaerun"},
            { 196, "オッチャ,Ocha"},

            { 999, "Debug" }
        };

        public static Dictionary<int, string> magNamesNGS = new Dictionary<int, string>()
        {
            { 1, "???,Alternate Mag?" },
            { 2, "マグ,Mag" },
            { 3, "ライラ,Lyra" },
            { 4, "フォルナクス,Fornax" },
            { 5, "レプス,Lepus"},
            { 6, "アントリア,Antlia"},
            { 7, "ライブラ,Libra"},
            { 8, "ドルフィヌス,Delphinus"},
            { 9, "キグナス,Cygnus"},
            { 10, "カエルム,Caelum"},
            { 11, "ケフェウス,Cepheus"},
            { 12, "ツカナ,Tsukana"},
            { 13, "カリーナ,Carina"},
            { 14, "モノケロス,Monoceros"},
            { 15, "オリオン,Orion"},
            { 16, "アプス,Apus"},
            { 17, "コルブス,Corvus"},
            { 18, "レオ,Leo"},
            { 19, "クルックス,Crux"},
            { 20, "リンクス,Lynx"},
            { 21, "ドラコ,Draco"},
            { 22, "シャト,Sato"},
            { 23, "ラッピー,Rappy"},
            { 24, "ジャック,Jack"},
            { 25, "ピート,Pete"},
            { 26, "キャンサー,Cancer"},
            { 27, "アクベンス,Acubens"},
            { 28, "アセルス,Asers"},
            { 29, "アルタルフ,Altarf"},
            { 30, "キトゥン,Kitten"},
            { 31, "カッツェ,Katze"},
            { 32, "ミーツェ,Miishe"},
            { 33, "クラーリタ,Clarita"},
            { 34, "ナナハナ,nanahana"},
            { 35, "アークマ,Arkuma"},
            { 36, "アークマミ,Arkumami"},
            { 37, "アンブラ,Umbra"},
            { 38, "トロ,Toro"},
            { 39, "クロ,Kuro"},
            { 40, "ハンプティ,Humpty"},
            { 41, "チャムライ,Chamurai"},
            { 42, "チャーク,Chark"},
            { 43, "リリーパ,Lillipan"},
            { 44, "ゴストン,Ghoston"},
            { 45, "ソニチ,Sonichi"},
            { 46, "プーシャン,Pushan"},
            { 47, "ミクダヨー,Mikudayo-"},
            { 48, "緑ぷよ,Green Puyo"},
            { 49, "カーバンクル,Carbuncle"},
            { 50, "キュゥべえ,Kyubey"},
            { 51, "ポリタン,Polytan"},
            { 52, "カガミミ,Kagamimi"},
            { 53, "ラブラッピー,Love Rappy"},
            { 54, "ラヴィラッピー,Lovey Rappy"},
            { 55, "キャリブー,Caribou" },

            { 56, ",Unidentified Black Bear"},

            { 57, "イーツター,Eatster (Intended spelling)"},
            { 58, "ミャリッジ,Wedding Bell"},
            { 59, "ベレイ,Berei"},
            { 60, "ベレイMk2,Berei Mk2"},
            { 61, "エトワル,étoile"},
            { 62, "月見ラッピー,Moon-Viewing Rappy"},
            { 63, "ソニック人形, Sonic Doll"},
            { 64, "モロ星人,Moro Alien"},
            { 65, "モロ星人B,Moro Alien B"},
            { 66, "ナイトギア,Nightgear"},
            { 67, "ニャウ,Nyau"},
            { 68, "ジャクラン,Jack Lan"},
            { 69, "テルクゥ,Teruku"},
            { 70, "キリゾー,Girizoo"},
            { 71, "SFC妖精,SFC Fairy"},
            { 72, "赤ぷよ,Red Puyo"},
            { 73, "ダンボー,Danboard"},
            { 74, "カラッピー,Karappy"},
            { 75, "タマヒメ,Tamahime"},
            { 76, "お団子ヘア,Dumpling Hair"},
            { 77, "ラブリーパ,LoveLipa"},
            { 78, "ラヴィリー,LoveLi"},
            { 79, "ドリキャス,Dreamcast"},
            { 80, "セガサターン,Sega Saturn"},
            { 81, "メガドラ,Mega Drive"},
            { 82, "アナライザー,Analyzer"},
            { 83, "ホヌホヌ,Honuhonu" },
            { 84, "小梅,Xiaomei"},
            { 85, "ニャンドリオン（ニャンD）,Nyandorion (NyanD)"},
            { 86, "A.I.S,A.I.S"},

            { 88, "ジーツター,Jiitsuter"},
            { 89, "レイニャン,Rainyan"},
            { 90, "ルクミン,Rukmin"},
            { 91, "ネッキー,Necky"},
            { 92, "リンクスR,Lynx R"},
            { 93, "キトゥンR,Kitten R"},
            { 96, "キャンサーR,Cancer R"},
            { 97, "アクベンスR,Acubens R"},
            { 100, "波乗ニャウ,Wave Riding Nyau"},
            { 101, "リリダイコ,Lilidaigo"},
            { 102, "RRリコ,RR Rico"},
            { 103, "ニドラー,Nidra"},
            { 104, "ピトリ,Pitri"},
            { 105, "プチアンガ,Petit Anga"},
            { 106, "ウサノヤ,Usanoya"},
            { 107, "モチュゴヤ,Mochugoya"},
            { 108, "オパオパ,Opa-Opa"},
            { 109, "紫ぷよ,Purple Puyo"},
            { 110, "テムジン,Temjin"},
            { 111, "青ぷよ,Blue Puyo"},
            { 112, "ルーシャー,Luther"},
            { 113, "バットリー,Batreat"},
            { 114, "シャノルン,Chanolun"},
            { 115, "ハッピー,Happy"},
            { 116, "ナガミミ,Nagamimi"},
            { 117, "ノルルン,Nolulun"},
            { 118, "クツッピー,Kutsuppy"},
            { 119, "ラブクマミ,Lovekumami"},
            { 120, "ラヴィクマ,LoveyKuma"},
            { 121, "チェリシュ,Cherish"},
            { 122, "オーディン,Odin"},
            { 123, "モーグリ,Moogle"},
            { 124, "プリニー,Prinny"},
            { 125, "東京タワーラッピー,Tokyo Tower Rappy"},
            { 126, "金シャチラッピー,Golden Whale Rappy"},
            { 127, "屋台ラッピー,Food Cart Rappy"},
            { 128, "ジンギスカンラッピー,Jingisukan Rappy"},
            { 129, "通天閣(R)ラッピー,Tsutenkaku (R) Rappy"},
            { 130, "ステルス化,Stealth"},
            { 131, "ケツカッチン,Ketsukacchin"},
            { 132, "エスカくん,Eska-kun"},
            { 133, "プリュミー,Plumii"},
            { 134, "光武二式（大神機）,Koubu MK II (OM)"},
            { 135, "光武二式（さくら機）,Koubu MK II (SM)"},
            { 136, "パティエンティア,Patty & Tiea"},
            { 137, "ワンダラー,Wanderer"},
            { 138, "ミニゴジラ,Mini Godzilla"},
            { 139, "ピートR,Pete R"},
            { 140, "ブラナート,Brownart"},

            { 143, "ポーラー,Polar"},
            { 144, "ポッド０４２,Pod 042"},
            { 145, "ポッド１５３,Pod 153"},
            { 146, "桜ニャウ,Sakura Nyau"},
            { 147, "フログラッピー,Frog Rappy"},
            { 148, "モア,Moa"},
            { 149, "スティレットＧ,Stylet G"},
            { 150, "エンペ・ラッピー,Empe Rappy"},
            { 151, "ヤミガラス,Yamigarasu"},
            { 152, "プラフタ,Plachta"},
            { 153, "ラタン・エンペ,Rotten Empe"},
            { 154, "アクス・ラッピー,ARKS Rappy"},
            { 155, "フェザーキャロル,Feather Carole"},
            { 156, "フェリチェマクス,Felice Max"},
            { 158, "ホワイトラプラス,White Laplace"},
            { 159, "エグ・ラッピー,Egg Rappy"},
            { 160, "ラヴィ・エンペ,Lovey Empe"},
            { 162, "パック,Puck"},
            { 164, "ラブ・エンペ,Love Empe"},
            { 166, "ダークラッピー,Dark Rappy"},
            { 167, "テルテルラッピー,Tell Tell Rappy"},
            { 168, "モルガナ,Morgana"},
            { 169, "バーゼラルドＧ,Baselard G"},
            { 170, "轟雷Ｇ,Gourai G"},
            { 171, "パートニャー,Partnya"},
            { 172, "プーギー,Poogie"},
            { 173, "レイチュ,Reichu"},
            { 174, "セント・ラッピー,Saint Rappy"},
            { 176, "ジャックフロスト,Jack Frost"},

            { 177, ",Ornate Japanese looking black pig"},
            { 178, "ちびレラ,Sabirera (Quartz Dragon/クォーツドラゴン)"},
            { 179, "サクリャ,Sakurya"},
            { 180, "リトルメデューナ,Little Meduna"},
            { 181, "キツネアメ,Kitsune Ame"},
            { 182, "カグヤ,Kaguya"},
            { 183, "ペルチョナ,Perchona"},
            { 184, "タマヒメ2,Tamahime 2"},
            { 185, "ペギー,Pegi"},
            { 186, "ペギータ,Pegita"},
            { 188, "Vハンター,V Hunter"},
            { 190, "パイ,Pai"},
            { 191, ",Ornate Japanese looking black mouse"},
            { 192, "チョトリ,Chotrea"},
            { 193, "ミルトリ,Miltrea"},
            { 194, "フェズ,Feath"},
            { 195, "カエルン,Kaerun"},
            { 196, "オッチャ,Ocha"},

            { 999, "Debug" }
        };
    }
}
